#version 330 core

// Three output shapes selected by the engine's defines: USE_DEFERRED (G-buffer, SOLID/CUTOUT),
// USE_WATER_PREPASS (single wave-normal target), neither (forward colour, TRANSLUCENT). One
// compiled file — anything referenced outside the #ifdef chain must be declared in every arm.

#moj_import <fornax_runtime:brdf.glsl>
#moj_import <fornax_runtime:env_brdf.glsl>
#moj_import <fornax_runtime:wetness.glsl>
// emission.glsl expects LINEAR albedo; this stage's albedo is display-encoded (gAlbedo's storage space).
#moj_import <fornax_runtime:color.glsl>
#moj_import <fornax_runtime:emission.glsl>
#moj_import <fornax_runtime:puddles.glsl>
#moj_import <fornax_runtime:snow.glsl>
#moj_import <fornax_runtime:water_reflection.glsl>
#moj_import <fornax_runtime:water_waves.glsl>
#moj_import <fornax_runtime:water_interaction.glsl>
#moj_import <fornax_runtime:shore_spill.glsl>
// Generated by the engine from blocks.toml; supplies MAT_WATER. See blocks.toml for the no-IPBR rule.
#moj_import <fornax_runtime:materials.glsl>

// Recovers full-resolution overflow-page samples when the atlas spills past page 0 (spilled
// sprites' baked UVs otherwise point at quarter-scale ghosts). No-op when unpaged.
#moj_import <fornax:block_atlas.glsl>

// Eases spilled sprites from full to quarter (ghost) resolution between these distances, trading
// only sharpness, to bound overflow-layer cache pressure near the camera.
const float PLAGUE_ATLAS_FULL_RES_DIST = 8.0;
const float PLAGUE_ATLAS_GHOST_DIST = 32.0;

// Byte-identical across gbuffer_resolve.fsh, ssr_trace.fsh, ssr_blur.fsh — mismatched declarations are a load error.
#define PLAGUE_WETNESS_PCT 75 //[0 25 50 75 100 125 150 200] compile "Wet Surfaces and Puddles" {0="Off" 25="Barely" 50="Damp" 75="Wet" 100="Very Wet" 125="Soaked" 150="Drenched" 200="Flooded"}

// Read BY NAME by the engine (gates the water pre-pass on SSR_WATER_MODE/SSR_QUALITY) — a contract,
// not a pack choice. Every declaring file must match byte-identically.
#define SSR_QUALITY 1 //[0 1 2] compile "Reflections" {0="Off" 1="Fancy" 2="Fast"}
#define SSR_WATER_MODE 2 //[0 1 2] compile "Water Surface" {0="Vanilla" 1="Shaded" 2="Reflective"}

// Wave complexity is fixed at compile time; only strength (u_WaveStrength, bridged below) is a runtime scalar.
#define PLAGUE_WATER_INTERACTION 1 //[0 1 2] compile "Player Water Interaction" {0="Off" 1="Quality" 2="Performance"}
#define PLAGUE_WATER_MESH_DISPLACEMENT 1 //[0 1] compile "Water Mesh Displacement" {0="Off" 1="Standard"}

// Screen-space refraction on glass, ice and stained panes. A gate, not a magnitude: strength is
// u_RefractStrength. Compile-time so Off drops the block and both its texture reads.
#define PLAGUE_GLASS_REFRACTION 1 //[0 1] compile "Glass Refraction" {0="Off" 1="On"}
// KEPT COMPILE, deliberately: `#if PLAGUE_PUDDLE_RIPPLE_PCT > 0` elides the whole impact evaluation,
// and a runtime version would keep that code resident in the hottest shader in the pack.
#define PLAGUE_PUDDLE_RIPPLE_PCT 100 //[0 50 100 150 200 300] compile "Puddle Ripples" {0="Off" 50="Subtle" 100="Standard" 150="Strong" 200="Heavy" 300="Extreme"}
// ON: height-map-shaped puddle placement (puddles.glsl). OFF: falls back to the same uniform
// sky-facing wetness the forward arm below uses (plagueSurfaceWetness/plagueApplyWetness).
#define PLAGUE_PUDDLE_SHAPE //[] compile "Puddle Shape"
// Reads the field water_shore.comp writes. Scaled by PLAGUE_WETNESS_PCT below like every other wet
// surface, and dead without PLAGUE_WATER_INTERACTION, which is what runs the pass that fills it.
#define PLAGUE_SHORE_SPILL 1 //[0 1] compile "Shoreline Spill" {0="Off" 1="On"}
// Paints the spill field's stage code flat over albedo. Black = the compute pass never wrote this
// texel, red = the clipmap publishes no column here, blue = the column is water, orange = dry with
// no water neighbour, yellow = dry beside water but the crest stays under the block top, green =
// washing. Separates every way the chain can produce nothing, in one frame.
#define PLAGUE_SHORE_DEBUG 0 //[0 1] compile "Shore Spill Debug" {0="Off" 1="Stage Codes"}

// DEFAULT OFF: repaints a large fraction of every snowy biome, so the user opts in knowingly.
// Do not write the bracket-annotation syntax out in this comment as prose — OptionAnnotation
// hard-errors on any line containing it, even in comments.
#define PLAGUE_SNOW_DUSTING 1 //[0 1] compile "Snow Dusting" {0="Off" 1="On"}
// Amount is the runtime slider u_SnowAmount (below) — a coverage threshold, not compile-gated.
// Split from ground dusting because they're different mechanisms (snow.glsl); foliage is the harder half.
#define PLAGUE_SNOW_ON_FOLIAGE 1 //[0 1] compile "Snow on Foliage" {0="Off" 1="On"}

uniform sampler2D u_BlockTex;
uniform sampler2D u_NormalTex;   // labPBR _n: tangent-space normal in rg, AO in b, height in a
uniform sampler2D u_MaterialTex; // labPBR _s: smoothness in r, F0 in g, porosity/SSS in b

// builtin.spriteBounds: grid cell holds (u0,v0,u1,v1) for the sprite at that position. texelFetch
// only — filtering would blend two sprites' rects into a bogus third.
uniform sampler2D u_GeomInput0;
// builtin.spriteHeightRange: (trueMin, trueMax, robustMin, robustMax; robust = 1st/99th percentile).
// Puddle placement reads only the WIDTH, as a presence test — the authored height itself stays unscaled.
uniform sampler2D u_GeomInput1;
// builtin.noise: the engine's 512x512 tileable RGBA noise, sampled REPEAT. Used for puddle
// placement: R is 16-cell value noise, B is a 4-octave FBM. See shaders/include/puddles.glsl.
uniform sampler2D u_GeomInput2;
// waterWaveB.history: previous actor-centred (pressure, velocity, dPdx, dPdy). Appended after the
// three established slots so every existing lookup keeps its index.
uniform sampler2D u_GeomInput3;
// sceneHdrComposited: scene-linear HDR, final for the frame by the translucent draw. The background
// refraction bends. TRANSLUCENT ONLY: SOLID and CUTOUT share this shader and bind group but run
// before the passes that write it, so they read last frame's colour with no error anywhere.
uniform sampler2D u_GeomInput4;
// builtin.depth_opaque: reversed-Z opaque depth, captured at the end of the graph so a translucent
// draw can read it without touching the live attachment it tests against. Rejects a refracted sample
// that landed in front of the pane. Same translucent-only rule as u_GeomInput4.
uniform sampler2D u_GeomInput5;
// shoreWetness.history: (film, soak) left on dry blocks by a crest clearing their top, on the wave
// solve's own actor-centred grid. Appended last; every earlier index keeps its slot.
uniform sampler2D u_GeomInput6;



// std140 UBO bridging runtime options into a DEFERRED pass (no u_PackOptions block here — see
// shaders.md rule 4). Member order is a contract with Java: PbrSettingsLayoutContractTest asserts
// this block name-for-name, in order, against PbrSettingsLayout.MEMBERS. APPEND ONLY — inserting
// moves every later member's std140 offset with no compile error. Fornax's own fallback terrain.fsh
// and one of its test fixtures declare only a short prefix of this same struct, legal only because
// that prefix stays stable.
layout(std140) uniform u_PbrSettings {
    float u_BumpStrength;
    float u_AOStrength;
    float u_PomDepth;
    float u_PomQuality;
    float u_PomDistance;
    float u_PomAllowCutout;
    float u_PomDebug;
    float u_AuthoredEmission;
    // --- Fog + display transform, bridged for the forward TRANSLUCENT arm at the bottom of this
    // file (glass/ice/honey), which composites after the tonemap and needs the same veil. ---------
    float u_FogDensity;
    float u_FogBorderDensity;
    float u_ScreenBrightness;
    float u_Exposure;
    float u_TmContrast;
    float u_TmWhitePath;
    float u_TmDarkDesaturation;
    float u_Saturation;
    float u_Contrast;
    // --- Wave strength, snow amount, splash density: continuous runtime sliders, declared in
    // gbuffer_resolve.fsh --------------------------------------------------------------------------
    float u_WaveStrength;
    float u_SnowAmount;
    float u_SplashDensity;
    // Underwater depth-darkening floor, for the glass arm's eye-in-water veil. Declared in gbuffer_resolve.fsh.
    float u_DepthDarkness;
    // Gates the gAlbedoOut diagnostic repaint below. Declared in gbuffer_resolve.fsh.
    float u_AlbedoIdentityDebug;
    float u_WaveSpeed;
    // Atmosphere six: this arm's fog colour IS the sky colour, so glass must see exactly what the
    // resolve sees. Declared in atmosphere.glsl.
    float u_AirDensity;
    float u_AirTurbidity;
    float u_AirOzone;
    float u_SunIntensity;
    float u_MoonIntensity;
    float u_NightScotopic;
    // Dome ten, same reason. Declared in sky.glsl.
    float u_TwilightSpan;
    float u_SkyGradient;
    float u_SunsetBandWidth;
    float u_SunsetBandHeight;
    float u_SunGlowStrength;
    float u_SunGlowTightness;
    float u_MoonGlowStrength;
    float u_MoonGlowTightness;
    float u_SkyBrightness;
    float u_SkyBiomeTint;
    // Warmth; two are never read here but must be declared to keep sky.glsl's reachability contract.
    float u_SunsetSkyWarmth;
    float u_SunsetTemp;
    float u_SunsetLightWarmth;
    float u_AmbientSkyBleed;
    // Fog drive seventeen: this arm expands PLAGUE_FOG_DRIVE, so every name that macro reaches must
    // be a member here. Order matches fog_options.glsl.
    float u_FogDistance;
    float u_FogSharpness;
    float u_FogHeight;
    float u_FogHighAltitude;
    float u_FogMorningMist;
    float u_FogNight;
    float u_FogDayVariance;
    float u_FogRainResponse;
    float u_FogRainDepth;
    float u_FogWetMist;
    float u_FogColdMist;
    float u_FogDryClear;
    float u_FogClimbRise;
    float u_FogCaveGuardLo;
    float u_FogCaveGuardHi;
    float u_FogBorderGateNear;
    float u_FogBorderGateFar;
    float u_FogMistReach;
    float u_FogEnableDistance;
    float u_FogEnableEdge;
    float u_FogEnableMorning;
    float u_FogEnableNight;
    float u_FogEnableWet;
    float u_FogEnableCold;
    float u_FogEnableDry;
    float u_FogAdvanced;
    float u_FogMorningDensity;
    float u_FogMorningDistance;
    float u_FogMorningSharpness;
    float u_FogNightDensity;
    float u_FogNightDistance;
    float u_FogNightSharpness;
    float u_FogWetDensity;
    float u_FogWetDistance;
    float u_FogWetSharpness;
    float u_FogColdDensity;
    float u_FogColdDistance;
    float u_FogColdSharpness;
    float u_FogDryDensity;
    float u_FogDryDistance;
    float u_FogDrySharpness;
    float u_PomShadowStrength;
    // APPENDED LAST by the std140 ABI rule.
    float u_RefractStrength;
};

// Import order is load-bearing: fog.glsl/tonemap.glsl declare these as #defines too, which the
// offline compiler (unlike the device) does not rewrite away. Declaring the block ABOVE these
// imports means the offline #define only shadows the block's later use, not its declaration; an
// import placed above the block would let `#define u_Exposure 1.0` corrupt the member itself.
#moj_import <fornax:globals.glsl>
// Shared fog + sky colour. One definition across five call sites (gbuffer_resolve, water_composite,
// banner_patterns, particles_translucent, here) that must agree or glass hazes to a different colour.
#moj_import <fornax_runtime:fog.glsl>
// The display transform, shared with tonemap.fsh. Needed because this arm's output is
// display-referred and the fog colour is linear scene light; see plagueCompositeLinearOverDisplay.
#moj_import <fornax_runtime:tonemap.glsl>

// Placed after u_PbrSettings, not with the top imports: parallaxSelfShadow reads
// u_PomShadowStrength from that block, so this import must come after it.
#moj_import <fornax_runtime:parallax_terrain.glsl>

in vec4 v_Color;
in vec4 v_RawTint;
in vec2 v_TexCoord;
in vec3 v_WorldPos;
in vec3 v_WaterBasePos;
in vec3 v_FaceNormal;
in float v_BlockLight;
in float v_SkyLight;
in vec2 v_MotionVector;
in vec3 v_SunDirection;
flat in vec3 v_CameraAbs;
flat in float v_Wetness;
flat in uint v_MaterialId;
flat in float v_WaveClock;
flat in float v_RainLevel;
// 1 where RAIN falls on this block's biome, 0 for snow/nothing — collapsed from a 0/1/2 type in
// terrain.vsh so it can be used as a plain multiplier below.
flat in float v_RainsHere;
// 1 where SNOW falls. Declared unconditionally (unlike a vertex-only output, a fragment input with
// no matching vertex output is a link error) even though only the snow dusting reads it.
flat in float v_SnowsHere;
// This block's own light level, 0..1 from vanilla's 0-15. Same declare-unconditionally reason as v_SnowsHere.
flat in float v_LightEmission;
// 1.0 when the engine says this block is in vanilla's #minecraft:coal_ores tag, else 0.0. Consumed
// by exactly one line, the authored-emission gate in the emission block below.
flat in float v_CoalClass;

#ifdef USE_WATER_PREPASS
// EXACTLY ONE output — the engine binds a single RGBA16_SNORM attachment for this pass identity;
// a count mismatch is a validation failure at setPipeline.
//
// Encode contract, decoded by ssr_trace_water.fsh and water_composite.fsh:
//   rgb = wave world-normal, SNORM [-1,1], unit length
//   a   = SIGNED. Magnitude carries presence + sky light, sign carries RAIN (not snow) on this biome:
//           |a| >= 0.5   -> water is here;  skyLight = (|a| - 0.5) * 2.0
//           a  >  0      -> rain falls here      a  <  0  -> it does not (incl. anywhere it snows)
//           a  == 0.0    -> no water
layout(location = 0) out vec4 waterNormalOut;
#elif defined(USE_DEFERRED)
layout(location = 0) out vec4 gNormalOut;
layout(location = 1) out vec4 gAlbedoOut;
layout(location = 2) out vec4 gMaterialOut;
layout(location = 3) out vec4 gAoOut;
layout(location = 4) out vec2 gMotionOut;
#else
out vec4 fragColor;
#endif

vec3 plagueInteractionNormal(vec3 baseNormal, vec3 worldPos, vec3 faceNormal) {
#if PLAGUE_WATER_INTERACTION != 0
    // The committed centre is the previous actor position at geometry time.
    vec2 previousCentre = u_LocalActorPosition.xz - u_LocalActorMotion.xz;
    vec4 waves = plagueInteractionSample(u_GeomInput3, worldPos, previousCentre,
            PLAGUE_WATER_INTERACTION);
    vec2 gradient = waves.zw;
    // The fourth root is a huge amplifier at the bottom of its range (pressure 0.01 reads at ~43%
    // visual strength), so the dead zone below suppresses the numerical noise floor while leaving genuine wakes untouched.
    float amplitude = clamp(1.35 * sqrt(sqrt(abs(waves.x))), 0.0, 1.0)
            * smoothstep(0.004, 0.02, abs(waves.x));
    float topSurface = smoothstep(0.65, 0.95, faceNormal.y);
    vec3 interactionNormal = normalize(vec3(-gradient.x, 1.0, -gradient.y));
    return normalize(mix(baseNormal, interactionNormal,
            amplitude * topSurface));
#else
    return baseNormal;
#endif
}

void main() {
    vec3 faceNormal = normalize(v_FaceNormal);
    vec3 dPosX = dFdx(v_WorldPos);
    vec3 dPosY = dFdy(v_WorldPos);
    vec2 dUvX  = dFdx(v_TexCoord);
    vec2 dUvY  = dFdy(v_TexCoord);

    float det = dUvX.x * dUvY.y - dUvY.x * dUvX.y;
    vec3 tangent;
    vec3 bitangent;
    if (abs(det) > 1e-12) {
        // Both axes from the UV derivatives, not cross(faceNormal, tangent): that guess is
        // orthogonal but blind to which way V runs, and Minecraft mirrors UVs per face.
        tangent = (dPosX * dUvY.y - dPosY * dUvX.y) * sign(det);
        bitangent = (dPosY * dUvX.x - dPosX * dUvY.x) * sign(det);
        tangent = normalize(tangent);
        bitangent = normalize(bitangent);
    } else {
        // Degenerate UVs (a face collapsed to a point on screen): fall back rather than divide by ~0.
        vec3 up = abs(faceNormal.y) < 0.99 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
        tangent = normalize(cross(up, faceNormal));
        bitangent = cross(faceNormal, tangent);
    }
    // Re-orthogonalize against the face normal for noisy silhouette-edge derivatives; bitangent
    // keeps its own measured direction rather than being regenerated (the point of the branch above).
    tangent = normalize(tangent - faceNormal * dot(faceNormal, tangent));
    bitangent = normalize(bitangent - faceNormal * dot(faceNormal, bitangent));

    bool isWater = v_MaterialId == uint(MAT_WATER);

    // Fades fine wave octaves with distance to avoid sub-pixel aliasing shimmer. 96 blocks reaches
    // full falloff around a lake's far edge, not a third of the way across it.
    float waveDistFalloff = 1.0 - exp(-length(v_WaterBasePos) / 96.0);

#ifdef USE_WATER_PREPASS
    // The pre-pass draws the whole TRANSLUCENT layer (glass, leaves, water); non-water must discard
    // or every window gets a wave field and the reflection chain treats it as a lake.
    if (!isWater) {
        discard;
    }

    vec3 waterAbsolute = v_CameraAbs + v_WaterBasePos;
    vec3 prepassNormal = plagueWaveNormal(
            u_GeomInput2, waterAbsolute,
            plagueWaveAnimatedTime(v_WaveClock, u_WaveStrength, u_WaveSpeed), waveDistFalloff,
            faceNormal, tangent, bitangent, u_WaveStrength);
    prepassNormal = plagueInteractionNormal(
            prepassNormal, waterAbsolute, faceNormal);

    float waterPixelFootprint = max(
            length(dFdx(v_WaterBasePos)), length(dFdy(v_WaterBasePos)));
    float unresolvedSlopeVariance = plagueWaveUnresolvedSlopeVariance(
            u_WaveStrength, waterPixelFootprint, waveDistFalloff, waterAbsolute.xz);
    float waterRoughness = plagueWaterRoughnessFromSlopeVariance(
            unresolvedSlopeVariance);

    // Nothing else here: this pass exists only to hand SSR a surface to reflect off; everything
    // else is computed (and shaded) in water_composite.fsh.
    float waterFlags = 0.5 + 0.5 * clamp(v_SkyLight, 0.0, 1.0);
    float signedWaterFlags = v_RainsHere > 0.5 ? waterFlags : -waterFlags;
    waterNormalOut = plagueEncodeWaterReflectionSurface(
            prepassNormal, waterRoughness, signedWaterFlags);
    return;
#endif

    // Cutout alpha test uses the ORIGINAL coordinate, never the parallax-offset one: alpha defines
    // shape, and displacing it makes solid panels fill in or open gaps.
    // Derivatives of the UNWRAPPED coordinate, before parallax — a wrapped coordinate's own
    // derivatives are meaningless at the atlas seam.
    vec2 ddx = dFdx(v_TexCoord);
    vec2 ddy = dFdy(v_TexCoord);

    vec2 uv = v_TexCoord;
    float pomTravel = 0.0;
    // Ray depth reached, 0..1 (1.0 = polygon plane). MUST default to 1.0: a fragment that never
    // marches would otherwise read as fully displaced and self-shadow a surface with no displacement.
    float pomHit = 1.0;

    // The sprite rectangle covering this fragment, from the atlas rather than from the geometry.
    vec4 spriteBounds = fornax_spriteGridCell(u_GeomInput0, v_TexCoord);

    // Validity, not just non-emptiness: the rectangle must contain the coordinate that looked it up.
    // An unresolved graph input binds noise, which fails this test, so a missing table disables
    // rather than corrupts.
    bool haveBounds = spriteBounds.z > spriteBounds.x && spriteBounds.w > spriteBounds.y
            && v_TexCoord.x >= spriteBounds.x && v_TexCoord.x <= spriteBounds.z
            && v_TexCoord.y >= spriteBounds.y && v_TexCoord.y <= spriteBounds.w;

#ifdef ALPHA_CUTOUT
    // Skipped unless asked for: displacing the coordinate a cutout's shape is read from makes
    // leaves and doors gain/lose material as the camera moves.
    bool pomAllowed = u_PomAllowCutout > 0.5;
#else
    bool pomAllowed = true;
#endif

    // v_WorldPos is camera-relative, so the direction back to the eye is simply its negation.
    vec3 viewWorld = normalize(-v_WorldPos);
    vec3 viewTangent = vec3(dot(viewWorld, tangent), dot(viewWorld, bitangent), dot(viewWorld, faceNormal));

    int pomSteps = int(u_PomQuality);

    // Fitted S-curve fade, band scaled by u_PomDistance; computed once, shared by the march and the
    // self-shadow ray. 1 = full parallax close in, 0 past the band.
    float pomFade = plaguePomDistanceFade(length(v_WorldPos), u_PomDistance);

    // A viewTangent.z near zero divides each step up toward infinity, flinging the march off the
    // sprite at exactly the grazing angles parallax is meant to look best at.
    if (pomAllowed && haveBounds && pomSteps > 0 && u_PomDepth > 0.0 && viewTangent.z > 0.1) {
        // A texel already at the top of the labPBR range has nothing to descend into.
        //
        // The gate must not scale the march's depth: a view ray is a property of the eye, not of
        // the texel it lands on, so neighbouring fragments must march the same slope.
        float surfaceHeight = plaguePagedNormalGrad(v_TexCoord, ddx, ddy).a;
        if (pomFade > 0.0 && surfaceHeight < (254.0 / 255.0)) {
            vec2 spriteSize = spriteBounds.zw - spriteBounds.xy;
            vec2 local = (v_TexCoord - spriteBounds.xy) / spriteSize;
            local = parallaxLocal(local, viewTangent, spriteBounds,
                    u_PomDepth, pomSteps, ddx, ddy, pomTravel, pomHit, pomFade);
            uv = spriteToAtlas(local, spriteBounds);
        }
    }

    // Self-shadowing, computed at the coordinate parallax actually landed on.
    float pomShadow = 1.0;
    if (pomAllowed && haveBounds && pomSteps > 0 && u_PomDepth > 0.0) {
        vec2 spriteSize = spriteBounds.zw - spriteBounds.xy;
        vec2 shadowLocal = (uv - spriteBounds.xy) / spriteSize;
        vec3 sunWorld = normalize(v_SunDirection);
        vec3 sunTangent = vec3(dot(sunWorld, tangent), dot(sunWorld, bitangent), dot(sunWorld, faceNormal));

        // The shadow ray starts from pomHit (where the march actually stopped), not from the
        // landed texel's own height: that texel may be a raised feature's TOP with the ray still
        // part-way down its side, and starting from the top makes crevice shadows unreachable —
        // a bright rim around a dark interior that reads as a dish rather than raised brick.
        float landedHeight = plaguePagedNormalGrad(uv, ddx, ddy).a;
        // Written as a max, which is identical to `min(landedHeight, pomHit)`:
        // a - max(0, a - b) IS min(a, b).
        float pomOvershoot = max(landedHeight - pomHit, 0.0);

        pomShadow = parallaxSelfShadow(shadowLocal, landedHeight, pomOvershoot,
                sunTangent, spriteBounds, ddx, ddy, pomFade);
    }

    // Gradients stay the ORIGINAL v_TexCoord derivatives even at a POM-marched uv (the file's
    // standing convention); the helper scales them for the overflow layer's quarter-to-full remap.
    float atlasGhostShare = smoothstep(PLAGUE_ATLAS_FULL_RES_DIST, PLAGUE_ATLAS_GHOST_DIST,
            length(v_WorldPos));
    vec4 albedo = fornax_sampleBlockAtlasBlendGrad(u_BlockTex, uv, ddx, ddy, atlasGhostShare);

#ifdef ALPHA_CUTOUT
    // At the parallax coordinate only when parallax is allowed on cutouts; else uv == v_TexCoord.
    if (albedo.a < ALPHA_CUTOUT) {
        discard;
    }
#endif

#ifdef USE_DEFERRED
    // Tinted albedo, unlit. Biome tint belongs in the G-buffer (foliage textures are greyscale
    // without it) but the lightmap does not: the resolve applies lighting once, and folding it in
    // here would light terrain twice.
    //
    // Decode texture AND tint (both are picked colours), multiply by the shade*AO scalar
    // (v_RawTint.a, already linear) in linear space, then re-encode: multiplying in display space
    // first would raise the linear shade/AO factor to decode's ~2.4 power, over-darkening every
    // non-top face. v_RawTint.rgb is the pure tint; v_RawTint.a is Sodium's separate shade*AO scalar.
    vec3 rawAlbedo = plagueLinearToSrgb(
            plagueSrgbToLinear(albedo.rgb) * plagueSrgbToLinear(v_RawTint.rgb) * v_RawTint.a);

    // Diagnostics, painted instead of the texture. False-coloured, not greyscale: a plausible-looking
    // grayscale magnitude gets lit/fogged/tonemapped like real albedo and misreads as a material.
    //   1: labPBR height map (RED = surface, BLUE = 25% deep)
    //   2: parallax self-shadow (RED = lit, BLUE = occluded)
    //   3: march travel fraction (BLUE = stopped immediately, RED = ran to the end)
    //   4: which rung of the height fallback ladder this fragment took
    //   5: the trimmed height range's two bounds and width, as raw magnitudes
    if (u_PomDebug > 0.5) {
        if (u_PomDebug < 1.5) {
            rawAlbedo = plagueDebugRamp(
                    plaguePagedNormalGrad(uv, ddx, ddy).a);
        } else if (u_PomDebug < 2.5) {
            rawAlbedo = plagueDebugRamp(pomShadow);
        } else if (u_PomDebug < 3.5) {
            rawAlbedo = plagueDebugRamp(pomTravel);
        }
    }

    // labPBR _n: rg is the tangent-space normal, b is per-texel AO (NOT the normal's Z, which is
    // reconstructed from xy below), a is height.
    vec4 normalSample = plaguePagedNormalGrad(uv, ddx, ddy);
    // Green decoded WITHOUT a flip: bitangent is the measured direction of increasing V, and atlas V
    // runs DOWN the sprite, so the raw channel already matches. A pack authored the other way would
    // need -tangentXY.y here.
    //
    // Neutral byte 128 by convention (labPBR defines no encoder, just the 0..255 -> left..right
    // mapping); this maps neutral to exactly 0.0 and byte 255 to +1.0, letting byte 0 undershoot
    // to -128/127 (absorbed by the clamp under the sqrt below):
    //   x = (byte - 128) / 127
    // u_BumpStrength scales XY before Z is rebuilt from the unit-length constraint, so the result
    // stays unit length by construction.
    vec3 nTex = normalSample.rgb;
    vec2 tangentXY;
    if (all(lessThan(nTex, vec3(0.003)))) {
        // All-black _n texel = "no normal authored"; downstream sees a flat face.
        tangentXY = vec2(0.0);
    } else {
        tangentXY = nTex.xy * PLAGUE_NORMAL_XY_SCALE + PLAGUE_NORMAL_XY_BIAS;
        tangentXY *= clamp(u_BumpStrength, 0.0, 2.0);
    }
    float tangentZ = sqrt(clamp(1.0 - dot(tangentXY, tangentXY), 0.0, 1.0));
    float bakedAo  = mix(1.0, normalSample.b, u_AOStrength);

    // Frame derived from how atlas UVs vary across the surface, not guessed from face normal + an
    // up-vector: a guessed frame is rotated/mirrored on most face directions, lighting bumps wrong.
    vec3 worldNormal = normalize(tangent * tangentXY.x + bitangent * tangentXY.y + faceNormal * tangentZ);

    // textureLod at a WHOLE level, not textureGrad: labPBR `_s` is four categorical/split lanes and
    // every hardware interpolation of it invents a material. See plagueMaterialLod.
    vec4 materialSample = plaguePagedMaterialLod(uv, ddx, ddy);

    // --- Does this quad's normal actually describe this quad? ------------------------------------
    // v_FaceNormal is snapped to the dominant cardinal axis, which is 45 degrees off the true normal
    // on cross-plates (grass, flowers) and biases the reflection term toward the sky. Suppresses
    // smoothness instead of fixing the normal (a true normal needs SSS to avoid a dark backlit tuft),
    // gated by dot(faceNormal, geoNormal) so only the mis-snapped quads lose reflection; not gated on
    // ALPHA_CUTOUT since axis-aligned cutout geometry (doors, rails) would lose reflections for nothing.
    vec3 geoNormal = cross(dPosX, dPosY);
    float geoLen = length(geoNormal);
    // |sin| between the derivative vectors; near zero only where the quad is edge-on. Guards against
    // normalizing a near-zero cross product at grazing angles, which would report a random direction.
    float geoSine = geoLen / max(length(dPosX) * length(dPosY), 1e-20);
    // cos(45deg)/cos(22.5deg): 0.7071 is exactly where a cross plate lands; the upper edge is half
    // that angle, so a quad tilted less than halfway toward the cross case keeps full smoothness.
    const float PLAGUE_NORMAL_TRUST_LO = 0.70710678;
    const float PLAGUE_NORMAL_TRUST_HI = 0.92387953;
    // gbuffer_resolve's own reflection floor (smoothstep(0.1, 0.35, smoothness) is zero at/below
    // this), so clamping here costs nothing that was ever traced.
    const float PLAGUE_UNTRUSTED_SMOOTHNESS = 0.1;
    float normalTrust = 1.0;
    if (geoSine > 0.05) {
        // abs() absorbs only the cross product's winding sign: deriveFaceIndex keeps the true
        // normal's own sign, so a real disagreement can never present as a sign flip.
        normalTrust = smoothstep(PLAGUE_NORMAL_TRUST_LO, PLAGUE_NORMAL_TRUST_HI,
                                 abs(dot(faceNormal, geoNormal / geoLen)));
    }
    // min(), never a mix() onto the floor: a genuinely matte cross plate must stay matte rather than
    // being lifted up to the floor by the very clamp that exists to hold surfaces below it.
    materialSample.r = min(materialSample.r,
                           mix(PLAGUE_UNTRUSTED_SMOOTHNESS, 1.0, normalTrust));

    // --- Emission ------------------------------------------------------------------------------
    // Two signals, MAXED not multiplied: the `_s` alpha is the artist's authored glow (per-texel,
    // sentinel byte 255 = "unauthored"), vanilla's block light level is what actually lights the
    // world. Multiplying would zero out any block strong on only one (ore: light 0, real _s dither;
    // glowstone: light 15, flat 255 "_s" sentinel). Coal ore is excluded from the authored lane by
    // its vanilla tag (v_CoalClass), not by texture statistics — its authored dither is
    // statistically indistinguishable from copper's. u_AuthoredEmission scales the authored lane
    // only; the block lane is unscaled (glowstone/lanterns are tuned to read correctly unscaled).
    // The emitter-luminance curve (emission.glsl) applies to the block lane only, here in the
    // geometry stage, because gAo.g is one channel and the two lanes must stay separable before max.
    bool unauthoredSprite = materialSample.a >= (254.5 / 255.0);
    float emissionShape = unauthoredSprite ? 1.0 : materialSample.a;
    // Authored scale is 0..254 (255 is the ignored sentinel); rescale so byte 254 reads exactly 1.0.
    float emissionAuthored = unauthoredSprite ? 0.0
            : min(materialSample.a * (255.0 / 254.0), 1.0);
    float emission = max(plagueEmitterLuminance(plagueSrgbToLinear(rawAlbedo))
                             * v_LightEmission * emissionShape,
                         emissionAuthored * u_AuthoredEmission
                             * (v_CoalClass > 0.5 ? 0.0 : 1.0));

    // --- Puddles -----------------------------------------------------------------------------
    // Applied HERE, not in the resolve: placement needs the height map (only available in this
    // stage), and the flattened normal must be baked into the G-buffer before the resolve runs.
    // Writing wetted material out also keeps the reflection trace, blur and resolve's Fresnel from
    // disagreeing about how wet a pixel is.
#if PLAGUE_WETNESS_PCT > 0
    PlagueMaterial puddleMat = plagueDecodeMaterial(materialSample.r, materialSample.g, materialSample.b);
    float puddleSmoothness = materialSample.r;
    float puddleF0 = materialSample.g;

    // Shoreline spill (shore_spill.glsl): what the wave solve left on this block after a crest
    // cleared its top. Read before the placement split so both puddle arms fold it in, and folded
    // in rather than applied separately -- a second darkening pass over the same fragment would
    // darken a rain-wet fringe twice.
    vec2 shoreSpill = vec2(0.0);
#if PLAGUE_SHORE_SPILL != 0 && PLAGUE_WATER_INTERACTION != 0
    // Absolute world position, and the centre the field was WRITTEN against, same as every other
    // reader of an actor-centred field: camera-relative here would drag the wet patch along.
    vec4 shoreField = plagueShoreSample(u_GeomInput6, v_CameraAbs + v_WorldPos,
            u_LocalActorPosition.xz - u_LocalActorMotion.xz, PLAGUE_WATER_INTERACTION);
    shoreSpill = shoreField.rg * (float(PLAGUE_WETNESS_PCT) / 100.0);
#if PLAGUE_SHORE_DEBUG != 0
    // Before the face gate below, so a stage code shows on every face rather than only the top.
    rawAlbedo = plagueShoreStageColour(shoreField.b);
#endif
    // The field is one value per world COLUMN, so without a face gate a wash wets the block's
    // vertical sides and its underside too. Same ramp bounds plaguePuddleAmount uses.
    shoreSpill *= smoothstep(0.71, 0.94, faceNormal.y);
#endif
#ifdef PLAGUE_PUDDLE_SHAPE
    // Clamped to 1: placement maths below assumes a normalised soak; letting it exceed 1 degenerates every threshold.
    //
    // No per-block gate here: v_Wetness already carries the biome-rain gate (terrain.vsh multiplies
    // by v_RainsHere). One gate, one place — two gates on the same quantity dries borders from both sides.
    float puddleWetness = clamp(v_Wetness * (float(PLAGUE_WETNESS_PCT) / 100.0), 0.0, 1.0);
    // A water film is a weather response, not authored metadata — a missing `_s` cannot veto it
    // (bedrock has no sidecar and still holds rain).
#ifdef ALPHA_CUTOUT
    // No standing water on cutout geometry (leaves pass "faces up + sees sky" but don't pool water).
    // Gated on ALPHA_CUTOUT, a material test, not a block-id list — a blocks.toml category list
    // here would be IPBR by the back door. Wetness darkening itself stays untouched.
    puddleWetness = 0.0;
#endif
    // A missing `_n` binds to identity height 1.0, so treating that literal as a hilltop biases every
    // vanilla block dry. spriteHeightRange reports zero span when there's no real relief, so it's the
    // unambiguous presence test instead.
    vec4 puddleHeightRange = fornax_spriteGridCell(u_GeomInput1, v_TexCoord);
    float puddleHeightSpan = max(puddleHeightRange.y - puddleHeightRange.x,
                                 puddleHeightRange.w - puddleHeightRange.z);
    bool puddleHasRelief = puddleHeightSpan > (0.5 / 255.0);
    float puddleHeight = puddleHasRelief ? normalSample.a : 0.5;
    float puddleNoise = plaguePuddleAmount(
            u_GeomInput2,
            v_CameraAbs.xz + v_WorldPos.xz, // absolute, or the puddles walk with the player
            puddleHeight,
            faceNormal.y, v_SkyLight, puddleWetness);
    // Film enters as puddle COVERAGE so it flattens the normal and glosses the surface through the
    // same three offset windows a rain puddle uses, remapped off its own 0..1 depth first.
    puddleNoise = max(puddleNoise, shoreSpill.x > 0.0
            ? mix(PLAGUE_SHORE_FILM_COVERAGE_MIN, PLAGUE_SHORE_FILM_COVERAGE_MAX, shoreSpill.x)
            : 0.0);
    float puddleAlbedoWet = plagueApplyPuddle(puddleNoise, worldNormal, faceNormal,
            puddleSmoothness, puddleF0, puddleMat.conductor);
    // Soak is already a 0..1 darkening weight, so it maxes straight against the puddle's own.
    puddleAlbedoWet = max(puddleAlbedoWet, shoreSpill.y);
#if PLAGUE_PUDDLE_RIPPLE_PCT > 0
    // After the flattening above, never before — applying it first would add noise to the brick underneath.
    // v_RainLevel is world-global (a storm darkens the whole sky); v_RainsHere makes it local to this block's biome.
    float localRain = v_RainLevel * v_RainsHere;
    float puddleImpactGate = smoothstep(0.55, 0.62, puddleNoise)
            * (float(PLAGUE_PUDDLE_RIPPLE_PCT) / 100.0);
    vec2 puddleImpactGradient = plaguePuddleImpactGradient(
            u_GeomInput2, v_CameraAbs.xz + v_WorldPos.xz, v_WaveClock, localRain, u_SplashDensity);
    worldNormal = normalize(worldNormal
            + vec3(-puddleImpactGradient.x, 0.0, -puddleImpactGradient.y) * puddleImpactGate);
#endif
    // Soaked fringe, darkened by porosity. Gated on u_PomDebug: this repaints rawAlbedo, which the
    // debug views also write into — see the same gate on snow dusting below.
    //
    // rawAlbedo is display-space sRGB here; plagueFauxPorosity is a linear-space model, so decode
    // in and re-encode out, same as the RawTint multiply above.
    if (u_PomDebug < 0.5) {
        vec3 puddleAlbedoLinear = plagueSrgbToLinear(rawAlbedo);
        puddleAlbedoLinear = plagueFauxPorosity(puddleAlbedoLinear, puddleAlbedoWet, puddleMat.porosity);
        rawAlbedo = plagueLinearToSrgb(puddleAlbedoLinear);
    }
#else
    // Off: no placement/ripples/splashes; every sky-facing surface gets uniformly wet via the same
    // plagueSurfaceWetness/plagueApplyWetness pair the forward arm below uses. Deliberately ungated
    // by ALPHA_CUTOUT — those gates stop placement, not uniform wetness, and the forward arm mirrors that.
    float puddleWetness = clamp(
            max(plagueSurfaceWetness(v_Wetness, v_SkyLight, worldNormal.y)
                        * (float(PLAGUE_WETNESS_PCT) / 100.0),
                max(shoreSpill.x, shoreSpill.y)),
            0.0, 1.0);
    vec3 puddleAlbedoLinear = plagueSrgbToLinear(rawAlbedo);
    plagueApplyWetness(puddleMat, puddleAlbedoLinear, puddleWetness);
    if (u_PomDebug < 0.5) {
        rawAlbedo = plagueLinearToSrgb(puddleAlbedoLinear);
    }
    // plagueApplyWetness mutates GGX alpha, the inverse of plagueDecodeMaterial's forward mapping
    // (brdf.glsl). Floored against the authored byte: the decode's alpha floor caps the round-trip
    // below what a bone-dry high-smoothness surface authored, and water only ever raises smoothness.
    puddleSmoothness = max(materialSample.r, 1.0 - sqrt(max(puddleMat.alpha, 0.0)));
    puddleF0 = puddleMat.f0;
#endif
    materialSample.r = puddleSmoothness;
    materialSample.g = puddleF0;
#endif

    // --- Static snow dusting -------------------------------------------------------------------
    // After puddles; mutually exclusive by construction (v_RainsHere = 0 wherever v_SnowsHere = 1),
    // ordered this way so snow would sit on top if that gate is ever loosened. Placement lives in
    // snow.glsl; the outer condition also names the foliage switch so it removes the whole block.
#if PLAGUE_SNOW_DUSTING && (PLAGUE_SNOW_ON_FOLIAGE || !defined(ALPHA_CUTOUT))
    // NOT decoration: the POM debug views write into rawAlbedo above, and snow repaints it too, so
    // without this gate every debug view in a snowy biome reads as white pillows. Any future term
    // that repaints rawAlbedo needs the same gate.
    if (v_SnowsHere > 0.5 && u_PomDebug < 0.5) {
        // dPosX/dPosY are taken at the top of main, before cutout discard — derivatives across a
        // quad with discarded lanes aren't reliable, and these were needed for the tangent frame anyway.
        float snowBias = (u_SnowAmount - 1.0) * PLAGUE_SNOW_BIAS_SPAN;
        // Absolute, never camera-relative — a dusting that slides with the player reads as a screen-space effect.
        vec3 snowWorldPos = v_CameraAbs + v_WorldPos;

#ifdef ALPHA_CUTOUT
        float snowCover = plagueSnowFoliageCoverage(u_GeomInput2, snowWorldPos, faceNormal.y,
                v_SkyLight, snowBias, dPosX, dPosY);
        plagueApplySnow(snowCover, PLAGUE_SNOW_AO_LIFT_FOLIAGE, PLAGUE_SNOW_FLATTEN_FOLIAGE,
                rawAlbedo, worldNormal, faceNormal, materialSample.r, bakedAo, pomShadow);
#else
        // The labPBR height at the coordinate parallax actually landed on, range-remapped exactly as
        // the puddle placement reads it: snow settles into the same grooves water pools in.
        float snowCover = plagueSnowGroundCoverage(u_GeomInput2, snowWorldPos.xz, faceNormal.y,
                v_SkyLight, normalSample.a, snowBias, dPosX, dPosY);
        plagueApplySnow(snowCover, PLAGUE_SNOW_AO_LIFT_GROUND, PLAGUE_SNOW_FLATTEN_GROUND,
                rawAlbedo, worldNormal, faceNormal, materialSample.r, bakedAo, pomShadow);
#endif
    }
#endif

    gNormalOut   = vec4(worldNormal, 1.0);
    // Decode audit instrument, NOT a shading change (rawAlbedo/materialSample/bakedAo above are
    // computed identically either way). Gated on u_AlbedoIdentityDebug, not the engine's debugView
    // uniform, which a DEFERRED program never receives. Overrides gAlbedoOut last, after snow and
    // puddles, so it can't be silently painted over. Values are RAW (undecoded, no tint multiply) —
    // gbuffer_resolve.fsh's DBG_ALBEDO_IDENTITY_INPUTS branch reads them back the same way.
    if (u_AlbedoIdentityDebug > 0.5) {
        float texLuma = dot(albedo.rgb, vec3(0.2126, 0.7152, 0.0722));
        gAlbedoOut = vec4(texLuma, v_RawTint.r, v_RawTint.g, v_RawTint.b);
    } else {
        gAlbedoOut = vec4(rawAlbedo, v_SkyLight);
    }
    // Full 8-bit precision, not a 16-step nibble: quantising a per-vertex-interpolated gradient
    // banded visibly along each quad's diagonal triangle seam.
    gMaterialOut = vec4(materialSample.r, materialSample.g, materialSample.b, v_BlockLight);
    // gMaterial: r=smoothness, g=F0, b=porosity/SSS (labPBR _s, wetness baked in), a=block light.
    // gAo: r=AO, g=emission, b=self-shadow — kept separate because the resolve applies each
    // differently (AO attenuates ambient, self-shadow occludes only direct sun).
    //
    // .g is normalised 0..1 and rescaled >1.0 on read in gbuffer_resolve (gAo is RGBA8_UNORM, so
    // this lane can't hold the >1 value directly; both source factors are already 8-bit-limited).
    //
    // The lane split above is load-bearing, not tidiness: self-shadow briefly shared .g with
    // emission and silently deleted every emissive surface's glow.
    // gAo.a: surface class, the one fact the deferred chain can't otherwise recover.
    //   1.0 terrain solid   0.75 entity   0.5 terrain cutout   0.25 particle   0.0 block entity
    // Quarter-step spaced (0.125 headroom against a 1/255 quantum); all five slots are assigned,
    // another class needs a new encoding.
    //
    // #ifdef ALPHA_CUTOUT is exact here, not a heuristic: verified against Sodium's
    // ShaderChunkRenderer.createShader — under USE_DEFERRED "defined" means exactly the cutout sub-draw.
    //
    // Mirrored in entities.fsh, block_entities.fsh and particles.fsh; the four writes must not drift
    // apart. Read by shaders/include/outline.glsl, which skips the outline on the cutout class (every
    // leaf gap is a real depth discontinuity) and on particles. Its only consumer, and compiled out
    // when World Outline is off, so a wrong value here fails silently.
#ifdef ALPHA_CUTOUT
    gAoOut       = vec4(bakedAo, emission, pomShadow, 0.5);
#else
    gAoOut       = vec4(bakedAo, emission, pomShadow, 1.0);
#endif
    gMotionOut   = v_MotionVector;
// Must mirror the output declaration's three-way chain: testing only USE_DEFERRED would compile the
// forward arm under USE_WATER_PREPASS too, where fragColor doesn't exist (an early return doesn't excuse it from compiling).
#elif !defined(USE_WATER_PREPASS)
    // Forward TRANSLUCENT arm. Water draws here by default (texture * tint * lightmap over the
    // tonemapped frame) unless the deferred chain owns it, in which case this must NOT also draw it.
    // The gate below must match the graph's condition for water_composite exactly, or both arms
    // draw water or neither does. That is SSR_WATER_MODE alone, the same gate the engine puts its
    // water pre-pass behind: SSR_QUALITY is the opaque reflection option and does not own water.
#if SSR_WATER_MODE > 0
    if (isWater) {
        discard;
    }
#endif
#if PLAGUE_UNDERWATER
    // This draw happens after the deferred water composite, so a wet eye must not let dry
    // translucent terrain on the far side of the water interface composite over the closed volume.
    // Small surface tolerance prevents flicker as camera bob moves the reconstructed altitude.
    if (u_WaterState.x > 0.5
            && v_WorldPos.y + v_CameraAbs.y > u_WaterState.z + 0.05) {
        discard;
    }
#endif
    // Preserve the exact forward baseline first. Sodium blends this output with straight alpha;
    // neither LabPBR nor the fog below is allowed to alter that ownership contract.
    vec4 forwardBase = albedo * v_Color;
    fragColor = forwardBase;

    // Engine-bound identity texels where a sprite has no sidecar. Not treated as presence metadata
    // (an authored texel with the same values states the same response) — only used to preserve the old path exactly.
    const vec4 FORWARD_NORMAL_FALLBACK = vec4(128.0 / 255.0, 128.0 / 255.0, 1.0, 1.0);
    const vec4 FORWARD_MATERIAL_FALLBACK = vec4(0.0, 0.0, 0.0, 1.0);
    const float FORWARD_SIDECAR_EPSILON = 0.5 / 255.0;

    vec4 forwardNormalSample = plaguePagedNormalGrad(uv, ddx, ddy);
    // Whole-level selection is required for `_s`: green contains categorical metal codes and blue
    // is split between porosity and SSS. Inter-level filtering would invent a third material.
    vec4 forwardMaterialSample = plaguePagedMaterialLod(uv, ddx, ddy);

    bool forwardNormalSignal = any(greaterThan(
            abs(forwardNormalSample - FORWARD_NORMAL_FALLBACK),
            vec4(FORWARD_SIDECAR_EPSILON)));
    bool forwardMaterialSignal = any(greaterThan(
            abs(forwardMaterialSample - FORWARD_MATERIAL_FALLBACK),
            vec4(FORWARD_SIDECAR_EPSILON)));
    bool forwardHasLabPbrSignal = forwardNormalSignal || forwardMaterialSignal;

    // Water keeps its existing dedicated forward/deferred treatments. Applying terrain material
    // response here when SSR water is disabled would silently make water depend on `_n`/`_s`.
    // Hoisted: the refraction block runs after fragColor is composited, so it cannot sit inside
    // these branches. Identity values when nothing is authored.
    vec3 forwardWorldNormal = faceNormal;
    PlagueMaterial forwardMaterial = plagueDecodeMaterial(0.0, 0.0, 0.0);

    if (!isWater && forwardHasLabPbrSignal) {
        float forwardBakedAo = 1.0;

        if (forwardNormalSignal) {
            // Same labPBR tangent-normal decode as the deferred arm. `_n.b` is AO; Z is
            // reconstructed from RG and must never be read from blue.
            vec3 forwardNtex = forwardNormalSample.rgb;
            vec2 forwardTangentXY;
            if (all(lessThan(forwardNtex, vec3(0.003)))) {
                forwardTangentXY = vec2(0.0);
            } else {
                forwardTangentXY = forwardNtex.xy * PLAGUE_NORMAL_XY_SCALE + PLAGUE_NORMAL_XY_BIAS;
                forwardTangentXY *= clamp(u_BumpStrength, 0.0, 2.0);
            }
            float forwardTangentZ = sqrt(clamp(
                    1.0 - dot(forwardTangentXY, forwardTangentXY), 0.0, 1.0));
            forwardWorldNormal = normalize(tangent * forwardTangentXY.x
                    + bitangent * forwardTangentXY.y + faceNormal * forwardTangentZ);
            forwardBakedAo = mix(1.0, forwardNormalSample.b, u_AOStrength);
        }

        vec3 forwardLightDir = dot(v_SunDirection, v_SunDirection) > 1e-6
                ? normalize(v_SunDirection) : vec3(0.0, 1.0, 0.0);
        vec3 forwardViewDir = length(v_WorldPos) > 1e-6
                ? normalize(-v_WorldPos) : faceNormal;

        // Same time/weather colour tables as the resolve. The normal map enters as a RELATIVE
        // directional response since baseline already owns vanilla's lightmap.
        vec3 forwardTrueSun = dot(u_SkyCelestial.xyz, u_SkyCelestial.xyz) > 1e-6
                ? normalize(u_SkyCelestial.xyz) : vec3(0.0, 1.0, 0.0);
        float forwardRain = clamp(u_SkyState.x, 0.0, 1.0);
        PlagueLighting forwardLighting = plagueOverworldLighting(
                max(u_SkyColor.rgb, vec3(0.0)), forwardTrueSun.y, u_SkyState.y,
                forwardRain, u_ScreenBrightness);

        float forwardSkyAccess = clamp(v_SkyLight, 0.0, 1.0);
        forwardSkyAccess *= forwardSkyAccess * (3.0 - 2.0 * forwardSkyAccess);
        vec3 forwardAmbient = max(forwardLighting.ambient, vec3(0.0));
        vec3 forwardDirect = max(forwardLighting.light, vec3(0.0))
                * forwardSkyAccess;
        vec3 forwardFlatIncident = forwardAmbient
                + forwardDirect * max(dot(faceNormal, forwardLightDir), 0.0);
        // AO belongs to the indirect hemisphere. The direct lobe remains controlled by its normal
        // and sky access instead of being multiplied by `_n.b` a second time.
        vec3 forwardMappedIncident = forwardAmbient * forwardBakedAo
                + forwardDirect * max(dot(forwardWorldNormal, forwardLightDir), 0.0);

        // Lands after the fullscreen tonemap: recover the scene estimate, keep its inverse residual,
        // do material maths in scene-linear space, then run the shared display transform once.
        vec3 forwardScene = plagueUntonemapApprox(forwardBase.rgb);
        vec3 forwardResidual = forwardBase.rgb - plagueTonemapAndGrade(forwardScene);
        if (forwardNormalSignal) {
            forwardScene *= forwardMappedIncident / max(forwardFlatIncident, vec3(1e-4));
        }

        if (forwardMaterialSignal) {
            forwardMaterial = plagueDecodeMaterial(
                    forwardMaterialSample.r, forwardMaterialSample.g,
                    forwardMaterialSample.b);

            // Porosity is meaningful only while wet. Apply its authored darkening as a ratio so the
            // already-established forward lightmap/tint baseline remains the source of illumination.
            //
            // Same tint/shade split as the deferred arm's rawAlbedo: v_RawTint.rgb (tint) is
            // decoded, v_RawTint.a (shade*AO, already linear) is not. No re-encode here — this
            // feeds shader-linear math directly, never an 8-bit target.
            vec3 forwardAuthoredAlbedo = clamp(
                    plagueSrgbToLinear(albedo.rgb) * plagueSrgbToLinear(v_RawTint.rgb) * v_RawTint.a,
                    0.0, 1.0);
            vec3 forwardWetAlbedo = forwardAuthoredAlbedo;
#if PLAGUE_WETNESS_PCT > 0
            float forwardWetness = plagueSurfaceWetness(
                    v_Wetness, v_SkyLight, forwardWorldNormal.y)
                    * (float(PLAGUE_WETNESS_PCT) / 100.0);
            forwardWetness = clamp(forwardWetness, 0.0, 1.0);
            plagueApplyWetness(forwardMaterial, forwardWetAlbedo, forwardWetness);
            forwardScene *= forwardWetAlbedo / max(forwardAuthoredAlbedo, vec3(1e-4));
#endif

            // One LabPBR response for every material: decoded F0/metalness sets energy, authored
            // smoothness sets the GGX lobe, and the existing ambient table supplies the unresolved
            // wide environment. No SSR result or water tuning is mixed into this forward consumer.
            float forwardNdotV = max(dot(forwardWorldNormal, forwardViewDir), 1e-4);
            float forwardPerceptualRoughness = sqrt(max(forwardMaterial.alpha, 0.0));
            vec2 forwardEnvBrdf = plagueEnvBrdfApprox(
                    forwardNdotV, forwardPerceptualRoughness);
            vec3 forwardSpecularAlbedo = plagueMaterialF0(
                    forwardMaterial, forwardWetAlbedo) * forwardEnvBrdf.x
                    + forwardEnvBrdf.y;
            vec3 forwardDiffuseShare = (vec3(1.0) - forwardSpecularAlbedo)
                    * (1.0 - forwardMaterial.metalness);
            forwardScene *= max(forwardDiffuseShare, vec3(0.0));

            PlagueBrdf forwardBrdf = plagueEvaluateBrdf(
                    forwardMaterial, forwardWetAlbedo, forwardWorldNormal,
                    forwardViewDir, forwardLightDir);
            vec3 forwardRadiance = forwardBrdf.specular * forwardDirect;
            // The unresolved environment is available only to the degree this fragment sees sky;
            // without that gate a pane in a cave receives outdoor fill from no source.
            forwardRadiance += forwardAmbient * forwardSpecularAlbedo
                    * forwardBakedAo * forwardSkyAccess;

            // labPBR blue 65..255 is thin-surface transmission. It is separate from porosity in
            // plagueDecodeMaterial, so no texel can accidentally receive both interpretations.
            float forwardBacklight = max(dot(-forwardWorldNormal, forwardLightDir), 0.0);
            forwardRadiance += forwardWetAlbedo * forwardDirect * forwardBacklight
                    * forwardMaterial.subsurface;

            // Alpha 255 is the atlas-level "no authored emission" sentinel. Any other value is the
            // pack's own emission magnitude and uses the same radiance curve as deferred terrain.
            bool forwardEmissionUnauthored =
                    forwardMaterialSample.a >= (254.5 / 255.0);
            float forwardEmission = forwardEmissionUnauthored
                    ? 0.0 : forwardMaterialSample.a * u_AuthoredEmission;
            forwardRadiance += plagueEmittedRadiance(
                    forwardWetAlbedo, forwardEmission);
            forwardScene += forwardRadiance;
        }

        fragColor.rgb = clamp(plagueTonemapAndGrade(max(forwardScene, vec3(0.0)))
                + forwardResidual, 0.0, 1.0);
    }

    // --- Refraction on translucent terrain ------------------------------------------------------
    // Bends the background by the pane's own `_s` green channel: F0 gives an IOR, an IOR gives the
    // bend. Reads sceneHdrComposited, never the framebuffer this blends into (read-write hazard).
#if PLAGUE_GLASS_REFRACTION
    {
        // The gain below is (1-a)/a, already 19x here. Lower alpha amplifies noise, not refraction.
        const float PLAGUE_REFRACT_MIN_ALPHA = 0.05;

        // Green 0 is unauthored, not ior 1.0: the format's table starts at 5. Taken literally, a
        // pack that paints no `_s` refracts nothing. Falls back to the table's glass entry.
        const float PLAGUE_REFRACT_F0_UNAUTHORED = 0.5 / 255.0;
        const float PLAGUE_REFRACT_GLASS_F0 = 9.0 / 255.0;
        float forwardF0 = forwardMaterial.f0 < PLAGUE_REFRACT_F0_UNAUTHORED
                ? PLAGUE_REFRACT_GLASS_F0
                : forwardMaterial.f0;

        // Inverts F0 = ((n-1)/(n+1))^2, as plagueFresnelDielectric does, so the two agree.
        float forwardSqrtF0 = min(sqrt(max(forwardF0, 0.0)), 0.99999);
        float forwardIor = (1.0 + forwardSqrtF0) / (1.0 - forwardSqrtF0);
        // Lateral shift through a thin slab scales with (1 - 1/ior).
        float forwardBend = 1.0 - 1.0 / max(forwardIor, 1.0);

        vec3 forwardDeviation = forwardWorldNormal - faceNormal;

        if (!forwardMaterial.conductor
                && forwardBend > 1e-4
                && u_RefractStrength > 0.0
                && forwardBase.a >= PLAGUE_REFRACT_MIN_ALPHA
                && dot(forwardDeviation, forwardDeviation) > 1e-12) {
            // mat3() drops translation: v_WorldPos is already camera-relative.
            vec3 forwardViewDeviation = mat3(u_ModelViewMatrix) * forwardDeviation;

            // Divide by distance, apply the projection's xy scales, halve for NDC to UV.
            // sceneHdrComposited is scale = 1.0, so its own size is the render size.
            float forwardViewDepth = max(length(v_WorldPos), 0.05);
            vec2 forwardProjScale = vec2(u_ProjectionMatrix[0][0], u_ProjectionMatrix[1][1]);
            vec2 forwardOffset = 0.5 * forwardProjScale * forwardViewDeviation.xy
                    * (forwardBend * u_RefractStrength / forwardViewDepth);

            vec2 forwardScreenTexel = 1.0 / vec2(textureSize(u_GeomInput4, 0));
            vec2 forwardBaseUv = gl_FragCoord.xy * forwardScreenTexel;
            vec2 forwardRefractUv = clamp(forwardBaseUv + forwardOffset, vec2(0.0), vec2(1.0));

            // Drop a sample that landed in front of the pane. Reversed-Z: nearer reads greater.
            float forwardFragDepth = gl_FragCoord.z;
            float refractedDepth = texture(u_GeomInput5, forwardRefractUv).r;
            if (refractedDepth > forwardFragDepth) {
                forwardRefractUv = forwardBaseUv;
            }

            // Same display transform on both, so their difference is meaningful.
            vec3 forwardBgRefracted = plagueTonemapAndGrade(
                    max(texture(u_GeomInput4, forwardRefractUv).rgb, vec3(0.0)));
            vec3 forwardBgDirect = plagueTonemapAndGrade(
                    max(texture(u_GeomInput4, forwardBaseUv).rgb, vec3(0.0)));

            // Sodium blends src*a + dst*(1-a) with dst unrefracted. Emitting the background
            // difference scaled by (1-a)/a lands on glass*a + refracted*(1-a).
            float forwardGain = (1.0 - forwardBase.a)
                    / max(forwardBase.a, PLAGUE_REFRACT_MIN_ALPHA);
            fragColor.rgb = clamp(
                    fragColor.rgb + (forwardBgRefracted - forwardBgDirect) * forwardGain,
                    0.0, 1.0);
        }
    }
#endif

    fragColor.a = forwardBase.a;

    // --- Fog on translucent terrain -------------------------------------------------------------
    // Runs in display space, not linear like the rest of this pack: this draw happens after
    // tonemap.fsh, so the deferred G-buffer path never reaches it. Blends the linear fog colour
    // over the display surface via plagueCompositeLinearOverDisplay (same treatment as
    // banner_patterns.fsh). The water discard above must stay above this block — a water fragment
    // must leave before paying fog twice (once here, once in water_composite.fsh).
#if PLAGUE_FOG
    // Full-ray fog (no cap on the in-water leg) keeps the render-distance edge from showing through
    // water. Ungated on u_WaterState: plagueFogTerms carries the eye-in-water arm itself, so a
    // submerged pane takes the veil with no extra plumbing here.
    {
        // The same colour tables the resolve, the water composite, the banner slot and the cloud
        // march build, from the same uniforms, so this pane's fog and the fog on the terrain behind
        // it cannot disagree about the time of day.
        float rainFactorFog = clamp(u_SkyState.x, 0.0, 1.0);

        // TRUE sun, never the active light: the moon sits where the sun sits at noon, so using the
        // active light's elevation would build the colour tables as noon at midnight.
        vec3 fogSunDir = dot(u_SkyCelestial.xyz, u_SkyCelestial.xyz) > 1e-6
                ? normalize(u_SkyCelestial.xyz) : vec3(0.0, 1.0, 0.0);
        // Fullscreen sites pass u_SunDirection.w (unavailable to a geometry pass); u_SkyCelestial.y
        // is exactly the same quantity (cos(sunAngle)) by construction, not an approximation.
        PlagueLighting fogLighting = plagueOverworldLighting(
                max(u_SkyColor.rgb, vec3(0.0)), fogSunDir.y, u_SkyState.y,
                rainFactorFog, u_ScreenBrightness);
        PlagueSkyColors fogSky = plagueSkyColors(max(u_SkyColor.rgb, vec3(0.0)),
                fogSunDir, fogLighting.sunVisibility, rainFactorFog, u_CameraAbs.y);

        // Same anchor the resolve uses (u_CameraSkyLight.z, the render distance) — a different one
        // would put this pane's veil at a different distance than the wall behind it, a visible seam.
        float renderDistance = u_CameraSkyLight.z > 1.0 ? u_CameraSkyLight.z : max(u_RenderFog.y, 32.0);

        // The same interleaved-gradient noise the sky and the resolve dither with, so the fog and the
        // sky it converges to break their banding identically rather than crossing patterns.
        float fogDither = fract(52.9829189
                * fract(0.06711056 * gl_FragCoord.x + 0.00583715 * gl_FragCoord.y));

        // Underwater-only pack-ambient relight: this arm's surface is vanilla's own lightmap, the
        // only one the pack never relights, and the underwater fog floor rises with distance, so a
        // near pane would sit visibly darker than the background behind it without this. Applies the
        // resolve's own live ambient via max() (never dims vanilla's lighting), gated on the
        // submerged eye so the dry path stays bit-identical.
        if (u_WaterState.x > 0.5) {
            vec3 uwZen = plagueGetSky(fogSky, 1.0, clamp(fogSunDir.y, -1.0, 1.0), 0.5,
                                      false, false);
            float uwZenLuma = dot(uwZen, vec3(0.2126, 0.7152, 0.0722));
            float uwTableLuma = dot(fogLighting.ambient, vec3(0.2126, 0.7152, 0.0722));
            float uwAmbScale = mix(uwTableLuma / max(uwZenLuma, 1e-5), 1.29,
                                   fogLighting.sunFactor);
            // The resolve's ambientMult gate: sky access, smoothstepped. A pane in a sealed
            // hull stays dark.
            float uwYm = v_SkyLight * v_SkyLight * (3.0 - 2.0 * v_SkyLight);
            vec3 uwPackAmbient = uwZen * uwAmbScale * uwYm;
            // The RAW albedo sample, not fragColor: fragColor already carries vanilla's dark
            // lightmap, and relighting that would double-count the very darkness being fixed.
            vec3 uwRelit = plagueTonemapAndGrade(
                    plagueSrgbToLinear(clamp(albedo.rgb, 0.0, 1.0)) * uwPackAmbient);
            fragColor.rgb = max(fragColor.rgb, uwRelit);
        }

        PlagueFogTerms fogTerms = plagueFogTerms(v_WorldPos, v_SkyLight, u_CameraSkyLight.x,
                                                 renderDistance,
                                                 v_CameraAbs.y, fogDither, fogSky, fogLighting,
                                                 fogSunDir, u_FogDensity, u_FogBorderDensity,
                                                 u_DepthDarkness);
        // Per-channel vec3, not scalar: underwater tint differs by wavelength (red dies first);
        // above water every channel agrees exactly, so this costs nothing there.
        vec3 fogOpacity = plagueFogOpacity(fogTerms);

        // Near the camera the fog is nothing at all and the un-premultiply below would divide a zero
        // by a zero. Skipping is both cheaper and better conditioned than clamping the divisor.
        if (max(max(fogOpacity.r, fogOpacity.g), fogOpacity.b) > 1e-3) {
            vec3 fogLinear = plaguePremultipliedFog(fogTerms) / max(fogOpacity, vec3(1e-3));
            fragColor.rgb = plagueCompositeLinearOverDisplay(fragColor.rgb, fogLinear, fogOpacity);
        }
    }
#endif

    // Alpha deliberately untouched (drives Sodium's SRC_ALPHA blend): fogging it toward 0 would leak
    // the already-fogged background through in proportion, since that background has already
    // converged toward sky colour on its own.
#endif
}
