#ifndef PLAGUE_CLOUD_TYPES
#define PLAGUE_CLOUD_TYPES

// The seven cloud genera as a table, generated by tools/derive_cloud_types.py from the WMO
// International Cloud Atlas and standard water-path/effective-radius tables via
// tau = 3 WP / (2 rho r_eff). Do not hand-edit the pasted block below; re-run the script instead.
//
// All seven rows exist now so the mid and high decks are table lookups when they land; only the
// low deck is resolved today, moving cumulus through cumulus congestus to cumulonimbus with rain
// and thunder. `family` (below the table) is authored, not derived.

// --- Options ----------------------------------------------------------------------------------
//
// Import only from a fullscreen pass, via clouds.glsl: these two options reach the shader through
// u_PackOptions, which a deferred geometry program never receives.

// Offset from the game's own cloud altitude (see plagueCloudEngineBase), not an absolute world Y,
// so a mod that moves vanilla's cloud layer is respected rather than overridden. Default 192.0
// equals PLAGUE_CLOUD_CUMULUS_BASE, so the offset is zero on an unmodded install. Applied as a
// shift (plagueCloudLowDeckShift) rather than an assignment, to keep the low etage's genera at
// their relative altitudes once more than cumulus is resolved.
#define u_CloudAltitude 192.0 //[96.0..384.0 step 4.0] runtime "Cloud Altitude"

// Candidate population. Stable owner ranks are compared with this response, so increasing Amount
// reveals additional owner-local domes without moving or dilating an already-active cloud.
#define u_CloudAmount 1.0 //[0.00..2.00 step 0.05] runtime "Cloud Amount"

// Relative physical size around the accepted reference; the one slider that departs from the
// genus-table scale on purpose. The accepted 0.30 setting keeps the table's 400 m cumulus depth
// while smaller/larger values shrink/grow around that reference rather than applying 0.30 twice.
//
// Raises/lowers the density isosurface inside each fixed candidate organisation and scales physical
// depth in Y. The base/detail coordinates and local/broad blend stay fixed, so Size reveals more
// irregular 3-D density rather than dilating an analytic support or stretching individual pieces.
// It never changes a world-coordinate divisor: doing that rephases every cloud around world origin.
//
// `tau` (optical depth) is deliberately not scaled with it: geometric similarity would fade the
// deck out as it shrinks, which is a second, unwanted departure from physics bundled into this one
// slider. The slab's opacity is held at the row's own figure regardless of size.
//
// Floor of 0.20 is set by clouds.glsl's traversal step cap, not by cloud/erosion size ratio.
#define u_CloudScale 0.30 //[0.20..2.00 step 0.05] runtime "Cloud Size"

// Strength of the rain -> congestus interpolation in plagueCloudLowDeck. 0 holds the deck at
// cumulus regardless of weather, for bisecting the weather response against a static sky.
#define u_CloudWeatherResponse 1.0 //[0.00..1.00 step 0.05] runtime "Weather Response"

// --- One resolved deck --------------------------------------------------------------------------

/**
 * One genus, resolved for this instant. Six fields are table rows; `family` is authored (see
 * below). `population` is the stable-rank activation threshold; `cover` is aggregate reporting for
 * lighting only; `cut` is the fixed per-candidate interior threshold. `sizeRatio` is whole-cloud
 * physical scale without changing the world-anchored lobe coordinates.
 */
struct PlagueCloudDeck {
    float base;        // absolute world Y of the slab's underside, blocks
    float depth;        // slab thickness, blocks
    float cell;        // horizontal size of one lump, blocks
    float shear;        // along-wind stretch, dimensionless; 1.0 is isotropic
    float tau;         // optical depth straight down through the whole slab, dimensionless
    float cover;        // fraction of the whole plane the deck occupies, 0..1
    float population;   // owner-rank activation threshold, 0..1
    float family;       // height-profile selector: 0 flat sheet, 1 deep tower, 2 spreading-top tower
    float cut;          // fixed per-candidate base-field threshold
    float sizeRatio;    // whole-cloud physical scale around the accepted reference
    float footprint;    // weather morphology's horizontal growth; independent of Cloud Size
    float sheetFloor;   // stratiform baseline potential away from any candidate; far negative = none
};

// Baseline potential a stratiform deck carries everywhere, not just inside a candidate. Places the
// mid-column cutoff at 0.30, about 2.3 sigma below the field's 0.51463 mean, so the layer is
// continuous as its 8-okta genus row says while the base volume still sets its thickness. The
// vertical penalty subtracts 0.52 at the slab's own top and base, taking it past the -0.329
// early-out, so the sheet closes itself rather than ending on a flat lid.
const float PLAGUE_CLOUD_SHEET_FLOOR = 0.15;

// A convective deck has no sheet: this is far below the early-out, so every position away from a
// candidate stays empty and the candidate-only field is reproduced exactly.
const float PLAGUE_CLOUD_SHEET_NONE = -1e6;

// The band over which the sky changes genus. Wide and centred on the ramp so the dissolve spends
// most of vanilla's weather transition in progress rather than resolving in a few frames, which is
// what a threshold did and what read as a pop.
const float PLAGUE_CLOUD_STRATIFORM_ONSET = 0.20;
const float PLAGUE_CLOUD_STRATIFORM_FULL  = 0.80;

// Traversal cap, blocks, horizontal. tools/derive_cloud_types.py checks its genus cell sizes
// against this so no cell fills the whole drawn region; the march's own visual horizon (from
// atmosphere.glsl's planet radius) is larger, so this bound is conservative, not wrong.
const float PLAGUE_CLOUD_DISTANCE = 4000.0;

// --- paste from tools/derive_cloud_types.py -----------------------------------------------------

// Cirrus, high deck, ice
const float PLAGUE_CLOUD_CIRRUS_BASE        =   1728.00;   // 9000 m
const float PLAGUE_CLOUD_CIRRUS_DEPTH       =    288.00;   // 1500 m
const float PLAGUE_CLOUD_CIRRUS_CELL        =    384.00;   // 2000 m
const float PLAGUE_CLOUD_CIRRUS_TAU         =    0.5000;
const float PLAGUE_CLOUD_CIRRUS_SHEAR       =    6.0000;
const float PLAGUE_CLOUD_CIRRUS_COVER       =    0.2500;   // 2 oktas

// Cirrocumulus, high deck, ice
const float PLAGUE_CLOUD_CIRROCUMULUS_BASE  =   1344.00;   // 7000 m
const float PLAGUE_CLOUD_CIRROCUMULUS_DEPTH =     76.80;   // 400 m
const float PLAGUE_CLOUD_CIRROCUMULUS_CELL  =     17.06;   // 89 m
const float PLAGUE_CLOUD_CIRROCUMULUS_TAU   =    1.8000;
const float PLAGUE_CLOUD_CIRROCUMULUS_SHEAR =    1.2000;
const float PLAGUE_CLOUD_CIRROCUMULUS_COVER =    0.3750;   // 3 oktas

// Altocumulus, mid deck, water
const float PLAGUE_CLOUD_ALTOCUMULUS_BASE   =    768.00;   // 4000 m
const float PLAGUE_CLOUD_ALTOCUMULUS_DEPTH  =    115.20;   // 600 m
const float PLAGUE_CLOUD_ALTOCUMULUS_CELL   =     61.15;   // 318 m
const float PLAGUE_CLOUD_ALTOCUMULUS_TAU    =    7.5000;
const float PLAGUE_CLOUD_ALTOCUMULUS_SHEAR  =    2.0000;
const float PLAGUE_CLOUD_ALTOCUMULUS_COVER  =    0.5000;   // 4 oktas

// Cumulus, low deck, water
const float PLAGUE_CLOUD_CUMULUS_BASE       =    192.00;   // 1000 m
const float PLAGUE_CLOUD_CUMULUS_DEPTH      =     76.80;   // 400 m
const float PLAGUE_CLOUD_CUMULUS_CELL       =    192.00;   // 1000 m
const float PLAGUE_CLOUD_CUMULUS_TAU        =    9.0000;
const float PLAGUE_CLOUD_CUMULUS_SHEAR      =    1.1000;
const float PLAGUE_CLOUD_CUMULUS_COVER      =    0.3750;   // 3 oktas

// Stratocumulus, low deck, water
const float PLAGUE_CLOUD_STRATOCUMULUS_BASE =    153.60;   // 800 m
const float PLAGUE_CLOUD_STRATOCUMULUS_DEPTH=    115.20;   // 600 m
const float PLAGUE_CLOUD_STRATOCUMULUS_CELL =    384.00;   // 2000 m
const float PLAGUE_CLOUD_STRATOCUMULUS_TAU  =   22.5000;
const float PLAGUE_CLOUD_STRATOCUMULUS_SHEAR=    2.5000;
const float PLAGUE_CLOUD_STRATOCUMULUS_COVER=    0.7500;   // 6 oktas

// Stratus, low deck, water
const float PLAGUE_CLOUD_STRATUS_BASE       =     57.60;   // 300 m
const float PLAGUE_CLOUD_STRATUS_DEPTH      =     76.80;   // 400 m
const float PLAGUE_CLOUD_STRATUS_CELL       =    960.00;   // 5000 m
const float PLAGUE_CLOUD_STRATUS_TAU        =   18.7500;
const float PLAGUE_CLOUD_STRATUS_SHEAR      =    1.0000;
const float PLAGUE_CLOUD_STRATUS_COVER      =    1.0000;   // 8 oktas

// Nimbostratus, low deck, water
const float PLAGUE_CLOUD_NIMBOSTRATUS_BASE  =    172.80;   // 900 m
const float PLAGUE_CLOUD_NIMBOSTRATUS_DEPTH =    384.00;   // 2000 m
const float PLAGUE_CLOUD_NIMBOSTRATUS_CELL  =    768.00;   // 4000 m
const float PLAGUE_CLOUD_NIMBOSTRATUS_TAU   =   50.0000;
const float PLAGUE_CLOUD_NIMBOSTRATUS_SHEAR =    1.0000;
const float PLAGUE_CLOUD_NIMBOSTRATUS_COVER =    1.0000;   // 8 oktas

// Cumulonimbus, low deck, water
const float PLAGUE_CLOUD_CUMULONIMBUS_BASE  =    153.60;   // 800 m
const float PLAGUE_CLOUD_CUMULONIMBUS_DEPTH =   1920.00;   // 10000 m
const float PLAGUE_CLOUD_CUMULONIMBUS_CELL  =   1536.00;   // 8000 m
const float PLAGUE_CLOUD_CUMULONIMBUS_TAU   =   90.0000;
const float PLAGUE_CLOUD_CUMULONIMBUS_SHEAR =    4.0000;
const float PLAGUE_CLOUD_CUMULONIMBUS_COVER =    0.6250;   // 5 oktas

// Cumulus congestus: a species of the cumulus genus, not a genus row of its own. Not composited
// independently; plagueCloudLowDeck interpolates depth and tau toward this point as rain builds.
// Cell and shear stay cumulus's own, so this point carries neither.
const float PLAGUE_CLOUD_CONGESTUS_DEPTH =    192.00;   // 1000 m
const float PLAGUE_CLOUD_CONGESTUS_TAU   =   18.0000;

// --- end of the derived block -------------------------------------------------------------------

// Authored: the derivation script has no source for this axis. Selects the height-profile shape,
// 0 = flat stratiform sheet, 1 = tower narrow at the base and rounding off at top, i.e. how much of
// the genus's silhouette a rising parcel made versus a layer condensing in place.
const float PLAGUE_CLOUD_CIRRUS_CONVECTIVE        = 0.00;  // ice fall-streaks laid along the shear;
                                                           // no updraught shapes it at all
const float PLAGUE_CLOUD_CIRROCUMULUS_CONVECTIVE  = 0.35;  // genuinely cellular, the WMO names it by
                                                           // its granulation, but only 400 m deep,
                                                           // so no tower ever develops
const float PLAGUE_CLOUD_ALTOCUMULUS_CONVECTIVE   = 0.40;  // the same cellular sheet one etage down
                                                           // and half again as deep
const float PLAGUE_CLOUD_CUMULUS_CONVECTIVE       = 1.00;  // the reference convective genus: a flat
                                                           // base and a cauliflower top is its
                                                           // definition, and the low deck is built
                                                           // to draw exactly that
const float PLAGUE_CLOUD_STRATOCUMULUS_CONVECTIVE = 0.30;  // rolls and mounds that convect under an
                                                           // inversion; the lid is what flattens the
                                                           // top, so the shape is mostly sheet
const float PLAGUE_CLOUD_STRATUS_CONVECTIVE       = 0.00;  // fog lifted off the ground, the
                                                           // stratiform end of the axis by
                                                           // definition, and the reason 0 exists
const float PLAGUE_CLOUD_NIMBOSTRATUS_CONVECTIVE  = 0.00;  // "grey, often dark, its appearance
                                                           // rendered diffuse by falling rain": a
                                                           // sheet, so the same end of the axis as
                                                           // stratus despite its far greater depth
const float PLAGUE_CLOUD_CUMULONIMBUS_CONVECTIVE  = 1.00;  // the deepest convection there is; its
                                                           // anvil comes from the table's own shear
                                                           // of 4.0, not from this axis

// --- Base-volume calibration --------------------------------------------------------------------
//
// The two-scale base-volume field is not uniform on 0..1. tools/verify_clouds.py takes 500,000
// deterministic trilinear samples over the 24x24x1 joint domain at the accepted size ratio: mean
// 0.51463, sigma 0.09489 after the centered fourfold organization-Y calibration. These statistics
// pin the authored volume and catch accidental sampler/coordinate changes; candidate allocation no
// longer derives a moving cutoff from aggregate coverage.
const float PLAGUE_CLOUD_FIELD_MEAN  = 0.51463;
const float PLAGUE_CLOUD_FIELD_SIGMA = 0.09489;
// Remap ceiling: the same sample's 99.9th percentile is 0.78005, so the top 0.1% saturates rather
// than normalising against an unreachable 1.0.
const float PLAGUE_CLOUD_FIELD_TOP   = 0.78005;

/**
 * How far u_CloudAltitude moves the low deck from the table's placement, blocks.
 *
 * A shift, not an assignment: the low etage's four genera sit at four different published
 * altitudes, and assigning the slider to `base` would flatten them onto one plane once the driver
 * blends between them. Zero at the default, since the slider's default equals cumulus's own base.
 */
float plagueCloudLowDeckShift() {
    return u_CloudAltitude - PLAGUE_CLOUD_CUMULUS_BASE;
}

/**
 * The game's own cloud altitude, world blocks: what the low deck is measured from.
 *
 * Reads u_CameraSkyLight.w, vanilla's cloudHeight argument captured by the engine at the moment it
 * cancels vanilla's cloud pass, so it reflects whatever mod last changed it, with no need to know
 * which mod that was. Falls back to the table's own cumulus base when the lane reads 0 (before any
 * cloud pass has registered, and in dimensions that never draw clouds), since 0.0 taken literally
 * would put the deck below bedrock. Branches rather than max(), because a mod is free to set a cloud
 * height below this fallback and max() would refuse to follow it down.
 *
 * The mid/high decks will scale proportionally from this base, not take their table altitudes
 * directly, so cumulus can never end up above cirrus on a raised install.
 */
float plagueCloudEngineBase() {
    return u_CameraSkyLight.w > 0.0 ? u_CameraSkyLight.w : PLAGUE_CLOUD_CUMULUS_BASE;
}

// Precipitation kinds, for the driver signature below. Named rather than numbered at the call site,
// so that adding a third cannot silently renumber a comparison somebody wrote as a literal.
const int PLAGUE_PRECIP_NONE = 0;
const int PLAGUE_PRECIP_RAIN = 1;
const int PLAGUE_PRECIP_SNOW = 2;

// Cover ceiling at full storm response: 5 oktas, broken-to-overcast, short of stratus's solid 8.
// Authored: WMO carries no separate coverage figure for congestus. Coverage near 1.0 merges every
// cloud into its neighbours and erases silhouettes, so the ceiling stays well clear of it.
const float PLAGUE_CLOUD_STORM_COVER = 0.6250;

// Precipitation endpoints authored against the owner's 2026-08-28 transition capture. Rain's 1.65
// footprint and family 0.30 close the gaps into a broad stratiform/congestus layer instead of a
// miniature vertical tower; snow is slightly shallower/flatter at 1.55 and family 0.15. The 0.875
// lighting cover is seven oktas: visibly overcast while retaining occasional breaks. Thunder's
// accepted 1.75/family-2 endpoint remains unchanged and overrides either precipitation endpoint.
const float PLAGUE_CLOUD_RAIN_FOOTPRINT = 1.65;
const float PLAGUE_CLOUD_SNOW_FOOTPRINT = 1.55;
const float PLAGUE_CLOUD_CUMULONIMBUS_FOOTPRINT = 1.75;
const float PLAGUE_CLOUD_RAIN_FAMILY = 0.30;
const float PLAGUE_CLOUD_SNOW_FAMILY = 0.15;
const float PLAGUE_CLOUD_PRECIPITATION_COVER = 0.875;

// Accepted live/default Cloud Size whose existing 57.6-block cumulus coordinate frequency is
// preserved. Measured from the owner's current working settings before stabilising the slider.
const float PLAGUE_CLOUD_REFERENCE_SCALE = 0.30;

// The owner-calibrated 0.20 exponent maps the full 0.20..2.00 UI span to 0.922..1.461 linear size.
// That range changes each stable owner's density isosurface without changing texture-field periods.
const float PLAGUE_CLOUD_SIZE_EXPONENT = 0.20;

// Population response and ceiling authored against the six 2026-08-28 high-altitude owner
// captures. A quarter response gives the default/max dry settings activation thresholds 0.50 and
// 0.707; 0.72 leaves headroom for weather while guaranteeing no setting fills the complete
// stratified lattice and exposes it as a grid.
const float PLAGUE_CLOUD_POPULATION_RESPONSE = 0.25;
const float PLAGUE_CLOUD_POPULATION_MAX = 0.72;

// Fixed per-candidate interior threshold: the shipped two-volume field's measured 75% superlevel
// cutoff. Amount owns population now, so this value must never move with aggregate coverage.
const float PLAGUE_CLOUD_CANDIDATE_CUTOFF = 0.450656;

// Measured over the fixed 24x24 owner calibration at reference Size: candidate potential area times
// fixed-cut base occupancy. This is aggregate lighting/reporting data, never a density-shape input.
const float PLAGUE_CLOUD_REFERENCE_OCCUPANCY = 0.34111;

// Used only by clouds.glsl's reference step-budget expression; candidate density reads the fixed
// table depth directly and never derives from this reciprocal.
const float PLAGUE_CLOUD_CUMULUS_VERTICAL_ASPECT = 3.33333333;

/**
 * Midpoint of the clear cumulus reference deck, without resolving the full weather driver.
 *
 * The direct compute march needs this only to choose one world-XZ weather sample before it knows
 * the local rain/snow state. Calling plagueCloudActiveDeck once for that proxy and again for the
 * real deck duplicates the whole driver in the generated Metal function; the Apple backend rejects
 * that expanded compute pipeline. Keep this algebra identical to plagueCloudLowDeck's clear arm
 * while leaving the full driver to the one result that is actually marched.
 */
float plagueCloudClearReferenceMidAltitude() {
    float physicalScale = pow(max(u_CloudScale, 0.05) / PLAGUE_CLOUD_REFERENCE_SCALE,
                              PLAGUE_CLOUD_SIZE_EXPONENT);
    return plagueCloudEngineBase() + plagueCloudLowDeckShift()
            + 0.5 * PLAGUE_CLOUD_CUMULUS_DEPTH * physicalScale;
}

/**
 * How far the sky has changed genus: 0 convective, 1 stratiform. Thunder pulls it back to zero,
 * since a cumulonimbus is the storm itself rather than the sheet in front of one.
 */
float plagueCloudStratiformWeight(float rainFactor, float thunderFactor) {
    float response = clamp(u_CloudWeatherResponse, 0.0, 1.0);
    float rain = clamp(rainFactor, 0.0, 1.0) * response;
    float thunder = clamp(thunderFactor, 0.0, 1.0) * response;
    return smoothstep(PLAGUE_CLOUD_STRATIFORM_ONSET, PLAGUE_CLOUD_STRATIFORM_FULL, rain)
         * (1.0 - thunder);
}

/**
 * The low deck, resolved for this instant. Interpolates cumulus toward congestus on rainFactor,
 * then congestus toward cumulonimbus on thunderFactor. Rain/snow grow depth and tau while keeping
 * candidate membership fixed; thunder may add storm cells. Cover reports expected aggregate
 * occupancy for lighting. Cell, shear, and every
 * texture coordinate stay fixed (see plagueCloudSampleCoord's world-origin constraint in
 * cloud_density.glsl). Footprint and family are morphology data: rain broadens into congestus and
 * thunder broadens again into the existing storm-top profile without rephasing the field.
 * snowWeight continuously selects the rain/snow stratiform endpoint; sunElevation and worldTime are accepted
 * and ignored for the future multi-deck driver.
 *
 * @param rainFactor     u_SkyState.x, 0..1. Grows existing candidates toward rain/snow morphology.
 * @param thunderFactor  0..1. Drives depth and tau from congestus toward cumulonimbus.
 * @param wetness        smoothed surface-wetness state, 0..1. Not used: it lags cloud weather.
 * @param snowWeight     0 rain morphology, 1 snow morphology, continuous between.
 * @param sunElevation   sin(sun elevation), u_SunDirection.w. Not yet wired.
 * @param worldTime      world clock, seconds. Not yet wired.
 */
PlagueCloudDeck plagueCloudLowDeck(float rainFactor, float thunderFactor, float wetness,
                                   float snowWeight, float sunElevation, float worldTime) {
    PlagueCloudDeck deck;

    float response = clamp(u_CloudWeatherResponse, 0.0, 1.0);
    float rainStorm = clamp(rainFactor, 0.0, 1.0) * response;
    float thunderStorm = clamp(thunderFactor, 0.0, 1.0) * response;
    float snowWeather = clamp(snowWeight, 0.0, 1.0);

    float precipitationDepth = mix(PLAGUE_CLOUD_CONGESTUS_DEPTH,
                                   PLAGUE_CLOUD_STRATOCUMULUS_DEPTH, snowWeather);
    float precipitationTau = mix(PLAGUE_CLOUD_CONGESTUS_TAU,
                                 PLAGUE_CLOUD_STRATOCUMULUS_TAU, snowWeather);
    float precipitationFootprint = mix(PLAGUE_CLOUD_RAIN_FOOTPRINT,
                                       PLAGUE_CLOUD_SNOW_FOOTPRINT, snowWeather);
    float precipitationFamily = mix(PLAGUE_CLOUD_RAIN_FAMILY,
                                    PLAGUE_CLOUD_SNOW_FAMILY, snowWeather);

    // Two-stage mix: calm cumulus to the local rain/snow endpoint, then to cumulonimbus. Chaining
    // keeps full thunder byte-for-byte independent of which precipitation endpoint it grew from.
    // Congestus is a convective shower species, not a frontal rain sheet, so the cumulus deck
    // hands its precipitation growth over as the stratiform deck arrives. Without this the sky
    // both fattens its cumulus and grows a sheet, which reads as two weathers at once.
    float convectiveRain = rainStorm
                         * (1.0 - plagueCloudStratiformWeight(rainFactor, thunderFactor));
    float depthAfterRain = mix(PLAGUE_CLOUD_CUMULUS_DEPTH, precipitationDepth, convectiveRain);
    float tauAfterRain = mix(PLAGUE_CLOUD_CUMULUS_TAU, precipitationTau, convectiveRain);

    // The bounded perceptual response was fit over the five Size knots recorded by the cloud
    // verifier. It grows physical depth and lowers a fixed-field density isosurface; it never
    // scales an analytic candidate radius or a world-coordinate divisor.
    float physicalScale = pow(max(u_CloudScale, 0.05) / PLAGUE_CLOUD_REFERENCE_SCALE,
                              PLAGUE_CLOUD_SIZE_EXPONENT);
    deck.depth      = mix(depthAfterRain, PLAGUE_CLOUD_CUMULONIMBUS_DEPTH, thunderStorm)
                    * physicalScale;
    deck.cell       = PLAGUE_CLOUD_CUMULUS_CELL * PLAGUE_CLOUD_REFERENCE_SCALE;
    deck.sizeRatio  = physicalScale;
    deck.shear      = PLAGUE_CLOUD_CUMULUS_SHEAR;
    deck.tau        = mix(tauAfterRain, PLAGUE_CLOUD_CUMULONIMBUS_TAU, thunderStorm);
    deck.footprint  = mix(mix(1.0, precipitationFootprint, convectiveRain),
                          PLAGUE_CLOUD_CUMULONIMBUS_FOOTPRINT, thunderStorm);
    deck.family     = mix(mix(PLAGUE_CLOUD_CUMULUS_CONVECTIVE,
                              precipitationFamily, rainStorm),
                          2.0, thunderStorm);

    // Shift, not assignment: see plagueCloudLowDeckShift.
    deck.base = plagueCloudEngineBase() + plagueCloudLowDeckShift();

    // Amount owns clear/rain/snow membership, so precipitation cannot cross a hard rank and pop a
    // new cloud into existence. Thunder retains its accepted extra storm-cell population endpoint.
    float amount = max(u_CloudAmount, 0.0);
    float thunderPopulation = mix(1.0,
            PLAGUE_CLOUD_STORM_COVER / PLAGUE_CLOUD_CUMULUS_COVER, thunderStorm);
    deck.population = amount <= 0.0
            ? 0.0
            : min(sqrt(max(PLAGUE_CLOUD_POPULATION_RESPONSE * amount * thunderPopulation, 0.0)),
                  PLAGUE_CLOUD_POPULATION_MAX);
    float clearCover = clamp(PLAGUE_CLOUD_REFERENCE_OCCUPANCY
                             * min(sqrt(max(PLAGUE_CLOUD_POPULATION_RESPONSE * amount, 0.0)),
                                   PLAGUE_CLOUD_POPULATION_MAX)
                             * physicalScale * physicalScale, 0.0, 1.0);
    float precipitationCover = mix(clearCover, PLAGUE_CLOUD_PRECIPITATION_COVER, rainStorm);
    deck.cover = amount <= 0.0
            ? 0.0
            : clamp(mix(precipitationCover, PLAGUE_CLOUD_PRECIPITATION_COVER,
                        thunderStorm), 0.0, 1.0);
    deck.cut = PLAGUE_CLOUD_CANDIDATE_CUTOFF;
    deck.sheetFloor = PLAGUE_CLOUD_SHEET_NONE;

    return deck;
}

/**
 * The precipitating stratiform deck. Not a morph of the cumulus deck: rain does not fall from
 * fatter cumulus, it falls from nimbostratus, which is its own genus with its own altitude, cell
 * and shear. Resolved through the low etage's own altitude shift so Cloud Altitude still moves it,
 * offset by the two genera's published base separation rather than assigned the slider outright.
 *
 * Its cell is constant, like the low deck's: the world-origin prohibition forbids a cell that moves
 * with time or a slider, not two decks holding different fixed ones.
 */
PlagueCloudDeck plagueCloudNimbostratusDeck(float stratiformWeight) {
    PlagueCloudDeck deck;

    float physicalScale = pow(max(u_CloudScale, 0.05) / PLAGUE_CLOUD_REFERENCE_SCALE,
                              PLAGUE_CLOUD_SIZE_EXPONENT);
    float amount = max(u_CloudAmount, 0.0);

    deck.base = plagueCloudEngineBase() + plagueCloudLowDeckShift()
              + (PLAGUE_CLOUD_NIMBOSTRATUS_BASE - PLAGUE_CLOUD_CUMULUS_BASE);
    deck.depth = PLAGUE_CLOUD_NIMBOSTRATUS_DEPTH * physicalScale;
    deck.cell = PLAGUE_CLOUD_NIMBOSTRATUS_CELL * PLAGUE_CLOUD_REFERENCE_SCALE;
    deck.shear = PLAGUE_CLOUD_NIMBOSTRATUS_SHEAR;
    // From zero, not from the cumulus figure. Optical depth is the sheet's water path, and a cloud
    // that has not arrived has none. Starting it at 9 put the first material on screen at 46%
    // opacity: MIN_SPAN floors the coverage span, so the field's top 0.26% clears the cutoff at
    // raw 0.69 the instant the deck engages, and that appeared out of nothing.
    // Squared, not linear: a linear ramp reached opacity 0.98 by the time coverage was 0.8%, so a
    // handful of tiny patches went solid before the sheet had spread anywhere. Squaring keeps the
    // veil translucent while coverage builds, which is the order a front actually thickens in.
    deck.tau = PLAGUE_CLOUD_NIMBOSTRATUS_TAU * stratiformWeight * stratiformWeight;
    deck.cover = PLAGUE_CLOUD_NIMBOSTRATUS_COVER;
    deck.family = PLAGUE_CLOUD_NIMBOSTRATUS_CONVECTIVE;
    deck.sizeRatio = physicalScale;
    deck.cut = PLAGUE_CLOUD_CANDIDATE_CUTOFF;

    // Amount still owns membership: at zero there is no sky to overcast. The candidates that
    // survive ride on top of the sheet as ragged base variation rather than being the whole cloud.
    deck.population = amount <= 0.0
            ? 0.0
            : min(sqrt(max(PLAGUE_CLOUD_POPULATION_RESPONSE * amount, 0.0)),
                  PLAGUE_CLOUD_POPULATION_MAX);
    deck.footprint = 1.0;
    // The floor is the arrival, not an alpha fade. It starts exactly at the early-out, so the
    // sheet is empty, and rises: the highest values in the base volume clear the cutoff first and
    // appear as scattered patches, which widen and merge as it rises further. The sky fills in
    // where the field says, in its own order, instead of every pixel fading up together.
    deck.sheetFloor = mix(PLAGUE_CLOUD_CANDIDATE_CUTOFF - PLAGUE_CLOUD_FIELD_TOP,
                          PLAGUE_CLOUD_SHEET_FLOOR, stratiformWeight);

    return deck;
}

/**
 * The single contributor-selection seam used by every live cloud integration path. Future weather
 * types select their contributors here while the march, shadow, and reflection stay one path each.
 *
 * Returns whichever genus currently owns the sky. Mid-transition that is a step, which is why the
 * direct march takes both contributors from plagueCloudTransitionDecks instead: shadow and
 * reflection are a three-tap and a single sample, too coarse for the seam to be worth doubling.
 */
PlagueCloudDeck plagueCloudActiveDeck(float rainFactor, float thunderFactor, float wetness,
                                      float snowWeight, float sunElevation, float worldTime) {
    float stratiform = plagueCloudStratiformWeight(rainFactor, thunderFactor);
    if (stratiform >= 0.5) {
        return plagueCloudNimbostratusDeck(stratiform);
    }
    return plagueCloudLowDeck(rainFactor, thunderFactor, wetness, snowWeight, sunElevation,
                              worldTime);
}

/**
 * Both contributors and the weight between them, for the one path that can afford two marches.
 * Two genera cannot be blended field by field, since cell and shear are fixed per deck, so the
 * transition is a dissolve between two marched results rather than an interpolated deck.
 */
float plagueCloudTransitionDecks(float rainFactor, float thunderFactor, float wetness,
                                 float snowWeight, float sunElevation, float worldTime,
                                 out PlagueCloudDeck convective, out PlagueCloudDeck stratiform) {
    convective = plagueCloudLowDeck(rainFactor, thunderFactor, wetness, snowWeight, sunElevation,
                                    worldTime);
    float weight = plagueCloudStratiformWeight(rainFactor, thunderFactor);
    stratiform = plagueCloudNimbostratusDeck(weight);
    return weight;
}

#endif // PLAGUE_CLOUD_TYPES
