#ifndef PLAGUE_CLOUDS
#define PLAGUE_CLOUDS

// Composited over the pack's fog terms (see the tail of plagueGetClouds): a cloud is in the air
// fog describes, and skipping this splits the sky into two atmospheres at the horizon.
//
// Deliberately imports fog_options/fog_model, not fog.glsl itself: that pulls in the whole
// underwater chain and broke live once the option merge saw the enlarged declaration set.
#moj_import <fornax_runtime:fog_options.glsl>
#moj_import <fornax_runtime:fog_model.glsl>

// Density is coverage * heightProfile(genus) * erosion, kept as separate factors because the
// weather driver moves them independently per genus and state; see cloud_density.glsl. Cloud
// Amount moves the direct coverage cutoff; height profile shapes the genus silhouette; erosion
// frays the edges only. Genus table (cloud_types.glsl, generated by tools/derive_cloud_types.py)
// supplies every figure this file consumes.
//
// Construction: Schneider & Vos, "The Real-Time Volumetric Cloudscapes of Horizon Zero Dawn"
// (SIGGRAPH 2015 Advances in Real-Time Rendering course): two-scale weather field and the
// powder term below.
//
// Single-scattering only; no multiple-scattering model here (see PLAGUE_CLOUD_MS_* below).

#moj_import <fornax_runtime:sky_hash.glsl>
#moj_import <fornax_runtime:cloud_types.glsl>
#moj_import <fornax_runtime:light_and_ambient_colors.glsl>
#moj_import <fornax_runtime:sky.glsl>
// Named directly though sky.glsl already pulls it in: the march reads plagueMoonColor and
// plagueAirEyePos and should say where they come from rather than inherit them transitively.
#moj_import <fornax_runtime:atmosphere.glsl>

// ------------------------------------------------------------------------------------------------
// Options
// ------------------------------------------------------------------------------------------------
//
// Import only from a fullscreen pass: the runtime option below and cloud_types.glsl's two arrive
// via u_PackOptions, which deferred geometry programs never receive.

// Read by name by the engine to cancel vanilla clouds (GraphRunner.packOwnsClouds) and by
// graph.toml to gate every cloud target/pass: an engine contract, not just a pack option.
#define CLOUDS_VOLUMETRIC 1 //[0 1] compile "Volumetric Clouds" {0="Off" 1="On"}

// Tier 2 marches into a full-scale target, a different one from tiers 0/1's half-scale target;
// graph.toml partitions on `!= 2` vs `== 2` for exactly that reason.
#define CLOUD_QUALITY 1 //[0 1 2] compile "Cloud Quality" {0="Fast" 1="Balanced" 2="Ultra"}

// Multiple of the derived wind speed below; 0 freezes the deck for screenshots/bisection. Top of
// range moves a cumulus cell past the viewer in about a quarter in-game hour, a squall line on
// purpose.
#define u_CloudSpeed 1.0 //[0.00..4.00 step 0.05] runtime "Cloud Speed"

// ------------------------------------------------------------------------------------------------
// The noise hook
// ------------------------------------------------------------------------------------------------
//
// Each consuming pass supplies the sampler as a macro, since an include cannot declare a sampler
// uniform and have two passes bind it at two different input slots:
//
//     #define PLAGUE_CLOUD_NOISE_3D(uvw) texture(u_InputN, uvw)
//     #define PLAGUE_CLOUD_DETAIL_3D(uvw) texture(u_InputN, uvw)
//     #moj_import <fornax_runtime:clouds.glsl>
//
// The #define must precede this import: it expands inside the functions below, so importing
// first uses the uniform before its own declaration. Not threaded as a function parameter
// (contrast aurora.glsl) because the density function is called from two different nesting
// depths, and a threaded sampler there is how the two ends up sampling different textures.
//
// PLAGUE_CLOUD_NOISE_3D/PLAGUE_CLOUD_DETAIL_3D are the real 3D Worley volumes (see
// tools/generate_cloud_noise.py) the coverage/erosion fields sample directly. Only a compute pass
// can bind a real sampler3D, since Vulkan's fullscreen-pipeline shader-reflection step refuses any
// non-2D/Cube sampler outright, so the direct-view march (shaders/compute/clouds_march_volume.comp)
// is a compute pass and defines these as real texture() calls. gbuffer_resolve.fsh's cloud-shadow
// query and water_environment.fsh's reflection imposter are both fullscreen passes: for those two
// the macro is instead an ALU approximation (plagueSkyFbm, the same primitive the field's warp
// already uses), the same cheap-field-for-a-cheap-consumer pattern plagueCloudDensityCoarseIn uses
// for the sun march. Never a bare constant, which would flatten shadow/reflection density to a
// uniform wash with no spatial structure at all.
#if CLOUDS_VOLUMETRIC
#ifndef PLAGUE_CLOUD_NOISE_3D
#error clouds.glsl needs PLAGUE_CLOUD_NOISE_3D(uvw) defined before the import. See the noise-hook contract at the top of this file.
#endif
#ifndef PLAGUE_CLOUD_DETAIL_3D
#error clouds.glsl needs PLAGUE_CLOUD_DETAIL_3D(uvw) defined before the import. See the noise-hook contract at the top of this file.
#endif
#endif

// ------------------------------------------------------------------------------------------------
// Quality tiers
// ------------------------------------------------------------------------------------------------
//
// Slab steps: vertical samples through the deck. Cap: max samples before the step must stretch (a
// near-horizon ray hits it almost immediately; a vertical ray never does).
//
// Each step integrates the closed-form density-over-segment analytically, so halving the count
// converges to the same total opacity rather than thinning it: undersampling costs per-pixel
// variance (absorbed by dither + temporal resolve), not a dimmer sky.
//
// Sun taps: self-shadowing march cost, which runs per lit sample so it scales with cloud
// coverage. One tap at Fast, two at Balanced, three at Ultra: the same code path, with cost
// scaling with tier the same way step counts already do.
#if CLOUD_QUALITY == 0
#define PLAGUE_CLOUD_SLAB_STEPS 2
#define PLAGUE_CLOUD_MAX_STEPS  32
#define PLAGUE_CLOUD_SUN_TAPS   1
#elif CLOUD_QUALITY == 2
#define PLAGUE_CLOUD_SLAB_STEPS 12
#define PLAGUE_CLOUD_MAX_STEPS  128
#define PLAGUE_CLOUD_SUN_TAPS   3
#else
#define PLAGUE_CLOUD_SLAB_STEPS 6
#define PLAGUE_CLOUD_MAX_STEPS  64
#define PLAGUE_CLOUD_SUN_TAPS   2
#endif

// Step count multiplier ceiling for a deck deeper than clear sky. Bounds a tall storm deck to
// 3x the tier's own step count.
const float PLAGUE_CLOUD_DEPTH_STEP_CAP = 3.0;

// ------------------------------------------------------------------------------------------------
// Constants
// ------------------------------------------------------------------------------------------------

// Integer lattice direction, not a unit vector, deliberately: (11,-4) is within 0.03 degrees of
// the westerlies bearing the genus table's WMO bands assume, and being integer lets the drift
// wrap land on a lattice boundary at every fbm octave (see PLAGUE_CLOUD_DRIFT_WRAP).
const vec2 PLAGUE_CLOUD_WIND = vec2(11.0, -4.0);
const float PLAGUE_CLOUD_WIND_LENGTH = 11.7046999107;   // sqrt(137)
const vec2 PLAGUE_CLOUD_WIND_UNIT = PLAGUE_CLOUD_WIND / PLAGUE_CLOUD_WIND_LENGTH;

// 1.92 blocks/s: a fair-weather cumulus drifts near its own base speed (~10 m/s, temperate
// mid-latitudes), and tools/derive_cloud_types.py's 0.192 blocks/metre scale gives 10 m/s here.
// Cross-check: a 192-block cumulus cell is then replaced by its neighbour in ~2 in-game hours.
const float PLAGUE_CLOUD_WIND_SPEED = 1.92;

// Wraps the drift after 1000 steps to avoid the fp32 clock trap: syncedTime is unwrapped seconds,
// so on a long-lived world the drift term grows until it swallows the per-pixel spatial offset's
// low bits and floor() collapses whole regions into one cell.
//
// 1000 * PLAGUE_CLOUD_WIND is divisible by 125 = 5^3, which keeps the jump integral through all
// four coverage octaves (plagueSkyFbm's per-octave (2/5)^k lattice transform), so the wrap
// introduces no seam: the field becomes a different field, not a torn one. At default speed the
// wrap fires only after roughly 325 hours of continuous world time.
const float PLAGUE_CLOUD_DRIFT_WRAP = 1000.0;

// Eight fixed reference cells per domain-warp cycle: measured as the broadest bend that breaks the
// volume tile's exact repeat without visibly distorting one cloud silhouette. With the 57.6-block
// reference cell this is a 460.8-block warp cycle at every Cloud Size.
const float PLAGUE_CLOUD_WEATHER_CLOUDS = 8.0;

// Domain-warp amplitude, in cell units, plagueCloudSampleCoord applies before the 3D noise volumes
// are sampled: breaks their exact one-cell periodicity, which Moires under perspective at grazing
// view angles (a radiating fan of light/dark rays; see plagueCloudSampleCoord's own comment for the
// full mechanism). Authored: 1.0 (up to half a cell of drift at full swing) keeps one cloud's own
// silhouette undistorted; retune against a render if a future genus's smaller cell makes the warp
// read as shimmer up close.
const float PLAGUE_CLOUD_WARP_STRENGTH = 1.0;

// Floor on the remap denominator: at coverage 0 the solved cutoff exceeds the field's measured
// maximum and the span goes non-positive, so this keeps the division defined (the clamped result
// is an empty sky either way).
const float PLAGUE_CLOUD_MIN_SPAN = 0.05;

// Interpolated per-genus between a sheet value and a tower value on `family`. Solved against
// the drawn silhouette (cross-section width by height) rather than chosen: 0.06/0.45 keeps the
// tower base flat and wide with just enough rim curl to read as an edge, not a cut. The asymmetry
// (flat base, rounded top) is what reads as a cumulus rather than a lens or smoke. Sheet's two
// edges sit inside the tower's, just enough to keep the march from aliasing a hard face.
const float PLAGUE_CLOUD_SHEET_BASE = 0.04;
const float PLAGUE_CLOUD_SHEET_TOP  = 0.92;
const float PLAGUE_CLOUD_TOWER_BASE = 0.06;
const float PLAGUE_CLOUD_TOWER_TOP  = 0.45;

// Ceiling on erosion cells per coverage cell / slab depth: 8, since a cumulus turret is roughly a
// tenth of its cloud. Applied per axis against the slab's own dimensions so every genus gets the
// same cell count through its own thickness regardless of blocks. The march's actual value,
// plagueCloudErosionCells, lowers this wherever 8 would undersample the finest octave below the
// march's own step (binds at the Fast tier).
const float PLAGUE_CLOUD_EROSION_CELLS = 8.0;

// 2.17, not 2.0: an exact doubling re-aligns every second lattice line of the two erosion octaves
// and prints a visible cross-hatch. Offset is three coprime integers so the octaves never share a
// texture slice.
const float PLAGUE_CLOUD_EROSION_LACUNARITY = 2.17;
const vec3 PLAGUE_CLOUD_EROSION_OFFSET = vec3(37.0, 11.0, 53.0);

// Erosion is weighted by s(1-s)^2 in shaped density s (zero at s=0 and s=1, so it neither erodes
// past the solved coverage cutoff nor eats a dense core down to static). PEAK = 27/4 =
// 1/max(s(1-s)^2), normalising the weight to peak at 1. STRENGTH = 1/3 is the largest value for
// which erosion cannot punch a hole above the weight's own peak (from (1/3)(27/4)s(1-s)^2 <= s,
// i.e. s >= 1/3).
const float PLAGUE_CLOUD_EROSION_PEAK = 6.75;
const float PLAGUE_CLOUD_EROSION_STRENGTH = 0.33333333;

// Forward: Mie asymmetry of a cloud-droplet distribution in visible light, ~0.85 (Hansen & Travis
// 1974, "Light scattering in planetary atmospheres"), taken as published.
// Multi: authored stand-in for the isotropised multiply-scattered field; -0.20 is mild enough to
// stay near-isotropic while still separating front-lit from side-lit faces.
const float PLAGUE_CLOUD_PHASE_FORWARD = 0.85;
const float PLAGUE_CLOUD_PHASE_MULTI = -0.20;

// Authored against paired noon-above and below-near-sun captures: retaining 10% of the raw
// droplet anisotropy keeps the two-octave forward/back response inside 2x-12x while mixing with
// the unit spherical mean preserves phase energy and avoids a near-sun HDR spike.
const float PLAGUE_CLOUD_PHASE_ANISOTROPY = 0.10;

// Authored against the noon-above acceptance capture after phase compression: a fully sun-visible
// upper crown needs one additional copy of its bounded direct term to read white. Height starts
// halfway to the field's minimum parcel top, while squared light/view gates leave lower bodies,
// occluded interiors, side views and the near-sun forward lobe at or near identity.
const float PLAGUE_CLOUD_CROWN_LIGHT_GAIN = 1.0;

// Multiple-scattering correction (Wrenninge, Kulla & Lombardi, "Art-Directable Multiple
// Volumetric Scattering", SIGGRAPH 2013 Talks): approximates the multiply-scattered field as a
// sum of single-scattering evaluations at reduced extinction, energy and phase asymmetry per
// order of scattering:
//
//     L ~= sum over n of  A^n * S(sigma * B^n, phase with g * C^n)
//
// Needed because single scattering under-predicts a thick cloud's brightness (a real cumulus,
// albedo 0.6-0.9, is bright from many internal bounces the direct term alone can't produce).
//
// A = ENERGY = 0.5, C = PHASE = 0.5 are the paper's published values. Two octaves, not three:
// geometric in A, so the third carries only 14% of the correction for a third of its cost.
// B (extinction reduction) is also 0.5 but isn't a constant here: the march computes
// transmittance^(B^n) as a chain of sqrt() (two per lit sample) rather than pow() calls.
const int   PLAGUE_CLOUD_MS_OCTAVES = 2;
const float PLAGUE_CLOUD_MS_ENERGY  = 0.5;   // A, energy surviving each further bounce
const float PLAGUE_CLOUD_MS_PHASE   = 0.5;   // C, how much of the forward bias it remembers

// Tier-counted taps at geometrically growing spacing: fine near the sample (where most shadowing
// optical depth is), cheap farther away. The unsampled path is closed analytically below, so each
// tier retains its existing one/two/three density lookups without treating the short fan as the
// whole light ray.
//
// Cone is lateral spread per unit distance, alternating side to side, not the solar disc (0.27
// degrees, pointless to sample), but the neighbourhood whose material actually shades this
// sample. 0.15 puts the last tap ~40 blocks off-axis, into the neighbouring cumulus cell.
const float PLAGUE_CLOUD_SUN_STEP = 0.06;
const float PLAGUE_CLOUD_SUN_GROWTH = 2.0;
const float PLAGUE_CLOUD_SUN_CONE = 0.15;

// Break threshold: one part in 256, the finest step an 8-bit display carries. The remaining
// transmittance stays in alpha rather than zeroing, so the composite is continuous through the
// threshold rather than stepping at it.
const float PLAGUE_CLOUD_MIN_TRANSMITTANCE = 0.0039;

// Sign-preserving floor on |viewDir.y|, not an early return: a level ray divides to infinity
// against the slab planes and the inf-minus-inf NaN survives every downstream max/mix/clamp,
// painting a white horizon band with no error. An early return would instead draw a one-pixel
// seam at the horizon. The value is small enough to be inert: the slab intersection lands ~2M
// blocks out, well past the deck's own horizon cutoff.
const float PLAGUE_CLOUD_RAY_EPSILON = 1e-4;

#if CLOUDS_VOLUMETRIC

#moj_import <fornax_runtime:cloud_density.glsl>

// ------------------------------------------------------------------------------------------------
// Scattering
// ------------------------------------------------------------------------------------------------

/**
 * Cornette-Shanks phase function, normalised so an isotropic scatterer returns exactly 1
 * (Cornette & Shanks 1992, "Physically reasonable analytic expression for the single-scattering
 * phase function"; the published 3/(8*pi) form times 4*pi, so the value reads directly as "how
 * many times more light goes this way than an isotropic scatterer would send").
 *
 * @param cosTheta cosine of the angle between the view ray and the direction TOWARD the light
 * @param g        asymmetry: positive forward, negative backward, 0 gives the Rayleigh shape
 */
float plagueCloudPhase(float cosTheta, float g) {
    float g2 = g * g;
    float d = 1.0 + g2 - 2.0 * g * cosTheta;
    // Guards a caller passing |g| = 1 (d's true minimum is 0.0225 at the forward lobe's own g).
    return 1.5 * (1.0 - g2) * (1.0 + cosTheta * cosTheta)
         / ((2.0 + g2) * max(d * sqrt(d), 1e-4));
}

/**
 * Light reaching this sample: the existing short fan toward the light plus a bounded analytic
 * estimate of the path the fan cannot afford to sample, then Beer-Lambert on the combined optical
 * depth. Shades a cloud by density between it and the sun rather than by height alone.
 *
 * @param lightDir unit vector toward the active body: the sun by day, the moon by night
 */
float plagueCloudLightTransmittance(vec3 pos, vec3 lightDir, PlagueCloudDeck deck, vec2 drift,
                                    float density) {
#if PLAGUE_CLOUD_SUN_TAPS == 0
    // Analytic: assumes today's density holds through the rest of the slab and integrates the
    // slant path to the top face in closed form. Gets the vertical gradient right (base dark, top
    // lit); can't see a neighbouring cloud's shadow, which is what Ultra's taps buy. Light
    // elevation is floored rather than allowed to graze, since the true slant path at sunrise
    // runs to infinity.
    float slantUp = max(abs(lightDir.y), 0.15);
    float above = deck.depth * (1.0 - clamp((pos.y - deck.base) / max(deck.depth, 1e-3), 0.0, 1.0));
    return exp(-density * (deck.tau / max(deck.depth, 1e-3)) * (above / slantUp));
#else

    // Any vector not parallel to lightDir will do; the branch exists only because the sun passes
    // close to the zenith at noon and the obvious reference is world up.
    vec3 ref = abs(lightDir.y) < 0.99 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
    vec3 fan = normalize(cross(lightDir, ref));

    float optical = 0.0;
    float travelled = 0.0;
    float sunStep = deck.depth * PLAGUE_CLOUD_SUN_STEP;

    for (int i = 0; i < PLAGUE_CLOUD_SUN_TAPS; i++) {
        // Sampled at the MIDPOINT of its own segment: with doubling steps, end-sampling the first
        // segment is wrong by half the near field, where almost all the shadowing optical depth is.
        float mid = travelled + sunStep * 0.5;
        float side = (i & 1) == 0 ? 1.0 : -1.0;
        vec3 p = pos + lightDir * mid + fan * (side * mid * PLAGUE_CLOUD_SUN_CONE);
        optical += plagueCloudDensityCoarseIn(p, deck, drift) * sunStep;
        travelled += sunStep;
        sunStep *= PLAGUE_CLOUD_SUN_GROWTH;
    }

    float h = clamp((pos.y - deck.base) / max(deck.depth, 1e-3), 0.0, 1.0);
    float sunY = clamp(abs(lightDir.y), 0.0, 1.0);
    float pathToExit = deck.depth * (1.0 - h) / max(sunY, 0.15);
    float remaining = max(pathToExit - travelled, 0.0);
    float fanMean = optical / max(travelled, 1e-3);

    // Fitted against the seeded 128-step final-density holdout in tools/verify_clouds.py. The
    // 75% fan mean preserves measured nearby overburden while 25% source density avoids carrying
    // one displaced tap through the whole slab. Exact binary fractions bound the extrapolated
    // share from 1/32 at zenith to 1/8 at the horizon.
    float remainingRho = mix(density, fanMean, 0.75);
    float fitWeight = 0.03125 + 0.09375 * (1.0 - sunY);
    float opticalFit = optical + fitWeight * remainingRho * remaining;
    return exp(-opticalFit * deck.tau / max(deck.depth, 1e-3));
#endif
}

// ------------------------------------------------------------------------------------------------
// Aerial perspective
// ------------------------------------------------------------------------------------------------

/**
 * (1 - exp(-x)) / x, which is 1 at x = 0.
 *
 * Written as a series below the crossover rather than the bare ratio: the bare ratio is
 * catastrophic cancellation for small x, which is the ordinary case here (a level ray a few
 * thousand blocks long crosses almost none of an 8.5km scale height).
 */
float plagueCloudExpRatio(float x) {
    return abs(x) < 1e-2 ? 1.0 - 0.5 * x + x * x * (1.0 / 6.0) : (1.0 - exp(-x)) / x;
}

/**
 * Atmospheric transmittance over a FINITE segment of air, eye to a point `dist` away.
 *
 * Closed form for an exponential density profile: integral(0..d) exp(-(y0+t*up)/H) dt reduces to
 * d * exp(-y0/H) * plagueCloudExpRatio(d*up/H), agreeing with plagueAirColumn's own vertical
 * column as d -> infinity, up -> 1. No epsilon needed on `up`: at up = 0 the ratio is 1, the
 * correct level-path answer rather than a rescued one.
 *
 * Ozone is passed as zero, not omitted: its density is identically zero below 10km, and every
 * path this function is asked about runs from the camera to a cloud deck a few hundred blocks up.
 *
 * @param eyeY  camera altitude, absolute world Y, taken as metres. See the note in plagueGetClouds
 * @param rayUp the ray's Y component, unit length
 * @param dist  distance along the ray, blocks
 */
vec3 plagueCloudAirTransmittance(float eyeY, float rayUp, float dist) {
    float y0 = max(eyeY, 0.0);
    float d = max(dist, 0.0);

    float colAir = d * exp(-y0 / PLAGUE_SCALE_HEIGHT_AIR)
                 * plagueCloudExpRatio(d * rayUp / PLAGUE_SCALE_HEIGHT_AIR);
    float colHaze = d * exp(-y0 / PLAGUE_SCALE_HEIGHT_HAZE)
                  * plagueCloudExpRatio(d * rayUp / PLAGUE_SCALE_HEIGHT_HAZE);

    // Through atmosphere.glsl's own extinction coefficients, so a band-model change reaches
    // clouds without an edit here.
    return exp(-plagueAirExtinction(vec3(colAir * u_AirDensity,
                                         colHaze * u_AirTurbidity,
                                         0.0)));
}

// ------------------------------------------------------------------------------------------------
// The march
// ------------------------------------------------------------------------------------------------

/**
 * The low deck along one view ray, as PREMULTIPLIED vec4(rgb * a, a) in HDR linear.
 *
 * @param viewDir         unit view ray in world space
 * @param cameraPosAbs    ABSOLUTE camera position; the field is world-anchored, not camera-relative
 * @param terrainDistance distance to the opaque fragment, blocks; <=0 means no geometry (sky case)
 * @param cloudFrontDistance first density-bearing sample along the ray, strictly positive; 0 when
 *                           the ray is empty
 * @param dither          per-pixel 0..1 offset on the first sample, avoiding banded steps
 * @param sunDirTrue      the true sun direction, never the active light: keying off the active
 *                        body would build a noon sky at midnight
 * @param syncedTime      seconds since world start, for the drift
 *
 * Distances are world blocks, handed to atmosphere.glsl as metres (the convention every other
 * consumer of that file uses); plagueAirEyePos takes a raw camera Y. The genus table's own 0.192
 * blocks-per-metre compression is deliberately not applied to the air: it fits a 9km altitude
 * ladder into a 384-block build height and says nothing about how much air separates the decks.
 */
vec4 plagueGetClouds(vec3 viewDir, vec3 cameraPosAbs, float terrainDistance, float dither,
                     PlagueCloudDeck deck, PlagueSkyColors skyColours, PlagueLighting lighting,
                     vec3 sunDirTrue, float syncedTime, float renderDistance,
                     vec3 atmColorMult, out float cloudFrontDistance) {
    cloudFrontDistance = 0.0;
    // --- Geometry -------------------------------------------------------------------------------
    float slabTop = deck.base + deck.depth;

    // Horizon guard; see PLAGUE_CLOUD_RAY_EPSILON for the NaN this prevents.
    float dy = viewDir.y;
    float dySafe = abs(dy) < PLAGUE_CLOUD_RAY_EPSILON
                 ? (dy < 0.0 ? -PLAGUE_CLOUD_RAY_EPSILON : PLAGUE_CLOUD_RAY_EPSILON)
                 : dy;

    float tA = (deck.base - cameraPosAbs.y) / dySafe;
    float tB = (slabTop - cameraPosAbs.y) / dySafe;
    float tNear = max(min(tA, tB), 0.0);
    float tFar = max(tA, tB);

    // A flat slab has no horizon of its own (unbounded sideways), so one is borrowed from
    // atmosphere.glsl's planet: two heights above a sphere of radius R see each other out to
    // sqrt(2*R*h) summed over the two. Clamping the far intersection to the draw radius instead
    // (the obvious reading) deletes the deck below the elevation where it first climbs out of
    // that radius, a ~30px empty band across the sky bottom.
    float horizon = sqrt(2.0 * PLAGUE_PLANET_RADIUS * max(cameraPosAbs.y, 0.0))
                  + sqrt(2.0 * PLAGUE_PLANET_RADIUS * max(deck.base, 0.0));
    if (tNear > horizon) {
        return vec4(0.0);
    }

    // Clamped horizontally, not along the ray: a near-horizon ray stays inside the (192-block
    // thick, laterally unbounded) slab for kilometres, and a ray-length limit would clip a
    // downward view at the same distance as a level one. PLAGUE_CLOUD_DISTANCE matches the figure
    // tools/derive_cloud_types.py anchors its cell sizes against.
    float horizontal = max(length(viewDir.xz), PLAGUE_CLOUD_RAY_EPSILON);
    tFar = min(tFar, tNear + PLAGUE_CLOUD_DISTANCE / horizontal);

    if (terrainDistance > 0.0) {
        tFar = min(tFar, terrainDistance);
    }
    if (tFar <= tNear) {
        return vec4(0.0);
    }

    // --- Step sizing ----------------------------------------------------------------------------
    float span = tFar - tNear;
    // Cumulus depth at the current Cloud Size, the baseline PLAGUE_CLOUD_SLAB_STEPS is tuned for.
    // Match plagueCloudLowDeck's reference-relative vertical calibration.  The accepted default
    // therefore remains six Balanced slab steps despite recovering the table's full cumulus depth.
    float clearDepth = PLAGUE_CLOUD_CUMULUS_DEPTH * max(u_CloudScale, 0.05)
                     * PLAGUE_CLOUD_CUMULUS_VERTICAL_ASPECT;
    float slabSteps = float(PLAGUE_CLOUD_SLAB_STEPS)
                    * clamp(deck.depth / max(clearDepth, 1e-3), 1.0, PLAGUE_CLOUD_DEPTH_STEP_CAP);
    float stepLen = deck.depth / slabSteps;
    int steps = max(int(ceil(span / stepLen)), 1);

    // When the cap binds, the step grows rather than the ray truncating: truncating would draw a
    // hard moving edge at the cap's own bind distance, since the cap is a function of ray
    // direction. Stretching undersamples the near-horizon rays instead, whose clouds are
    // compressed into a few pixels anyway; the integration below is step-invariant, so this only
    // changes resolved detail, not cloud thickness.
    if (steps > PLAGUE_CLOUD_MAX_STEPS) {
        steps = PLAGUE_CLOUD_MAX_STEPS;
        stepLen = span / float(steps);
    }

    // --- Per-ray constants ----------------------------------------------------------------------
    vec2 drift = plagueCloudDrift(deck, syncedTime);
    float sigmaScale = deck.tau / max(deck.depth, 1e-3);

    // Moon sits opposite the true sun; the sign flips where sunVisibility2 reaches zero (sun 3.6
    // degrees below horizon). By then the direct term is already the night colour, two orders of
    // magnitude below the day one, so what jumps is the phase function on an already-negligible
    // term. Between the two flip points the deck is lit from below by a sun under the horizon: the
    // ordinary look of a lit cloud base at dusk.
    float lightSign = lighting.sunVisibility2 > 0.0 ? 1.0 : -1.0;
    vec3 lightDir = sunDirTrue * lightSign;
    float cosLight = clamp(dot(viewDir, lightDir), -1.0, 1.0);

    // Night uses plagueMoonColor rather than the authored `lighting.light` table: the two are
    // calibrated against each other by day (PLAGUE_SUN_LUMINANCE solved for it) but diverge at
    // night, where the authored table reads clouds darker than the sky behind them. Day and dusk
    // keep the authored table unchanged. The flip sits at the same sunVisibility2==0 boundary as
    // above, so it doesn't introduce a second discontinuity.
    vec3 directRadiance = lightSign > 0.0
            ? lighting.light
            : plagueMoonColor(plagueAirEyePos(cameraPosAbs.y), lightDir);

    // Hoisted since these depend only on the ray/light angle, constant along the ray. What's
    // left inside the march is just the transmittance power. Octave 0 carries the single-
    // scattering pair this file used before the multi-scattering correction landed
    // (msPhaseFwd[0]/msPhaseIso[0]).
    float msEnergy[PLAGUE_CLOUD_MS_OCTAVES];
    float msPhaseFwd[PLAGUE_CLOUD_MS_OCTAVES];
    float msPhaseIso[PLAGUE_CLOUD_MS_OCTAVES];
    {
        float a = 1.0;
        float c = 1.0;
        for (int n = 0; n < PLAGUE_CLOUD_MS_OCTAVES; n++) {
            msEnergy[n] = a;
            // Both lobes flatten together per octave; the blend further down (per-sample, on
            // light transmittance) is a different, separate question.
            // Compressing only one lobe leaves the raw multi lobe outswinging the bounded forward
            // one, so scattered() peaks at lightT 0.76 rather than 1.0: away from the light, a
            // half-shadowed sample outshines a fully lit one and the deck reads flat.
            float rawPhaseFwd = plagueCloudPhase(cosLight, PLAGUE_CLOUD_PHASE_FORWARD * c);
            float rawPhaseIso = plagueCloudPhase(cosLight, PLAGUE_CLOUD_PHASE_MULTI * c);
            msPhaseFwd[n] = mix(1.0, rawPhaseFwd, PLAGUE_CLOUD_PHASE_ANISOTROPY);
            msPhaseIso[n] = mix(1.0, rawPhaseIso, PLAGUE_CLOUD_PHASE_ANISOTROPY);
            a *= PLAGUE_CLOUD_MS_ENERGY;
            c *= PLAGUE_CLOUD_MS_PHASE;
        }
    }

    // Dark-edge correction for viewing a cloud's lit side (light scattered back out of the edge
    // reads darker than single scattering predicts); looking toward the light the same edge is
    // thin and bright, so the gate must flip. Linear in cosine, not a step, so it draws no seam.
    float powderGate = 0.5 - 0.5 * cosLight;

    // Evaluated once per ray: no per-sample direction to vary it by.
    vec3 ambientDome = plagueSkyHemisphere(skyColours, skyColours.lightUp);

    // Fraction of the sky dome a cloud's base sees through the gaps in this deck. No ground-bounce
    // term: this pass has no albedo signal to build one from.
    float ambientBase = 1.0 - deck.cover;

    // Reference length for the powder term: one erosion cell, the field's finest feature, read
    // through plagueCloudErosionCells so it tracks the Fast tier's coarsened cell size rather
    // than the nominal 8.
    float powderRef = deck.cell / plagueCloudErosionCells(deck);

    // --- Integration ----------------------------------------------------------------------------
    //
    // Analytic, not a running sum: each step is the closed-form integral over constant density,
    // so halving the step converges to the same opacity rather than doubling it. This is what
    // lets the quality tiers trade detail for cost without changing how thick a cloud looks, and
    // what lets the cap above stretch a grazing ray's step without banding the horizon. Verified
    // against a 4x step difference (Fast vs Ultra): mean alpha agrees to <1% at every elevation;
    // per-pixel variance grows toward the horizon as the cap-stretched rays legitimately resolve
    // less detail, not as the integration failing.
    float transmittance = 1.0;
    vec3 luminance = vec3(0.0);
    float distSum = 0.0;
    float weightSum = 0.0;

    float t = tNear + stepLen * dither;

    for (int i = 0; i < PLAGUE_CLOUD_MAX_STEPS; i++) {
        if (i >= steps || transmittance < PLAGUE_CLOUD_MIN_TRANSMITTANCE) {
            break;
        }

        vec3 pos = cameraPosAbs + viewDir * t;
        float density = plagueCloudDensityAt(pos, deck, drift);

        if (density > 0.0) {
            if (cloudFrontDistance <= 0.0) {
                cloudFrontDistance = max(t, PLAGUE_CLOUD_RAY_EPSILON);
            }
            float sigma = density * sigmaScale;
            float stepT = exp(-sigma * stepLen);
            float weight = transmittance * (1.0 - stepT);

            float h = clamp((pos.y - deck.base) / max(deck.depth, 1e-3), 0.0, 1.0);
            float lightT = plagueCloudLightTransmittance(pos, lightDir, deck, drift, density);

            // Blended on the light's own transmittance rather than a separate dial: where
            // directly lit, light hasn't scattered yet (forward lobe); deep inside, it's bounced
            // many times (near isotropic).
            float powder = 1.0 - exp(-2.0 * sigma * powderRef);

            // Sum over multiple-scattering octaves: each term is a further bounce order (less
            // energy, thinner-looking, flatter phase). Reduced-extinction transmittance is the
            // single-scattering value raised to that octave's power: a chain of sqrt() at
            // B=0.5, so free on top of the march.
            float scattered = 0.0;
            float lightTn = lightT;
            for (int n = 0; n < PLAGUE_CLOUD_MS_OCTAVES; n++) {
                // Uses this octave's own transmittance so a deep octave (sees the cloud as thin)
                // leans forward and a near octave leans isotropic.
                float phaseN = mix(msPhaseIso[n], msPhaseFwd[n], lightTn);
                scattered += msEnergy[n] * lightTn * phaseN;
                // B=0.5 extinction reduction as a running sqrt(); see the constants block.
                lightTn = sqrt(lightTn);
            }

            vec3 direct = directRadiance
                        * (scattered * mix(1.0, powder, powderGate * (1.0 - lightT)));
            float crownBackView = max(-cosLight, 0.0);
            float crownExposure = smoothstep(0.5 * PLAGUE_CLOUD_PARCEL_MIN_TOP,
                                             PLAGUE_CLOUD_PARCEL_MIN_TOP, h)
                                * lightT * lightT * crownBackView * crownBackView;
            // Relative gain on a directRadiance the weather has already dimmed, so it scales the
            // overcast palette rather than injecting clear-sky light into it. The term is also
            // self-attenuating under rain: lightT falls as the deck's tau grows, and the gate is
            // lightT squared.
            direct *= 1.0 + PLAGUE_CLOUD_CROWN_LIGHT_GAIN * crownExposure;
            // Fitted against the seeded 24-direction final-density hemisphere holdout in
            // tools/verify_clouds.py. This is local Beer visibility, not a surface normal: the
            // coloured sky dome remains the incident light and gains no texture/density lookup.
            float ambientVisibility = exp(-0.22 * density * deck.tau * (1.0 - h)
                                        * (1.0 - lightT));
            vec3 ambient = ambientDome * mix(ambientBase, 1.0, h) * ambientVisibility;

            luminance += weight * (direct + ambient);
            distSum += weight * t;
            weightSum += weight;
            transmittance *= stepT;
        }

        t += stepLen;
    }

    float alpha = 1.0 - transmittance;
    if (alpha <= 0.0) {
        return vec4(0.0);
    }

    // --- Aerial perspective ---------------------------------------------------------------------
    //
    // Applied once at the opacity-weighted mean sample distance: to first order this reproduces
    // the per-sample integral for the cost of one evaluation instead of one per sample.
    //
    // Fades toward plagueGetSky along this same ray (doGlow=true, doGround=false), the exact
    // pair fog.glsl's border term uses to make a terrain pixel at the render cutoff match the sky
    // beside it (tools/verify_fog.py asserts the two agree), so a cloud and the terrain under it
    // dissolve toward the same sky and don't seam.
    //
    // Air is entered through the same Weibull extinction and PLAGUE_FOG_DRIVE the terrain fog
    // uses, height-weighted along the slant path to the cloud, rather than the terrain's own
    // aerial term (too weak at the horizon) or the border-veil metric (a cloud past the render
    // cutoff read as dissolved mid-sky while nearer sky stayed clear). Deliberately not gated by
    // the fog-density slider alone: everything else the drive carries (distance, layer height,
    // rain, time-of-day) must reach this fade too, or a hazed hillside with a crisp cloud above
    // it reopens the same seam.
    float meanDist = weightSum > 0.0 ? distSum / weightSum : tNear;
    float VdotS = dot(viewDir, sunDirTrue);
    // Graded so the deck fades toward the same tinted sky fog.glsl's border term dissolves
    // terrain into, holding the seam closed under a non-identity atmColorMult too.
    vec3 skyAlong = plagueGetSky(skyColours, viewDir.y, VdotS, dither, true, false) * atmColorMult;

    PlagueFogDrive fogDrive = PLAGUE_FOG_DRIVE(lighting);
    float rainH = fogDrive.H * (1.0 + fogDrive.rainDepth * fogDrive.rain);
    float cloudAlt = cameraPosAbs.y + viewDir.y * meanDist;
    float pathDepth = meanDist * plagueFogPathWeight(cameraPosAbs.y, cloudAlt, rainH);
    float airOp = clamp(plagueFogAirOpacity(pathDepth, fogDrive, renderDistance),
                        0.0, 1.0);

    // Premultiplied throughout: `luminance` already carries the alpha, so the sky is premultiplied
    // by it before the mix.
    vec3 rgb = mix(luminance, skyAlong * alpha, airOp);
    return vec4(max(rgb, vec3(0.0)), alpha);
}

#else

// CLOUDS_VOLUMETRIC off: feature compiles away entirely; entry points survive as identities so
// callers don't need their own gate. Written out (not left to the caller) because
// gbuffer_resolve.fsh imports this file unconditionally to get the option declarations.

vec2 plagueCloudDrift(PlagueCloudDeck deck, float syncedTime) {
    return vec2(0.0);
}

float plagueCloudDensityAt(vec3 worldPos, PlagueCloudDeck deck, vec2 drift) {
    return 0.0;
}

float plagueCloudDensity(vec3 worldPos, PlagueCloudDeck deck, float syncedTime) {
    return 0.0;
}

vec4 plagueGetClouds(vec3 viewDir, vec3 cameraPosAbs, float terrainDistance, float dither,
                     PlagueCloudDeck deck, PlagueSkyColors skyColours, PlagueLighting lighting,
                     vec3 sunDirTrue, float syncedTime, float renderDistance,
                     vec3 atmColorMult, out float cloudFrontDistance) {
    cloudFrontDistance = 0.0;
    return vec4(0.0);
}

#endif // CLOUDS_VOLUMETRIC

#endif // PLAGUE_CLOUDS
