#ifndef PLAGUE_CLOUD_TYPES
#define PLAGUE_CLOUD_TYPES

// The seven cloud genera as a table, generated by tools/derive_cloud_types.py from the WMO
// International Cloud Atlas and standard water-path/effective-radius tables via
// tau = 3 WP / (2 rho r_eff). Do not hand-edit the pasted block below; re-run the script instead.
//
// All seven rows exist now so the mid and high decks are table lookups when they land; only
// cumulus is resolved today. `convective` (below the table) is authored, not derived.

// --- Options ----------------------------------------------------------------------------------
//
// Import only from a fullscreen pass, via clouds.glsl: these two options reach the shader through
// u_PackOptions, which a deferred geometry program never receives.

// Offset from the game's own cloud altitude (see plagueCloudEngineBase), not an absolute world Y,
// so a mod that moves vanilla's cloud layer is respected rather than overridden. Default 192.0
// equals PLAGUE_CLOUD_CUMULUS_BASE, so the offset is zero on an unmodded install. Applied as a
// shift (plagueCloudLowDeckShift) rather than an assignment, to keep the low etage's genera at
// their relative altitudes once more than cumulus is resolved.
#define u_CloudAltitude 192.0 //[96.0..384.0 step 4.0] runtime "Cloud Altitude"

// Multiplier on the genus's own published coverage, spent on the region field (which map areas
// have weather) rather than the cell threshold: thresholding one fractal field harder only shrinks
// its blobs, it doesn't reduce their count. Measured mean cloud chord fell 181->98 blocks under the
// old single-field approach across this slider's range; splitting the demand between two fields
// (see PLAGUE_CLOUD_REGION_DENSITY) holds that drift to 214->239, 11% instead of 85%.
#define u_CloudAmount 1.0 //[0.00..2.00 step 0.05] runtime "Cloud Amount"

// Multiple of the genus's own derived cell size; the one slider that departs from the physics on
// purpose. Physically-sized cumulus (1.0) subtend ~45 degrees overhead and read as weather systems,
// not a "nice day" sky; 0.30 gives the small-puff look this pack ships by default.
//
// Scales cell and depth together, not cell alone: scaling width only inverts the genus's aspect
// ratio (a narrow column reading as fog) and desynchronises the march step, erosion and coverage
// fields from the shrinking cloud, which measurably degraded ray-march sampling density at small
// scale. Scaling both keeps the row's aspect ratio and holds march sampling density constant with
// cloud size.
//
// `tau` (optical depth) is deliberately not scaled with it: geometric similarity would fade the
// deck out as it shrinks, which is a second, unwanted departure from physics bundled into this one
// slider. The slab's opacity is held at the row's own figure regardless of size.
//
// Floor of 0.20 is set by clouds.glsl's traversal step cap, not by cloud/erosion size ratio.
#define u_CloudScale 0.30 //[0.20..2.00 step 0.05] runtime "Cloud Size"

// --- One resolved deck --------------------------------------------------------------------------

/**
 * One genus, resolved for this instant. Six fields are table rows; `convective` is authored (see
 * below); the last three are solved on-the-fly so nothing downstream can threshold with a number
 * that doesn't deliver what it claims.
 *
 * Two coverages at two scales: `cover` is the genus's whole-sky figure; `localCover` is coverage
 * inside a region that already has weather in it (higher), and is what an individual cloud's size
 * is set by. `regionCut` and `cut` are the field thresholds that deliver each.
 */
struct PlagueCloudDeck {
    float base;        // absolute world Y of the slab's underside, blocks
    float depth;        // slab thickness, blocks
    float cell;        // horizontal size of one lump, blocks
    float shear;        // along-wind stretch, dimensionless; 1.0 is isotropic
    float tau;         // optical depth straight down through the whole slab, dimensionless
    float cover;        // fraction of the whole plane the deck occupies, 0..1
    float convective;   // height-profile selector: 0 flat stratiform sheet, 1 deep convective tower
    float localCover;   // fraction of a cloudy region the deck occupies, 0..1; see REGION_DENSITY
    float cut;          // cell-field threshold delivering `localCover`; see plagueCloudCutoff
    float regionCut;    // region-field threshold; see plagueCloudRegionCutoff
};

// Traversal cap, blocks, horizontal. tools/derive_cloud_types.py checks its genus cell sizes
// against this so no cell fills the whole drawn region; the march's own visual horizon (from
// atmosphere.glsl's planet radius) is larger, so this bound is conservative, not wrong.
const float PLAGUE_CLOUD_DISTANCE = 4000.0;

// --- paste from tools/derive_cloud_types.py -----------------------------------------------------

// Cirrus, high deck, ice
const float PLAGUE_CLOUD_CIRRUS_BASE        =   1728.00;   // 9000 m
const float PLAGUE_CLOUD_CIRRUS_DEPTH       =    288.00;   // 1500 m
const float PLAGUE_CLOUD_CIRRUS_CELL        =    384.00;   // 2000 m
const float PLAGUE_CLOUD_CIRRUS_TAU         =    0.5000;
const float PLAGUE_CLOUD_CIRRUS_SHEAR       =    6.0000;
const float PLAGUE_CLOUD_CIRRUS_COVER       =    0.2500;   // 2 oktas

// Cirrocumulus, high deck, ice
const float PLAGUE_CLOUD_CIRROCUMULUS_BASE  =   1344.00;   // 7000 m
const float PLAGUE_CLOUD_CIRROCUMULUS_DEPTH =     76.80;   // 400 m
const float PLAGUE_CLOUD_CIRROCUMULUS_CELL  =     17.06;   // 89 m
const float PLAGUE_CLOUD_CIRROCUMULUS_TAU   =    1.8000;
const float PLAGUE_CLOUD_CIRROCUMULUS_SHEAR =    1.2000;
const float PLAGUE_CLOUD_CIRROCUMULUS_COVER =    0.3750;   // 3 oktas

// Altocumulus, mid deck, water
const float PLAGUE_CLOUD_ALTOCUMULUS_BASE   =    768.00;   // 4000 m
const float PLAGUE_CLOUD_ALTOCUMULUS_DEPTH  =    115.20;   // 600 m
const float PLAGUE_CLOUD_ALTOCUMULUS_CELL   =     61.15;   // 318 m
const float PLAGUE_CLOUD_ALTOCUMULUS_TAU    =    7.5000;
const float PLAGUE_CLOUD_ALTOCUMULUS_SHEAR  =    2.0000;
const float PLAGUE_CLOUD_ALTOCUMULUS_COVER  =    0.5000;   // 4 oktas

// Cumulus, low deck, water
const float PLAGUE_CLOUD_CUMULUS_BASE       =    192.00;   // 1000 m
const float PLAGUE_CLOUD_CUMULUS_DEPTH      =     76.80;   // 400 m
const float PLAGUE_CLOUD_CUMULUS_CELL       =    192.00;   // 1000 m
const float PLAGUE_CLOUD_CUMULUS_TAU        =    9.0000;
const float PLAGUE_CLOUD_CUMULUS_SHEAR      =    1.1000;
const float PLAGUE_CLOUD_CUMULUS_COVER      =    0.3750;   // 3 oktas

// Stratocumulus, low deck, water
const float PLAGUE_CLOUD_STRATOCUMULUS_BASE =    153.60;   // 800 m
const float PLAGUE_CLOUD_STRATOCUMULUS_DEPTH=    115.20;   // 600 m
const float PLAGUE_CLOUD_STRATOCUMULUS_CELL =    384.00;   // 2000 m
const float PLAGUE_CLOUD_STRATOCUMULUS_TAU  =   22.5000;
const float PLAGUE_CLOUD_STRATOCUMULUS_SHEAR=    2.5000;
const float PLAGUE_CLOUD_STRATOCUMULUS_COVER=    0.7500;   // 6 oktas

// Stratus, low deck, water
const float PLAGUE_CLOUD_STRATUS_BASE       =     57.60;   // 300 m
const float PLAGUE_CLOUD_STRATUS_DEPTH      =     76.80;   // 400 m
const float PLAGUE_CLOUD_STRATUS_CELL       =    960.00;   // 5000 m
const float PLAGUE_CLOUD_STRATUS_TAU        =   18.7500;
const float PLAGUE_CLOUD_STRATUS_SHEAR      =    1.0000;
const float PLAGUE_CLOUD_STRATUS_COVER      =    1.0000;   // 8 oktas

// Cumulonimbus, low deck, water
const float PLAGUE_CLOUD_CUMULONIMBUS_BASE  =    153.60;   // 800 m
const float PLAGUE_CLOUD_CUMULONIMBUS_DEPTH =   1920.00;   // 10000 m
const float PLAGUE_CLOUD_CUMULONIMBUS_CELL  =   1536.00;   // 8000 m
const float PLAGUE_CLOUD_CUMULONIMBUS_TAU   =   90.0000;
const float PLAGUE_CLOUD_CUMULONIMBUS_SHEAR =    4.0000;
const float PLAGUE_CLOUD_CUMULONIMBUS_COVER =    0.6250;   // 5 oktas

// --- end of the derived block -------------------------------------------------------------------

// Authored: the derivation script has no source for this axis. Selects the height-profile shape,
// 0 = flat stratiform sheet, 1 = tower narrow at the base and rounding off at top, i.e. how much of
// the genus's silhouette a rising parcel made versus a layer condensing in place.
const float PLAGUE_CLOUD_CIRRUS_CONVECTIVE        = 0.00;  // ice fall-streaks laid along the shear;
                                                           // no updraught shapes it at all
const float PLAGUE_CLOUD_CIRROCUMULUS_CONVECTIVE  = 0.35;  // genuinely cellular, the WMO names it by
                                                           // its granulation, but only 400 m deep,
                                                           // so no tower ever develops
const float PLAGUE_CLOUD_ALTOCUMULUS_CONVECTIVE   = 0.40;  // the same cellular sheet one etage down
                                                           // and half again as deep
const float PLAGUE_CLOUD_CUMULUS_CONVECTIVE       = 1.00;  // the reference convective genus: a flat
                                                           // base and a cauliflower top is its
                                                           // definition, and the low deck is built
                                                           // to draw exactly that
const float PLAGUE_CLOUD_STRATOCUMULUS_CONVECTIVE = 0.30;  // rolls and mounds that convect under an
                                                           // inversion; the lid is what flattens the
                                                           // top, so the shape is mostly sheet
const float PLAGUE_CLOUD_STRATUS_CONVECTIVE       = 0.00;  // fog lifted off the ground, the
                                                           // stratiform end of the axis by
                                                           // definition, and the reason 0 exists
const float PLAGUE_CLOUD_CUMULONIMBUS_CONVECTIVE  = 1.00;  // the deepest convection there is; its
                                                           // anvil comes from the table's own shear
                                                           // of 4.0, not from this axis

// --- Turning a coverage fraction into a threshold -----------------------------------------------
//
// plagueSkyFbm's output is nowhere near uniform on 0..1 (octave averaging pulls it toward the
// mean); the threshold that delivers a stated coverage has to be solved against its actual
// distribution, not guessed. Measured at this file's octave count, 4M samples over a 6000-cell
// square: mean 0.50002, sigma 0.13191, close enough to Gaussian to invert with a probit.
const float PLAGUE_CLOUD_FIELD_MEAN  = 0.50002;
const float PLAGUE_CLOUD_FIELD_SIGMA = 0.13191;
// Remap ceiling: field's measured max is 0.9438 over 4M samples, so normalising against 1.0 would
// mean no column ever saturates. The top 0.1% saturates instead.
const float PLAGUE_CLOUD_FIELD_TOP   = 0.85000;
// Threshold for "no weather here": 1.0 is above the field's measured max (0.9443), so an empty
// column is exact rather than a few surviving specks. Depends on the field's octave count staying
// at 4 (max rises to 0.9728 at 3 octaves, 0.9954 at 2) and would need re-measuring if that
// changes.
const float PLAGUE_CLOUD_FIELD_CLOSED = 1.0;

/**
 * Standard normal upper-tail quantile (x with P(X > x) = p). Abramowitz & Stegun 26.2.23, rational
 * approximation in sqrt(-2 ln p), absolute error bound 4.5e-4.
 *
 * Clamped to [1e-4, 0.5] so cover = 0 lands on a finite threshold above the field's max rather than
 * an asymptote.
 */
float plagueNormalUpperQuantile(float p) {
    float q = clamp(min(p, 1.0 - p), 1e-4, 0.5);
    float t = sqrt(-2.0 * log(q));
    float num = 2.515517 + t * (0.802853 + t * 0.010328);
    float den = 1.0 + t * (1.432788 + t * (0.189269 + t * 0.001308));
    float x = t - num / den;
    return p > 0.5 ? -x : x;
}

/**
 * Coverage-field threshold that delivers a given sky coverage. Measured against the 4-octave field,
 * worst error 1.5 percentage points (the field's departure from Gaussian, not the quantile bound).
 *
 * @param cover coverage to deliver: once more than the low deck resolves, this is the deck's
 *              `localCover`, not `cover` (see below).
 */
float plagueCloudCutoff(float cover) {
    return PLAGUE_CLOUD_FIELD_MEAN
         + PLAGUE_CLOUD_FIELD_SIGMA * plagueNormalUpperQuantile(clamp(cover, 0.0, 1.0));
}

// --- The region field: which parts of the map have weather in them at all -----------------------
//
// Two independently-thresholded fractal fields, not one: thresholding a single field harder for
// less coverage also shrinks every surviving cloud, since only a peak clears a raised bar. Follows
// Schneider & Vos, SIGGRAPH 2015: a low-frequency weather field gating whether a region is cloudy,
// a cell-scale field shaping the cloud inside it.
//
// The coverage figure is split between them: within an active region the genus covers
// PLAGUE_CLOUD_REGION_DENSITY times its whole-sky average; the rest of the demand buys region area.
// The product reproduces `cover` at any slider position. Once region area saturates, only local
// density can still grow, and the two fields collapse back into the single-field case.
const float PLAGUE_CLOUD_REGION_DENSITY = 1.5;

// Region field's own distribution, measured at the octave count clouds.glsl samples it with (wider
// than the 4-octave cell field, as fewer octaves pulls less toward the mean): 3 octaves, 4M samples,
// mean 0.49997, sigma 0.14048.
const float PLAGUE_CLOUD_WEATHER_MEAN  = 0.49997;
const float PLAGUE_CLOUD_WEATHER_SIGMA = 0.14048;

// Soft-edge half-width, in sigma. Not taste: measured so the region mask crosses 0.02->0.98 over
// 447 blocks (2.3 cumulus cells), keeping a weather boundary at least two clouds thick rather than
// a hard line.
const float PLAGUE_CLOUD_WEATHER_BAND = 0.35;

// Correction for the soft edge, subtracted from the threshold. The cell field's response through
// the crossing is steeply convex (half the mask delivers a sixteenth of the cloud, not half), so a
// region solved for area alone comes out short; 0.15 sigma of extra area puts delivered coverage
// back on target (worst error 0.012, against 0.015 for the single-field construction it replaced).
const float PLAGUE_CLOUD_WEATHER_BIAS = 0.15;

/**
 * Region-field threshold delivering a given fraction of the map, biased for the soft edge.
 * Deliberately over-delivers area (bias buying back what the soft edge costs); the number that has
 * to land correctly is the coverage the two fields produce together, not either field's area alone.
 */
float plagueCloudRegionCutoff(float regionFraction) {
    return PLAGUE_CLOUD_WEATHER_MEAN
         + PLAGUE_CLOUD_WEATHER_SIGMA * (plagueNormalUpperQuantile(clamp(regionFraction, 0.0, 1.0))
                                         - PLAGUE_CLOUD_WEATHER_BIAS);
}

/**
 * How far u_CloudAltitude moves the low deck from the table's placement, blocks.
 *
 * A shift, not an assignment: the low etage's four genera sit at four different published
 * altitudes, and assigning the slider to `base` would flatten them onto one plane once the driver
 * blends between them. Zero at the default, since the slider's default equals cumulus's own base.
 */
float plagueCloudLowDeckShift() {
    return u_CloudAltitude - PLAGUE_CLOUD_CUMULUS_BASE;
}

/**
 * The game's own cloud altitude, world blocks: what the low deck is measured from.
 *
 * Reads u_CameraSkyLight.w, vanilla's cloudHeight argument captured by the engine at the moment it
 * cancels vanilla's cloud pass, so it reflects whatever mod last changed it, with no need to know
 * which mod that was. Falls back to the table's own cumulus base when the lane reads 0 (before any
 * cloud pass has registered, and in dimensions that never draw clouds), since 0.0 taken literally
 * would put the deck below bedrock. Branches rather than max(), because a mod is free to set a cloud
 * height below this fallback and max() would refuse to follow it down.
 *
 * The mid/high decks will scale proportionally from this base, not take their table altitudes
 * directly, so cumulus can never end up above cirrus on a raised install.
 */
float plagueCloudEngineBase() {
    return u_CameraSkyLight.w > 0.0 ? u_CameraSkyLight.w : PLAGUE_CLOUD_CUMULUS_BASE;
}

// Precipitation kinds, for the driver signature below. Named rather than numbered at the call site,
// so that adding a third cannot silently renumber a comparison somebody wrote as a literal.
const int PLAGUE_PRECIP_NONE = 0;
const int PLAGUE_PRECIP_RAIN = 1;
const int PLAGUE_PRECIP_SNOW = 2;

/**
 * The low deck, resolved for this instant. Currently returns cumulus unconditionally; a later pass
 * replaces this body with the weather driver. The full driver signature is taken now, with the
 * unused half accepted and ignored, so landing the driver is an edit to this function only, not to
 * every call site (including the cloud-shadow site in the resolve, the one nobody remembers).
 *
 * @param rainFactor     u_SkyState.x, 0..1. Will drive cover up and the genus toward stratus.
 * @param thunderFactor  0..1. The only path to cumulonimbus.
 * @param wetness        smoothed surface-wetness state, 0..1. Will lag rainFactor.
 * @param precipitation  PLAGUE_PRECIP_*. Snow forms under a shallower, flatter deck than rain.
 * @param sunElevation   sin(sun elevation), u_SunDirection.w. Will drive diurnal convection.
 * @param worldTime      world clock, seconds. Will drive the slow weather walk.
 */
PlagueCloudDeck plagueCloudLowDeck(float rainFactor, float thunderFactor, float wetness,
                                   int precipitation, float sunElevation, float worldTime) {
    PlagueCloudDeck deck;

    // See u_CloudScale: both dimensions scale together; tau does not.
    float scale     = max(u_CloudScale, 0.05);
    deck.depth      = PLAGUE_CLOUD_CUMULUS_DEPTH * scale;
    deck.cell       = PLAGUE_CLOUD_CUMULUS_CELL * scale;
    deck.shear      = PLAGUE_CLOUD_CUMULUS_SHEAR;
    deck.tau        = PLAGUE_CLOUD_CUMULUS_TAU;
    deck.convective = PLAGUE_CLOUD_CUMULUS_CONVECTIVE;

    // Shift, not assignment: see plagueCloudLowDeckShift.
    deck.base = plagueCloudEngineBase() + plagueCloudLowDeckShift();

    deck.cover = clamp(PLAGUE_CLOUD_CUMULUS_COVER * max(u_CloudAmount, 0.0), 0.0, 1.0);

    // rowLocal reads off the genus row, not `cover`, so cloud size doesn't change as the slider
    // moves. max() is the saturating arm: once the region is fully covered, further coverage has to
    // raise localCover instead. See PLAGUE_CLOUD_REGION_DENSITY.
    float rowLocal   = min(PLAGUE_CLOUD_CUMULUS_COVER * PLAGUE_CLOUD_REGION_DENSITY, 1.0);
    deck.localCover  = max(rowLocal, deck.cover);
    // 1e-3 floor: avoids a divide-by-zero at zero coverage; unreachable otherwise since localCover
    // is always >= the row's cover.
    float regionArea = min(deck.cover / max(deck.localCover, 1e-3), 1.0);

    // Solved here, not cached, so both cutoffs stay in lockstep with `cover` as it starts moving.
    deck.cut       = plagueCloudCutoff(deck.localCover);
    deck.regionCut = plagueCloudRegionCutoff(regionArea);

    return deck;
}

#endif // PLAGUE_CLOUD_TYPES
