#ifndef PLAGUE_CLOUDS
#define PLAGUE_CLOUDS

// Composited over the pack's fog terms (see the tail of plagueGetClouds): a cloud is in the air
// fog describes, and skipping this splits the sky into two atmospheres at the horizon.
//
// Deliberately imports fog_options/fog_model, not fog.glsl itself: that pulls in the whole
// underwater chain and broke live once the option merge saw the enlarged declaration set.
#moj_import <fornax_runtime:fog_options.glsl>
#moj_import <fornax_runtime:fog_model.glsl>

// Density is coverage * heightProfile(genus) * erosion, kept as separate factors because the
// weather driver moves them independently per genus and state; see cloud_density.glsl. Cloud
// Amount moves the direct coverage cutoff; height profile shapes the genus silhouette; erosion
// frays the edges only. Genus table (cloud_types.glsl, generated by tools/derive_cloud_types.py)
// supplies every figure this file consumes.
//
// Construction: Schneider & Vos, "The Real-Time Volumetric Cloudscapes of Horizon Zero Dawn"
// (SIGGRAPH 2015 Advances in Real-Time Rendering course): two-scale weather field and the
// powder term below.
//
// Single-scattering only; no multiple-scattering model here (see PLAGUE_CLOUD_MS_* below).

#moj_import <fornax_runtime:sky_hash.glsl>
#moj_import <fornax_runtime:precip_field.glsl>
#moj_import <fornax_runtime:cloud_types.glsl>
#moj_import <fornax_runtime:light_and_ambient_colors.glsl>
#moj_import <fornax_runtime:sky.glsl>
// Named directly though sky.glsl already pulls it in: the march reads plagueMoonColor and
// plagueAirEyePos and should say where they come from rather than inherit them transitively.
#moj_import <fornax_runtime:atmosphere.glsl>
// Unconditional, same as gbuffer_resolve.fsh: under PLAGUE_SKY_MODEL == 0 the branches below that
// read it are compiled away, but the include itself (and any PLAGUE_ATMO_READS_* the caller
// defined before importing this file) must still be present.
#moj_import <fornax_runtime:atmo_lut.glsl>

// ------------------------------------------------------------------------------------------------
// Options
// ------------------------------------------------------------------------------------------------
//
// Import only from a fullscreen pass: the runtime option below and cloud_types.glsl's two arrive
// via u_PackOptions, which deferred geometry programs never receive.

// Read by name by the engine to cancel vanilla clouds (GraphRunner.packOwnsClouds) and by
// graph.toml to gate every cloud target/pass: an engine contract, not just a pack option.
#define CLOUDS_VOLUMETRIC 1 //[0 1] compile "Volumetric Clouds" {0="Off" 1="On"}

// March resolution, and only that: 0.25, 0.5, 0.75 of the screen, one target pair each, which is
// why graph.toml partitions on `== 0`, `== 1` and `== 2`. Step budget is per deck, on u_CloudTier*.
//
// Global because it cannot be otherwise: all seven genera march into one target and the pass sorts
// them per ray by first-hit distance, so a per-deck resolution loses the ordering that puts a near
// tower in front of far cirrus.
//
// At a quarter, clouds_composite's 4-tap box spans four destination pixels and leaves the march's
// per-pixel variance as 4x4 blocks.
#define CLOUD_RESOLUTION 1 //[0 1 2] compile "Cloud Resolution" {0="Quarter" 1="Half" 2="Three Quarter"}

// Multiple of the derived wind speed below; 0 freezes the deck for screenshots/bisection. Top of
// range moves a cumulus cell past the viewer in about a quarter in-game hour, a squall line on
// purpose.
#define u_CloudSpeed 1.0 //[0.00..4.00 step 0.05] runtime "Cloud Speed"

// Scales the phase function's swing, both lobes. 1 is a 7.8x ratio between facing the light and
// facing away; 0 is isotropic. Coverage carries no light term, so this cannot resize a cloud, only
// brighten thin edges past visibility: 13% of apparent area across the range.
#define u_CloudSilverLining 1.0 //[0.00..1.00 step 0.05] runtime "Cloud Silver Lining"

// Shadow depth, as a multiple of the deck's own tau. 0 leaves the ground unshadowed.
#define u_CloudShadowStrength 1.0 //[0.00..2.00 step 0.05] runtime "Cloud Shadow Strength"

// Ceiling on the sun ray's slant, 1/sin(elevation). Uncapped it belongs to a slab that never ends:
// 29x optical depth at 2 degrees, which crushes everything under cloud to black. A cloud is finite
// and the ray leaves it out the side. 3 holds the path at 19 degrees.
const float PLAGUE_CLOUD_SHADOW_MAX_SLANT = 3.0;


// ------------------------------------------------------------------------------------------------
// The noise hook
// ------------------------------------------------------------------------------------------------
//
// Each consuming pass supplies the sampler as a macro, since an include cannot declare a sampler
// uniform and have two passes bind it at two different input slots:
//
//     #define PLAGUE_CLOUD_NOISE_3D(uvw) texture(u_InputN, uvw)
//     #define PLAGUE_CLOUD_DETAIL_3D(uvw) texture(u_InputN, uvw)
//     #moj_import <fornax_runtime:clouds.glsl>
//
// The #define must precede this import: it expands inside the functions below, so importing
// first uses the uniform before its own declaration. Not threaded as a function parameter
// (contrast aurora.glsl) because the density function is called from two different nesting
// depths, and a threaded sampler there is how the two ends up sampling different textures.
//
// PLAGUE_CLOUD_NOISE_3D/PLAGUE_CLOUD_DETAIL_3D are the real 3D Worley volumes (see
// tools/generate_cloud_noise.py) the coverage/erosion fields sample directly. Only a compute pass
// can bind a real sampler3D, since Vulkan's fullscreen-pipeline shader-reflection step refuses any
// non-2D/Cube sampler outright, so the direct-view march (shaders/compute/clouds_march_volume.comp)
// is a compute pass and defines these as real texture() calls. gbuffer_resolve.fsh's cloud-shadow
// query and water_environment.fsh's reflection imposter are both fullscreen passes: for those two
// the macro is instead an ALU approximation (plagueSkyFbm, the same primitive the field's warp
// already uses), the same cheap-field-for-a-cheap-consumer pattern plagueCloudDensityCoarseIn uses
// for the sun march. Never a bare constant, which would flatten shadow/reflection density to a
// uniform wash with no spatial structure at all.
#if CLOUDS_VOLUMETRIC
#ifndef PLAGUE_CLOUD_NOISE_3D
#error clouds.glsl needs PLAGUE_CLOUD_NOISE_3D(uvw) defined before the import. See the noise-hook contract at the top of this file.
#endif
#ifndef PLAGUE_CLOUD_DETAIL_3D
#error clouds.glsl needs PLAGUE_CLOUD_DETAIL_3D(uvw) defined before the import. See the noise-hook contract at the top of this file.
#endif
#endif

// ------------------------------------------------------------------------------------------------
// Quality tiers
// ------------------------------------------------------------------------------------------------
//
// Slab steps: vertical samples through the deck. Cap: max samples before the step must stretch (a
// near-horizon ray hits it almost immediately; a vertical ray never does).
//
// Each step integrates the closed-form density-over-segment analytically, so halving the count
// converges to the same total opacity rather than thinning it: undersampling costs per-pixel
// variance (absorbed by dither + temporal resolve), not a dimmer sky.
//
// Sun taps: self-shadowing march cost, which runs per lit sample so it scales with cloud coverage.
//
// All three are per deck, on u_CloudTier* (plagueCloudTierSlabSteps / StepCap / SunTaps in
// cloud_types.glsl). CLOUD_RESOLUTION owns march resolution, which cannot go per deck.
//
// Compile-time here is only the loop ceiling, at the largest cap any tier asks for. The live
// per-ray count is stepCap, a variable, always <= this.
#define PLAGUE_CLOUD_MAX_STEPS  64

// Step count multiplier ceiling for a deck deeper than clear sky. Bounds a tall storm deck to
// 3x the tier's own step count.
// Marched layers: convective, low sheet, precipitating, stratocumulus, altocumulus,
// cirrocumulus, cirrus. Each is gated on its own presence, so an empty genus costs nothing
// beyond building its deck.
#define PLAGUE_CLOUD_LAYERS 7

const float PLAGUE_CLOUD_DEPTH_STEP_CAP = 3.0;

// Floor on the samples taken through a deck's own thickness. Below four the interior is resolved by
// too few planes and the dither turns the gaps into rays radiating from the layer's vanishing point.
// stepScale can buy budget back, but not past this.
const float PLAGUE_CLOUD_MIN_SLAB_STEPS = 4.0;

// Distance over which a deck's step budget halves, blocks: one mip level per 16 chunks. A deck's
// features subtend an angle that falls with distance, so the budget follows the same curve a mip
// chain does rather than a gentler one. PLAGUE_CLOUD_MIN_SLAB_STEPS is the floor underneath it.
const float PLAGUE_CLOUD_QUALITY_HALVING = 256.0;

// Ends of u_CloudDetailFade's range, in chunks. The top is the off sentinel and must equal the
// slider's declared maximum, or off becomes unreachable.
const float PLAGUE_CLOUD_DETAIL_FADE_MIN = 8.0;
const float PLAGUE_CLOUD_DETAIL_FADE_OFF = 128.0;
const float PLAGUE_CLOUD_BLOCKS_PER_CHUNK = 16.0;

// Last-to-first step ratio once the budget stops covering the span. 16 holds the first step under a
// uniform slab crossing on every tier at the 4000-block worst case: 22.7/38.4, 11.4/12.8, 5.8/6.4.
const float PLAGUE_CLOUD_STEP_RANGE = 16.0;

// ------------------------------------------------------------------------------------------------
// Constants
// ------------------------------------------------------------------------------------------------

// Integer lattice direction, not a unit vector, deliberately: (11,-4) is within 0.03 degrees of
// the westerlies bearing the genus table's WMO bands assume, and being integer lets the drift
// wrap land on a lattice boundary at every fbm octave (see PLAGUE_CLOUD_DRIFT_WRAP).
const vec2 PLAGUE_CLOUD_WIND = vec2(11.0, -4.0);
const float PLAGUE_CLOUD_WIND_LENGTH = 11.7046999107;   // sqrt(137)
const vec2 PLAGUE_CLOUD_WIND_UNIT = PLAGUE_CLOUD_WIND / PLAGUE_CLOUD_WIND_LENGTH;

// 1.92 blocks/s: a fair-weather cumulus drifts near its own base speed (~10 m/s, temperate
// mid-latitudes), and tools/derive_cloud_types.py's 0.192 blocks/metre scale gives 10 m/s here.
// Cross-check: a 192-block cumulus cell is then replaced by its neighbour in ~2 in-game hours.
const float PLAGUE_CLOUD_WIND_SPEED = 1.92;

// Wraps the drift after 1000 steps to avoid the fp32 clock trap: syncedTime is unwrapped seconds,
// so on a long-lived world the drift term grows until it swallows the per-pixel spatial offset's
// low bits and floor() collapses whole regions into one cell.
//
// 1000 * PLAGUE_CLOUD_WIND is divisible by 125 = 5^3, which keeps the jump integral through all
// four coverage octaves (plagueSkyFbm's per-octave (2/5)^k lattice transform), so the wrap
// introduces no seam: the field becomes a different field, not a torn one. At default speed the
// wrap fires only after roughly 325 hours of continuous world time.
const float PLAGUE_CLOUD_DRIFT_WRAP = 1000.0;

// Eight fixed reference cells per domain-warp cycle: measured as the broadest bend that breaks the
// volume tile's exact repeat without visibly distorting one cloud silhouette. With the 57.6-block
// reference cell this is a 460.8-block warp cycle at every Cloud Size.
const float PLAGUE_CLOUD_WEATHER_CLOUDS = 8.0;

// Domain-warp amplitude, in cell units, plagueCloudSampleCoord applies before the 3D noise volumes
// are sampled: breaks their exact one-cell periodicity, which Moires under perspective at grazing
// view angles (a radiating fan of light/dark rays; see plagueCloudSampleCoord's own comment for the
// full mechanism). Authored: 1.0 (up to half a cell of drift at full swing) keeps one cloud's own
// silhouette undistorted; retune against a render if a future genus's smaller cell makes the warp
// read as shimmer up close.
const float PLAGUE_CLOUD_WARP_STRENGTH = 1.0;

// Floor on the remap denominator: at coverage 0 the solved cutoff exceeds the field's measured
// maximum and the span goes non-positive, so this keeps the division defined (the clamped result
// is an empty sky either way).
const float PLAGUE_CLOUD_MIN_SPAN = 0.05;

// Interpolated per-genus between a sheet value and a tower value on `family`. Solved against
// the drawn silhouette (cross-section width by height) rather than chosen: 0.06/0.45 keeps the
// tower base flat and wide with just enough rim curl to read as an edge, not a cut. The asymmetry
// (flat base, rounded top) is what reads as a cumulus rather than a lens or smoke. Sheet's two
// edges sit inside the tower's, just enough to keep the march from aliasing a hard face.
const float PLAGUE_CLOUD_SHEET_BASE = 0.04;
const float PLAGUE_CLOUD_SHEET_TOP  = 0.92;
const float PLAGUE_CLOUD_TOWER_BASE = 0.06;
const float PLAGUE_CLOUD_TOWER_TOP  = 0.45;

// Ceiling on erosion cells per coverage cell / slab depth: 8, since a cumulus turret is roughly a
// tenth of its cloud. Applied per axis against the slab's own dimensions so every genus gets the
// same cell count through its own thickness regardless of blocks. The march's actual value,
// plagueCloudErosionCells, lowers this wherever 8 would undersample the finest octave below the
// march's own step (binds at the Fast tier).
const float PLAGUE_CLOUD_EROSION_CELLS = 8.0;

// 2.17, not 2.0: an exact doubling re-aligns every second lattice line of the two erosion octaves
// and prints a visible cross-hatch. Offset is three coprime integers so the octaves never share a
// texture slice.
const float PLAGUE_CLOUD_EROSION_LACUNARITY = 2.17;
const vec3 PLAGUE_CLOUD_EROSION_OFFSET = vec3(37.0, 11.0, 53.0);

// Erosion is weighted by s(1-s)^2 in shaped density s (zero at s=0 and s=1, so it neither erodes
// past the solved coverage cutoff nor eats a dense core down to static). PEAK = 27/4 =
// 1/max(s(1-s)^2), normalising the weight to peak at 1. STRENGTH = 1/3 is the largest value for
// which erosion cannot punch a hole above the weight's own peak (from (1/3)(27/4)s(1-s)^2 <= s,
// i.e. s >= 1/3).
const float PLAGUE_CLOUD_EROSION_PEAK = 6.75;
const float PLAGUE_CLOUD_EROSION_STRENGTH = 0.33333333;

// Forward: Mie asymmetry of a cloud-droplet distribution in visible light, ~0.85 (Hansen & Travis
// 1974, "Light scattering in planetary atmospheres"), taken as published.
// Multi: authored stand-in for the isotropised multiply-scattered field; -0.20 is mild enough to
// stay near-isotropic while still separating front-lit from side-lit faces.
const float PLAGUE_CLOUD_PHASE_FORWARD = 0.85;
const float PLAGUE_CLOUD_PHASE_MULTI = -0.20;

// Authored against paired noon-above and below-near-sun captures: retaining 10% of the raw
// droplet anisotropy keeps the two-octave forward/back response inside 2x-12x while mixing with
// the unit spherical mean preserves phase energy and avoids a near-sun HDR spike.
const float PLAGUE_CLOUD_PHASE_ANISOTROPY = 0.10;

// Authored against the noon-above acceptance capture after phase compression: a fully sun-visible
// upper crown needs one additional copy of its bounded direct term to read white. Height starts
// halfway to the field's minimum parcel top, while squared light/view gates leave lower bodies,
// occluded interiors, side views and the near-sun forward lobe at or near identity.
const float PLAGUE_CLOUD_CROWN_LIGHT_GAIN = 1.0;

// Shortwave albedo of the surface under the deck. Between vegetated land (~0.2) and open water
// (~0.06) for a mixed coastal view. Sets how grey a cloud base reads; 0 restores gap-lit bases.
const float PLAGUE_CLOUD_GROUND_ALBEDO = 0.15;

// Multiple-scattering correction (Wrenninge, Kulla & Lombardi, "Art-Directable Multiple
// Volumetric Scattering", SIGGRAPH 2013 Talks): approximates the multiply-scattered field as a
// sum of single-scattering evaluations at reduced extinction, energy and phase asymmetry per
// order of scattering:
//
//     L ~= sum over n of  A^n * S(sigma * B^n, phase with g * C^n)
//
// Needed because single scattering under-predicts a thick cloud's brightness (a real cumulus,
// albedo 0.6-0.9, is bright from many internal bounces the direct term alone can't produce).
//
// A = ENERGY = 0.5, C = PHASE = 0.5 are the paper's published values. Two octaves, not three:
// geometric in A, so the third carries only 14% of the correction for a third of its cost.
// B (extinction reduction) is also 0.5 but isn't a constant here: the march computes
// transmittance^(B^n) as a chain of sqrt() (two per lit sample) rather than pow() calls.
const int   PLAGUE_CLOUD_MS_OCTAVES = 2;
const float PLAGUE_CLOUD_MS_ENERGY  = 0.5;   // A, energy surviving each further bounce
const float PLAGUE_CLOUD_MS_PHASE   = 0.5;   // C, how much of the forward bias it remembers

// Tier-counted taps at geometrically growing spacing: fine near the sample (where most shadowing
// optical depth is), cheap farther away. The unsampled path is closed analytically below, so each
// tier retains its existing one/two/three density lookups without treating the short fan as the
// whole light ray.
//
// Cone is lateral spread per unit distance, alternating side to side, not the solar disc (0.27
// degrees, pointless to sample), but the neighbourhood whose material actually shades this
// sample. 0.15 puts the last tap ~40 blocks off-axis, into the neighbouring cumulus cell.
const float PLAGUE_CLOUD_SUN_STEP = 0.06;
const float PLAGUE_CLOUD_SUN_GROWTH = 2.0;
const float PLAGUE_CLOUD_SUN_CONE = 0.15;

// Fraction of the unsampled light path the analytic tail charges. Family-scaled because `taps` IS
// the quality tier: a weight blind to the measured path length makes the tier an exposure control,
// one dropdown moving sky luminance 23% across Fast/Balanced/Ultra. tools/derive_cloud_lighting.py,
// minimising tier spread subject to per-deck accuracy over seven decks: spread 0.049, accuracy
// 0.050. Floor of the method: remainingRho comes from the fan, already outside a lumpy cloud, so
// cumulus holds ~0.10 error at any weight.
const float PLAGUE_CLOUD_REMAINDER_WEIGHT         = 0.1750;
const float PLAGUE_CLOUD_REMAINDER_FAMILY_OCTAVES = 0.5000;

// Sky and ground visibility use a sample's OWN density as proxy for the column past it, only as
// good as the deck's vertical coherence: under a sheet the column matches the sample, inside a
// tower the neighbouring air is clear and the same coefficient buries it. deck.family is that axis
// (0 stratiform, 1 cumulus, 2 storm). tools/derive_cloud_lighting.py, minimax against the
// 24-direction hemisphere reference over the seven low-etage decks: worst deviation 1.46x, against
// 8.09x for one shared coefficient, 3.9x too bright on a rain sheet, 6.9x too dark in cumulonimbus.
const float PLAGUE_CLOUD_AMBIENT_COHERENCE      = 0.7257;
const float PLAGUE_CLOUD_AMBIENT_FAMILY_OCTAVES = 2.0000;   // a factor of four per unit of family

// Break threshold: one part in 256, the finest step an 8-bit display carries. The remaining
// transmittance stays in alpha rather than zeroing, so the composite is continuous through the
// threshold rather than stepping at it.
const float PLAGUE_CLOUD_MIN_TRANSMITTANCE = 0.0039;

// Sign-preserving floor on |viewDir.y|, not an early return: a level ray divides to infinity
// against the slab planes and the inf-minus-inf NaN survives every downstream max/mix/clamp,
// painting a white horizon band with no error. An early return would instead draw a one-pixel
// seam at the horizon. The value is small enough to be inert: the slab intersection lands ~2M
// blocks out, well past the deck's own horizon cutoff.
const float PLAGUE_CLOUD_RAY_EPSILON = 1e-4;

#if CLOUDS_VOLUMETRIC

#moj_import <fornax_runtime:cloud_density.glsl>

// ------------------------------------------------------------------------------------------------
// Scattering
// ------------------------------------------------------------------------------------------------

/**
 * Cornette-Shanks phase function, normalised so an isotropic scatterer returns exactly 1
 * (Cornette & Shanks 1992, "Physically reasonable analytic expression for the single-scattering
 * phase function"; the published 3/(8*pi) form times 4*pi, so the value reads directly as "how
 * many times more light goes this way than an isotropic scatterer would send").
 *
 * @param cosTheta cosine of the angle between the view ray and the direction TOWARD the light
 * @param g        asymmetry: positive forward, negative backward, 0 gives the Rayleigh shape
 */
float plagueCloudPhase(float cosTheta, float g) {
    float g2 = g * g;
    float d = 1.0 + g2 - 2.0 * g * cosTheta;
    // Guards a caller passing |g| = 1 (d's true minimum is 0.0225 at the forward lobe's own g).
    return 1.5 * (1.0 - g2) * (1.0 + cosTheta * cosTheta)
         / ((2.0 + g2) * max(d * sqrt(d), 1e-4));
}

/**
 * Light reaching this sample: the existing short fan toward the light plus a bounded analytic
 * estimate of the path the fan cannot afford to sample, then Beer-Lambert on the combined optical
 * depth. Shades a cloud by density between it and the sun rather than by height alone.
 *
 * @param lightDir unit vector toward the active body: the sun by day, the moon by night
 */
float plagueCloudLightTransmittance(vec3 pos, vec3 lightDir, PlagueCloudDeck deck, vec2 drift,
                                    float density) {
    // Tap counts are per deck and floored at one, so there is no zero-tap analytic arm.

    // Any vector not parallel to lightDir will do; the branch exists only because the sun passes
    // close to the zenith at noon and the obvious reference is world up.
    vec3 ref = abs(lightDir.y) < 0.99 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
    vec3 fan = normalize(cross(lightDir, ref));

    float optical = 0.0;
    float travelled = 0.0;
    float sunStep = deck.depth * PLAGUE_CLOUD_SUN_STEP;

    // Taps ride the group's budget too. Floored at one so every deck still measures its own near
    // field, where most of the shadowing optical depth is. The analytic tail below reads
    // `travelled`, so a shorter fan is absorbed rather than lost.
    int taps = max(plagueCloudTierSunTaps(deck.tier), 1);
    for (int i = 0; i < taps; i++) {
        // Sampled at the MIDPOINT of its own segment: with doubling steps, end-sampling the first
        // segment is wrong by half the near field, where almost all the shadowing optical depth is.
        float mid = travelled + sunStep * 0.5;
        float side = (i & 1) == 0 ? 1.0 : -1.0;
        vec3 p = pos + lightDir * mid + fan * (side * mid * PLAGUE_CLOUD_SUN_CONE);
        optical += plagueCloudDensityCoarseIn(p, deck, drift) * sunStep;
        travelled += sunStep;
        sunStep *= PLAGUE_CLOUD_SUN_GROWTH;
    }

    float h = clamp((pos.y - deck.base) / max(deck.depth, 1e-3), 0.0, 1.0);
    float sunY = clamp(abs(lightDir.y), 0.0, 1.0);
    float pathToExit = deck.depth * (1.0 - h) / max(sunY, 0.15);
    float remaining = max(pathToExit - travelled, 0.0);
    float fanMean = optical / max(travelled, 1e-3);

    // 75% fan mean preserves measured nearby overburden while 25% source density avoids carrying
    // one displaced tap through the whole slab. Fitted against the seeded 128-step final-density
    // holdout in tools/verify_clouds.py.
    float remainingRho = mix(density, fanMean, 0.75);
    float fitWeight = PLAGUE_CLOUD_REMAINDER_WEIGHT
                    * exp2(-PLAGUE_CLOUD_REMAINDER_FAMILY_OCTAVES * deck.family);
    float opticalFit = optical + fitWeight * remainingRho * remaining;
    return exp(-opticalFit * deck.tau / max(deck.depth, 1e-3));
}

// ------------------------------------------------------------------------------------------------
// Aerial perspective
// ------------------------------------------------------------------------------------------------

/**
 * (1 - exp(-x)) / x, which is 1 at x = 0.
 *
 * Written as a series below the crossover rather than the bare ratio: the bare ratio is
 * catastrophic cancellation for small x, which is the ordinary case here (a level ray a few
 * thousand blocks long crosses almost none of an 8.5km scale height).
 */
float plagueCloudExpRatio(float x) {
    return abs(x) < 1e-2 ? 1.0 - 0.5 * x + x * x * (1.0 / 6.0) : (1.0 - exp(-x)) / x;
}

/**
 * Atmospheric transmittance over a FINITE segment of air, eye to a point `dist` away.
 *
 * Closed form for an exponential density profile: integral(0..d) exp(-(y0+t*up)/H) dt reduces to
 * d * exp(-y0/H) * plagueCloudExpRatio(d*up/H), agreeing with plagueAirColumn's own vertical
 * column as d -> infinity, up -> 1. No epsilon needed on `up`: at up = 0 the ratio is 1, the
 * correct level-path answer rather than a rescued one.
 *
 * Ozone is passed as zero, not omitted: its density is identically zero below 10km, and every
 * path this function is asked about runs from the camera to a cloud deck a few hundred blocks up.
 *
 * @param eyeY  camera altitude, absolute world Y, taken as metres. See the note in plagueGetClouds
 * @param rayUp the ray's Y component, unit length
 * @param dist  distance along the ray, blocks
 */
vec3 plagueCloudAirTransmittance(float eyeY, float rayUp, float dist) {
    float y0 = max(eyeY, 0.0);
    float d = max(dist, 0.0);

    float colAir = d * exp(-y0 / PLAGUE_SCALE_HEIGHT_AIR)
                 * plagueCloudExpRatio(d * rayUp / PLAGUE_SCALE_HEIGHT_AIR);
    float colHaze = d * exp(-y0 / PLAGUE_SCALE_HEIGHT_HAZE)
                  * plagueCloudExpRatio(d * rayUp / PLAGUE_SCALE_HEIGHT_HAZE);

    // Through atmosphere.glsl's own extinction coefficients, so a band-model change reaches
    // clouds without an edit here.
    return exp(-plagueAirExtinction(vec3(colAir * u_AirDensity,
                                         colHaze * u_AirTurbidity,
                                         0.0)));
}

// ------------------------------------------------------------------------------------------------
// The march
// ------------------------------------------------------------------------------------------------

/**
 * The low deck along one view ray, as PREMULTIPLIED vec4(rgb * a, a) in HDR linear.
 *
 * @param viewDir         unit view ray in world space
 * @param cameraPosAbs    ABSOLUTE camera position; the field is world-anchored, not camera-relative
 * @param terrainDistance distance to the opaque fragment, blocks; <=0 means no geometry (sky case)
 * @param cloudFrontDistance first density-bearing sample along the ray, strictly positive; 0 when
 *                           the ray is empty
 * @param dither          per-pixel 0..1 offset on the first sample, avoiding banded steps
 * @param ambientDome     the sky's cosine-weighted hemisphere average, already graded
 * @param skyAlong        what this ray dissolves into at the render cutoff, already graded by
 *                        atmColorMult and (under the scattering sky) plagueWarmSkyBand
 * @param sunDirTrue      the true sun direction, never the active light: keying off the active
 *                        body would build a noon sky at midnight
 * @param syncedTime      seconds since world start, for the drift
 *
 * Distances are world blocks, handed to atmosphere.glsl as metres (the convention every other
 * consumer of that file uses); plagueAirEyePos takes a raw camera Y. The genus table's own 0.192
 * blocks-per-metre compression is deliberately not applied to the air: it fits a 9km altitude
 * ladder into a 384-block build height and says nothing about how much air separates the decks.
 *
 * Low-level entry: the caller has already decided where the sky comes from. The overload below
 * takes a PlagueSkyColors and an atmColorMult instead, and builds these two from the palette:
 * every existing caller (clouds_march.fsh, and clouds_march_volume.comp under
 * PLAGUE_SKY_MODEL == 0) keeps using that one unchanged. clouds_march_volume.comp calls this one
 * directly under PLAGUE_SKY_MODEL == 1, with both read from atmo_lut.glsl instead.
 */
vec4 plagueGetClouds(vec3 viewDir, vec3 cameraPosAbs, float terrainDistance, float dither,
                     PlagueCloudDeck deck, vec3 ambientDome, vec3 skyAlong, PlagueLighting lighting,
                     vec3 sunDirTrue, float syncedTime, float renderDistance,
                     out float cloudFrontDistance) {
    cloudFrontDistance = 0.0;
    // --- Geometry -------------------------------------------------------------------------------
    float slabTop = deck.base + deck.depth;

    // Horizon guard; see PLAGUE_CLOUD_RAY_EPSILON for the NaN this prevents.
    float dy = viewDir.y;
    float dySafe = abs(dy) < PLAGUE_CLOUD_RAY_EPSILON
                 ? (dy < 0.0 ? -PLAGUE_CLOUD_RAY_EPSILON : PLAGUE_CLOUD_RAY_EPSILON)
                 : dy;

    float tA = (deck.base - cameraPosAbs.y) / dySafe;
    float tB = (slabTop - cameraPosAbs.y) / dySafe;
    float tNear = max(min(tA, tB), 0.0);
    float tFar = max(tA, tB);

    // A flat slab has no horizon of its own (unbounded sideways), so one is borrowed from
    // atmosphere.glsl's planet: two heights above a sphere of radius R see each other out to
    // sqrt(2*R*h) summed over the two. Clamping the far intersection to the draw radius instead
    // (the obvious reading) deletes the deck below the elevation where it first climbs out of
    // that radius, a ~30px empty band across the sky bottom.
    float horizon = sqrt(2.0 * PLAGUE_PLANET_RADIUS * max(cameraPosAbs.y, 0.0))
                  + sqrt(2.0 * PLAGUE_PLANET_RADIUS * max(deck.base, 0.0));
    if (tNear > horizon) {
        return vec4(0.0);
    }

    // Clamped horizontally, not along the ray: a near-horizon ray stays inside the (192-block
    // thick, laterally unbounded) slab for kilometres, and a ray-length limit would clip a
    // downward view at the same distance as a level one. PLAGUE_CLOUD_DISTANCE matches the figure
    // tools/derive_cloud_types.py anchors its cell sizes against.
    float horizontal = max(length(viewDir.xz), PLAGUE_CLOUD_RAY_EPSILON);
    tFar = min(tFar, tNear + PLAGUE_CLOUD_DISTANCE / horizontal);

    if (terrainDistance > 0.0) {
        tFar = min(tFar, terrainDistance);
    }
    if (tFar <= tNear) {
        return vec4(0.0);
    }

    // --- Step sizing ----------------------------------------------------------------------------
    float span = tFar - tNear;
    // Cumulus depth at the current Cloud Size, the tier's own slab-step count is tuned for.
    // Match plagueCloudLowDeck's reference-relative vertical calibration.  The accepted default
    // therefore remains six Balanced slab steps despite recovering the table's full cumulus depth.
    float clearDepth = PLAGUE_CLOUD_CUMULUS_DEPTH * max(u_CloudScale, 0.05)
                     * PLAGUE_CLOUD_CUMULUS_VERTICAL_ASPECT;
    // stepScale below 1 buys back the budget a thin deck does not need. A cirrus slab is 288
    // blocks deep against cumulus's 76.8, so the depth ratio alone would spend three times the
    // steps on a layer of optical depth 0.5 that has almost no interior to resolve.
    float slabSteps = plagueCloudTierSlabSteps(deck.tier)
                    * clamp(deck.depth / max(clearDepth, 1e-3), 1.0, PLAGUE_CLOUD_DEPTH_STEP_CAP)
                    * clamp(deck.stepScale, 0.05, 1.0);
    // A mip level per 16 chunks: quality follows where the viewer is relative to THIS deck, not a
    // global setting. Standing under the low deck the high etage is several halvings away; fly up
    // into it and it earns its budget back as it approaches.
    //
    // Distance to the SLAB, not to its mid-height, and zero once inside it. Cumulonimbus is 1920
    // blocks deep, so its mid sits 1051 blocks above a viewer standing under a base only 91 blocks
    // overhead: measuring to the mid drops the storm filling the whole sky to the step floor, and
    // at that few steps the per-frame dither resamples different planes each frame and the cloud
    // visibly restructures rather than drifting.
    float deckDistance = max(max(deck.base - cameraPosAbs.y,
                                 cameraPosAbs.y - (deck.base + deck.depth)), 0.0);
    float deckQuality = exp2(-deckDistance / PLAGUE_CLOUD_QUALITY_HALVING);

    // The ray's own horizontal reach. The vertical term above cannot see that a deck 30 blocks
    // overhead still runs kilometres sideways. Measured before the cap, so it is the span the ray
    // would cover.
    //
    // Skipped entirely at the top of the slider. A reach term has iso-lines at constant elevation,
    // which are circles on the dome, so any residual strength draws rings.
    //
    // Distance to where the ray ENTERS the deck, not the horizontal extent it covers inside one.
    // `span * horizontal` scales with deck thickness: a 1920-block cumulonimbus reaches ~3300 blocks
    // at 30 degrees elevation, driving deckQuality to 0.009 and engaging both floors across the
    // whole visible sky, which is the MIN_SLAB comment's radiating rays. Entry distance is immune to
    // thickness, so one setting means the same under cumulus and under a storm. Measured at eye Y
    // 63, Cloud Size 0.30, fade 32: slab steps unpin from the floor at 5.75 degrees against 64.25,
    // and stepCap at 25.75 degrees is 38 against its floor of 8.
    float fadeChunks = clamp(u_CloudDetailFade, PLAGUE_CLOUD_DETAIL_FADE_MIN,
                             PLAGUE_CLOUD_DETAIL_FADE_OFF);
    if (fadeChunks < PLAGUE_CLOUD_DETAIL_FADE_OFF) {
        float reach = tNear * horizontal;
        deckQuality *= exp2(-reach / (fadeChunks * PLAGUE_CLOUD_BLOCKS_PER_CHUNK));
    }

    // The player's budget for this deck's group. The floors below keep the lowest setting a
    // coarser deck rather than a missing one.
    slabSteps *= deckQuality;
    slabSteps = max(slabSteps, PLAGUE_CLOUD_MIN_SLAB_STEPS);
    float stepLen = deck.depth / slabSteps;
    // The cap, not the slab budget, is what a long ray actually spends: a shallow ray reaches it
    // whatever the step length, so scaling slabSteps alone leaves the cost untouched. Quality
    // therefore lowers the ceiling too, floored so a distant deck still resolves.
    // Dithered, not truncated. deckQuality is continuous but the cap is an integer, so a plain
    // int() steps down at a fixed elevation, drawing one ring per integer crossed. The ray's dither
    // turns each boundary into per-pixel noise. slabSteps stays continuous and needs no such fix.
    int stepCap = max(int(plagueCloudTierStepCap(deck.tier) * deckQuality + dither),
                      int(PLAGUE_CLOUD_MIN_SLAB_STEPS) * 2);

    int steps = max(int(ceil(span / stepLen)), 1);

    // When the cap binds the step grows rather than the ray truncating, since the cap is a function
    // of ray direction and truncating would draw a hard moving edge at its bind distance. Growth is
    // geometric, not one stretched uniform step: a camera inside the slab puts tNear at 0, so one
    // ray carries both a near cloud and the horizon band, and a uniform step across that applies a
    // whole step of extinction at one sample's density. Front-loading keeps the near field at the
    // slab's own resolution and spends the coarseness on distance.
    float stepGrowth = 1.0;
    if (steps > stepCap) {
        steps = stepCap;
        stepGrowth = pow(PLAGUE_CLOUD_STEP_RANGE, 1.0 / float(steps - 1));
        // Normalised so the series sums to the span exactly.
        stepLen = span * (stepGrowth - 1.0) / (pow(stepGrowth, float(steps)) - 1.0);
    }

    // --- Per-ray constants ----------------------------------------------------------------------
    vec2 drift = plagueCloudDrift(deck, syncedTime);
    float sigmaScale = deck.tau / max(deck.depth, 1e-3);

    // Biome dryness read where the CLOUD is, not where the camera is. The precipitation clipmap is
    // a per-column field over a 512-block window, so the ray samples it at its own crossing of the
    // deck's mid-height. Reading it at the camera instead makes the whole dome follow the player: a
    // step across a border repaints cloud hundreds of blocks away, which is what this replaces.
    //
    // Once per ray, not per step. The field is constant over a 4-block cell and a cloud spans far
    // more than that, so a per-sample read would buy nothing for 128x the lookups.
    if (deck.biomeResponse > 0.0) {
        float midHeight = deck.base + deck.depth * 0.5;
        float toMid = (midHeight - cameraPosAbs.y) / (abs(viewDir.y) < 1e-3 ? 1e-3 : viewDir.y);
        if (toMid > 0.0) {
            // Clamped into the window, not gated on it. Each deck's ray leaves the 512-block
            // square at its own distance, and gating dropped the aridity term along that edge: a
            // 45% extinction step on a straight line, one per deck. Clamping lets a far column
            // inherit the nearest one the field knows.
            vec2 columnXZ = plaguePrecipClampColumn(cameraPosAbs.xz + viewDir.xz * toMid,
                                                    cameraPosAbs.xz);
            float aridHere;
            float coldHere;
            if (plaguePrecipNeighbourhood(columnXZ, aridHere, coldHere)) {
                sigmaScale *= 1.0 - deck.biomeResponse * aridHere;
            }
        }
    }

    // Moon sits opposite the true sun; the sign flips where sunVisibility2 reaches zero (sun 3.6
    // degrees below horizon). By then the direct term is already the night colour, two orders of
    // magnitude below the day one, so what jumps is the phase function on an already-negligible
    // term. Between the two flip points the deck is lit from below by a sun under the horizon: the
    // ordinary look of a lit cloud base at dusk.
    float lightSign = lighting.sunVisibility2 > 0.0 ? 1.0 : -1.0;
    vec3 lightDir = sunDirTrue * lightSign;
    float cosLight = clamp(dot(viewDir, lightDir), -1.0, 1.0);

    // Night uses plagueMoonColor rather than the authored `lighting.light` table: the two are
    // calibrated against each other by day (PLAGUE_SUN_LUMINANCE solved for it) but diverge at
    // night, where the authored table reads clouds darker than the sky behind them. Day and dusk
    // keep the authored table unchanged. The flip sits at the same sunVisibility2==0 boundary as
    // above, so it doesn't introduce a second discontinuity.
    vec3 directRadiance = lightSign > 0.0
            ? lighting.light
            : plagueMoonColor(plagueAirEyePos(cameraPosAbs.y), lightDir);

    // Hoisted since these depend only on the ray/light angle, constant along the ray. What's
    // left inside the march is just the transmittance power. Octave 0 carries the single-
    // scattering pair this file used before the multi-scattering correction landed
    // (msPhaseFwd[0]/msPhaseIso[0]).
    float msEnergy[PLAGUE_CLOUD_MS_OCTAVES];
    float msPhaseFwd[PLAGUE_CLOUD_MS_OCTAVES];
    float msPhaseIso[PLAGUE_CLOUD_MS_OCTAVES];
    {
        float a = 1.0;
        float c = 1.0;
        for (int n = 0; n < PLAGUE_CLOUD_MS_OCTAVES; n++) {
            msEnergy[n] = a;
            // Both lobes flatten together per octave; the blend further down (per-sample, on
            // light transmittance) is a different, separate question.
            // Compressing only one lobe leaves the raw multi lobe outswinging the bounded forward
            // one, so scattered() peaks at lightT 0.76 rather than 1.0: away from the light, a
            // half-shadowed sample outshines a fully lit one and the deck reads flat.
            float rawPhaseFwd = plagueCloudPhase(cosLight, PLAGUE_CLOUD_PHASE_FORWARD * c);
            float rawPhaseIso = plagueCloudPhase(cosLight, PLAGUE_CLOUD_PHASE_MULTI * c);
            float anisotropy = PLAGUE_CLOUD_PHASE_ANISOTROPY
                             * clamp(u_CloudSilverLining, 0.0, 1.0);
            msPhaseFwd[n] = mix(1.0, rawPhaseFwd, anisotropy);
            msPhaseIso[n] = mix(1.0, rawPhaseIso, anisotropy);
            a *= PLAGUE_CLOUD_MS_ENERGY;
            c *= PLAGUE_CLOUD_MS_PHASE;
        }
    }

    // Dark-edge correction for viewing a cloud's lit side (light scattered back out of the edge
    // reads darker than single scattering predicts); looking toward the light the same edge is
    // thin and bright, so the gate must flip. Linear in cosine, not a step, so it draws no seam.
    float powderGate = 0.5 - 0.5 * cosLight;

    // Fraction of the sky dome a cloud's base sees through the gaps in this deck.
    float ambientBase = 1.0 - deck.cover;

    // The rest of what a base sees: sun and skylight off the surface below. Without it a grazing
    // ray under a closed deck reads near-black. lightDir, not skyColours.lightUp, since the latter
    // is the true sun and would zero the bounce against a moon directRadiance.
    vec3 groundBounce = PLAGUE_CLOUD_GROUND_ALBEDO
                      * (directRadiance * max(lightDir.y, 0.0) + ambientDome);

    // Reference length for the powder term: one erosion cell, the field's finest feature, read
    // through plagueCloudErosionCells so it tracks the Fast tier's coarsened cell size rather
    // than the nominal 8.
    float powderRef = deck.cell / plagueCloudErosionCells(deck);

    // --- Integration ----------------------------------------------------------------------------
    //
    // Analytic, not a running sum: each step is the closed-form integral over constant density,
    // so halving the step converges to the same opacity rather than doubling it. This is what
    // lets the quality tiers trade detail for cost without changing how thick a cloud looks, and
    // what lets the cap above stretch a grazing ray's step without banding the horizon. Verified
    // against a 4x step difference (Fast vs Ultra): mean alpha agrees to <1% at every elevation;
    // per-pixel variance grows toward the horizon as the cap-stretched rays legitimately resolve
    // less detail, not as the integration failing.
    float transmittance = 1.0;
    vec3 luminance = vec3(0.0);
    float distSum = 0.0;
    float weightSum = 0.0;

    float t = tNear + stepLen * dither;

    for (int i = 0; i < PLAGUE_CLOUD_MAX_STEPS; i++) {
        if (i >= steps || transmittance < PLAGUE_CLOUD_MIN_TRANSMITTANCE) {
            break;
        }

        vec3 pos = cameraPosAbs + viewDir * t;
        float density = plagueCloudDensityAt(pos, deck, drift);

        if (density > 0.0) {
            if (cloudFrontDistance <= 0.0) {
                cloudFrontDistance = max(t, PLAGUE_CLOUD_RAY_EPSILON);
            }
            float sigma = density * sigmaScale;
            float stepT = exp(-sigma * stepLen);
            float weight = transmittance * (1.0 - stepT);

            float h = clamp((pos.y - deck.base) / max(deck.depth, 1e-3), 0.0, 1.0);
            float lightT = plagueCloudLightTransmittance(pos, lightDir, deck, drift, density);

            // Blended on the light's own transmittance rather than a separate dial: where
            // directly lit, light hasn't scattered yet (forward lobe); deep inside, it's bounced
            // many times (near isotropic).
            float powder = 1.0 - exp(-2.0 * sigma * powderRef);

            // Sum over multiple-scattering octaves: each term is a further bounce order (less
            // energy, thinner-looking, flatter phase). Reduced-extinction transmittance is the
            // single-scattering value raised to that octave's power: a chain of sqrt() at
            // B=0.5, so free on top of the march.
            float scattered = 0.0;
            float lightTn = lightT;
            for (int n = 0; n < PLAGUE_CLOUD_MS_OCTAVES; n++) {
                // Uses this octave's own transmittance so a deep octave (sees the cloud as thin)
                // leans forward and a near octave leans isotropic.
                float phaseN = mix(msPhaseIso[n], msPhaseFwd[n], lightTn);
                scattered += msEnergy[n] * lightTn * phaseN;
                // B=0.5 extinction reduction as a running sqrt(); see the constants block.
                lightTn = sqrt(lightTn);
            }

            vec3 direct = directRadiance
                        * (scattered * mix(1.0, powder, powderGate * (1.0 - lightT)));
            float crownBackView = max(-cosLight, 0.0);
            float crownExposure = smoothstep(0.5 * PLAGUE_CLOUD_PARCEL_MIN_TOP,
                                             PLAGUE_CLOUD_PARCEL_MIN_TOP, h)
                                * lightT * lightT * crownBackView * crownBackView;
            // Relative gain on a directRadiance the weather has already dimmed, so it scales the
            // overcast palette rather than injecting clear-sky light into it. The term is also
            // self-attenuating under rain: lightT falls as the deck's tau grows, and the gate is
            // lightT squared.
            direct *= 1.0 + PLAGUE_CLOUD_CROWN_LIGHT_GAIN * crownExposure;
            // Local Beer visibility, not a surface normal: the coloured sky dome remains the
            // incident light and gains no texture/density lookup. Family scaling of the
            // coefficient: see PLAGUE_CLOUD_AMBIENT_COHERENCE.
            float overburden = PLAGUE_CLOUD_AMBIENT_COHERENCE
                             * exp2(-PLAGUE_CLOUD_AMBIENT_FAMILY_OCTAVES * deck.family)
                             * density * deck.tau * (1.0 - lightT);
            float ambientVisibility = exp(-overburden * (1.0 - h));
            // Same Beer visibility, depth mirrored: the sky dome is buried by cloud above a
            // sample, the ground by cloud below it.
            float bounceVisibility = exp(-overburden * h);
            vec3 ambient = ambientDome * mix(ambientBase, 1.0, h) * ambientVisibility
                         + groundBounce * bounceVisibility;

            luminance += weight * (direct + ambient);
            distSum += weight * t;
            weightSum += weight;
            transmittance *= stepT;
        }

        t += stepLen;
        stepLen *= stepGrowth;
    }

    float alpha = 1.0 - transmittance;
    if (alpha <= 0.0) {
        return vec4(0.0);
    }

    // --- Aerial perspective ---------------------------------------------------------------------
    //
    // Applied once at the opacity-weighted mean sample distance: to first order this reproduces
    // the per-sample integral for the cost of one evaluation instead of one per sample.
    //
    // Fades toward plagueGetSky along this same ray (doGlow=true, doGround=false), the exact
    // pair fog.glsl's border term uses to make a terrain pixel at the render cutoff match the sky
    // beside it (tools/verify_fog.py asserts the two agree), so a cloud and the terrain under it
    // dissolve toward the same sky and don't seam.
    //
    // Air is entered through the same Weibull extinction and PLAGUE_FOG_DRIVE the terrain fog
    // uses, height-weighted along the slant path to the cloud, rather than the terrain's own
    // aerial term (too weak at the horizon) or the border-veil metric (a cloud past the render
    // cutoff read as dissolved mid-sky while nearer sky stayed clear). Deliberately not gated by
    // the fog-density slider alone: everything else the drive carries (distance, layer height,
    // rain, time-of-day) must reach this fade too, or a hazed hillside with a crisp cloud above
    // it reopens the same seam.
    float meanDist = weightSum > 0.0 ? distSum / weightSum : tNear;

    PlagueFogDrive fogDrive = PLAGUE_FOG_DRIVE(lighting);
    float rainH = fogDrive.H * (1.0 + fogDrive.rainDepth * fogDrive.rain);
    float cloudAlt = cameraPosAbs.y + viewDir.y * meanDist;
    float pathDepth = meanDist * plagueFogPathWeight(cameraPosAbs.y, cloudAlt, rainH);
    float airOp = clamp(plagueFogAirOpacity(pathDepth, fogDrive, renderDistance),
                        0.0, 1.0);

    // Premultiplied throughout: `luminance` already carries the alpha, so the sky is premultiplied
    // by it before the mix.
    vec3 rgb = mix(luminance, skyAlong * alpha, airOp);
    return vec4(max(rgb, vec3(0.0)), alpha);
}

/**
 * The palette overload: builds ambientDome and skyAlong from the palette (plagueSkyHemisphere and
 * plagueGetSky, matching the low-level entry's parameter definitions above), then forwards. Every
 * caller that has not opted into the scattering tables uses this one: clouds_march.fsh always, and
 * clouds_march_volume.comp under PLAGUE_SKY_MODEL == 0. This file tests no compile option itself
 * (an import is spliced before the program's own defines, so a #if here would silently read 0, the
 * same rule atmo_lut.glsl states for itself): the program picks the overload.
 */
vec4 plagueGetClouds(vec3 viewDir, vec3 cameraPosAbs, float terrainDistance, float dither,
                     PlagueCloudDeck deck, PlagueSkyColors skyColours, PlagueLighting lighting,
                     vec3 sunDirTrue, float syncedTime, float renderDistance,
                     vec3 atmColorMult, out float cloudFrontDistance) {
    vec3 ambientDome = plagueSkyHemisphere(skyColours, skyColours.lightUp);
    float VdotS = dot(viewDir, sunDirTrue);
    vec3 skyAlong = plagueGetSky(skyColours, viewDir.y, VdotS, dither, true, false) * atmColorMult;
    return plagueGetClouds(viewDir, cameraPosAbs, terrainDistance, dither, deck, ambientDome,
                           skyAlong, lighting, sunDirTrue, syncedTime, renderDistance,
                           cloudFrontDistance);
}

/**
 * Transmittance of one deck along the sun ray.
 *
 * Mean of three heights, not max: optical depth is a path average, and the quarter heights avoid
 * both faces where the profile ramps. Coarse field, as the cloud's own sun march uses: an integral
 * does not care about the erosion detail.
 */
// Optical depth below which a deck's shadow is not worth three density samples. exp(-0.5) is 0.61
// at full density, and a deck this thin never reaches full density: its darkest shadow is a few
// percent. This runs per lit fragment, so every deck skipped here is three coarse samples saved on
// every pixel in the frame, water included.
const float PLAGUE_CLOUD_SHADOW_MIN_TAU = 0.5;

float plagueCloudDeckShadow(vec3 fragAbsPos, vec3 sunDir, PlagueCloudDeck deck, float syncedTime) {
    if (deck.tau <= PLAGUE_CLOUD_SHADOW_MIN_TAU || deck.population <= 0.0) {
        return 1.0;
    }
    vec2 drift = plagueCloudDrift(deck, syncedTime);
    float meanDensity = 0.0;
    for (int i = 0; i < 3; i++) {
        float sampleY = deck.base + deck.depth * (0.25 + 0.25 * float(i));
        float t = (sampleY - fragAbsPos.y) / sunDir.y;
        // t <= 0: this height is below the fragment (above the deck, or on a mountain inside it),
        // so skip rather than sample behind the fragment.
        if (t > 0.0) {
            meanDensity += plagueCloudDensityCoarse(fragAbsPos + sunDir * t, deck, drift);
        }
    }
    meanDensity /= 3.0;

    float slant = min(1.0 / max(sunDir.y, 1e-3), PLAGUE_CLOUD_SHADOW_MAX_SLANT);
    return exp(-deck.tau * meanDensity * slant * max(u_CloudShadowStrength, 0.0));
}

#else

// CLOUDS_VOLUMETRIC off: feature compiles away entirely; entry points survive as identities so
// callers don't need their own gate. Written out (not left to the caller) because
// gbuffer_resolve.fsh imports this file unconditionally to get the option declarations.

vec2 plagueCloudDrift(PlagueCloudDeck deck, float syncedTime) {
    return vec2(0.0);
}


float plagueCloudDensityAt(vec3 worldPos, PlagueCloudDeck deck, vec2 drift) {
    return 0.0;
}

float plagueCloudDensity(vec3 worldPos, PlagueCloudDeck deck, float syncedTime) {
    return 0.0;
}

vec4 plagueGetClouds(vec3 viewDir, vec3 cameraPosAbs, float terrainDistance, float dither,
                     PlagueCloudDeck deck, PlagueSkyColors skyColours, PlagueLighting lighting,
                     vec3 sunDirTrue, float syncedTime, float renderDistance,
                     vec3 atmColorMult, out float cloudFrontDistance) {
    cloudFrontDistance = 0.0;
    return vec4(0.0);
}

#endif // CLOUDS_VOLUMETRIC

#endif // PLAGUE_CLOUDS
