#!/usr/bin/env python3
"""Emit the exact option snapshot used by the cloud history diagnostic.

Only reads this pack's source. Snapshot all imported runtime declarations, including
unused options, so edits conservatively invalidate rather than collide in a hash.
Run with --check to detect stale generated shader/layout without editing live files.
"""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / 'shaders/include/cloud_history_state.glsl'

def generate():
    seen, names = set(), set()
    def visit(path):
        if path in seen or path == OUTPUT:
            return
        seen.add(path)
        source = path.read_text()
        for m in re.finditer(r'^#define\s+(u_\w+)\s+[^\n]+//\[[^\n]+', source, re.M):
            if 'compile' not in m[0]:
                names.add(m[1])
        for m in re.finditer(r'#moj_import\s+<fornax_runtime:([^>]+)>', source):
            visit(ROOT / 'shaders/include' / m[1])
    visit(ROOT / 'shaders/compute/clouds_march_volume.comp')
    options = sorted(names)
    # Rows 0..5 are frame facts; 6..12 are contributor transforms; 13 is wind.
    rows = (len(options) + 3) // 4
    lines = ['// Generated by tools/derive_cloud_history_state.py; regenerate after option changes.',
             '#ifndef PLAGUE_CLOUD_HISTORY_STATE', '#define PLAGUE_CLOUD_HISTORY_STATE',
             'const int PLAGUE_CLOUD_HISTORY_DECK_ROW = 6;',
             'const int PLAGUE_CLOUD_HISTORY_WIND_ROW = 13;',
             'const int PLAGUE_CLOUD_HISTORY_OPTION_ROW = 14;',
             f'const int PLAGUE_CLOUD_HISTORY_STATE_ROWS = {14 + rows};',
             '#ifdef PLAGUE_CLOUD_HISTORY_WRITE_STATE',
             'vec4 plagueCloudHistoryOptions(int row) {', '    switch (row) {']
    for i in range(rows):
        group = options[i*4:(i+1)*4]
        group += ['0.0'] * (4 - len(group))
        lines.append(f'        case {i}: return vec4({", ".join(group)});')
    lines += ['    }', '    return vec4(0.0);', '}', '#endif', '#endif', '']
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            raise SystemExit('FAIL: cloud history state snapshot is stale')
        print('ok: cloud history option snapshot matches imported declarations')
    else:
        OUTPUT.write_text(text)
        print(OUTPUT)

if __name__ == '__main__':
    main()
